import type { CountryId, CountryProfile, Macro } from "./types.ts";

/**
 * The six fictional economies. Each one is a different first job for a new
 * governor: names and numbers are invented, the mechanics are real.
 */
export const PROFILES: Record<CountryId, CountryProfile> = {
  velden: {
    id: "velden",
    currency: { zh: "维岚盾", en: "Velden guilder" },
    symbol: "ƒ",
    difficulty: 1,
    blurb: {
      zh: "富裕、谨慎、受人信任。央行信誉高，起点平稳——适合第一任期。",
      en: "Rich, careful and trusted. A credible bank and a calm start: a good first term.",
    },
    weight: 0.8,
    piStar: 2,
    rStar: 1,
    uStar: 4.5,
    gStar: 1.8,
    openness: 0.55,
    passthrough: 0.12,
    rrrBase: 3,
    deficitNorm: 1,
    commodity: false,
    start: { rate: 2.5, pi: 2.3, piE: 2.1, gap: 0.3, u: 4.4, trust: 78, debt: 45, deficit: 1, reserves: 18, bubble: 0.2, bank: 0.95 },
  },
  lion: {
    id: "lion",
    currency: { zh: "狮子币", en: "Leo" },
    symbol: "Ł",
    difficulty: 2,
    blurb: {
      zh: "大陆最大的经济体，正在过热：通胀爬升、楼市发烫，财政部却想要更多增长。",
      en: "The continent's largest economy, running hot: inflation creeping up, housing frothy, and a Treasury that wants more growth.",
    },
    weight: 2.4,
    piStar: 2,
    rStar: 1.5,
    uStar: 5,
    gStar: 2.2,
    openness: 0.35,
    passthrough: 0.15,
    rrrBase: 5,
    deficitNorm: 3,
    commodity: false,
    start: { rate: 2.5, pi: 3.4, piE: 2.8, gap: 1.4, u: 4.4, trust: 60, debt: 72, deficit: 3.5, reserves: 10, bubble: 0.45, bank: 0.85 },
  },
  nordlan: {
    id: "nordlan",
    currency: { zh: "诺德克朗", en: "Nordlan krone" },
    symbol: "kr",
    difficulty: 3,
    blurb: {
      zh: "寒冷的资源出口国，刚从油价暴跌里爬出来：物价几乎不涨，工厂在裁员。",
      en: "A cold commodity exporter just out of an oil slump: prices barely rising, factories laying off.",
    },
    weight: 0.7,
    piStar: 2,
    rStar: 1.2,
    uStar: 5.5,
    gStar: 1.9,
    openness: 0.6,
    passthrough: 0.2,
    rrrBase: 4,
    deficitNorm: 2,
    commodity: true,
    start: { rate: 1.75, pi: 0.4, piE: 1.2, gap: -2.4, u: 7.2, trust: 62, debt: 40, deficit: 3, reserves: 22, bubble: 0.1, bank: 0.9 },
  },
  dawei: {
    id: "dawei",
    currency: { zh: "大卫镑", en: "Dawei pound" },
    symbol: "D£",
    difficulty: 4,
    blurb: {
      zh: "世界的金融中心。银行太大、杠杆太高，资产价格已经离地面很远。",
      en: "The world's financial centre. Banks too big, leverage too high, asset prices a long way off the ground.",
    },
    weight: 1.8,
    piStar: 2,
    rStar: 1.3,
    uStar: 5,
    gStar: 2,
    openness: 0.5,
    passthrough: 0.12,
    rrrBase: 4,
    deficitNorm: 3,
    commodity: false,
    start: { rate: 1.5, pi: 2.4, piE: 2.2, gap: 1, u: 4.6, trust: 58, debt: 88, deficit: 4, reserves: 8, bubble: 0.62, bank: 0.7 },
  },
  serein: {
    id: "serein",
    currency: { zh: "瑟林里拉", en: "Serein lira" },
    symbol: "₤",
    difficulty: 4,
    blurb: {
      zh: "海岛共和国，靠游客和外债活着。债务压顶，汇率一碰就晃。",
      en: "An island republic living on tourists and foreign borrowing. Heavy debt, and a currency that wobbles at a touch.",
    },
    weight: 0.5,
    piStar: 2,
    rStar: 1.5,
    uStar: 7,
    gStar: 1.4,
    openness: 0.75,
    passthrough: 0.3,
    rrrBase: 5,
    deficitNorm: 4,
    commodity: false,
    start: { rate: 3.5, pi: 4.2, piE: 3.8, gap: -0.8, u: 8.4, trust: 44, debt: 122, deficit: 5, reserves: 6, bubble: 0.3, bank: 0.72 },
  },
  ramona: {
    id: "ramona",
    currency: { zh: "拉莫娜比索", en: "Ramona peso" },
    symbol: "₱",
    difficulty: 5,
    blurb: {
      zh: "年轻而躁动的新兴经济体。通胀两位数、没人信央行，资本随时会跑。",
      en: "A young, restless emerging economy. Double-digit inflation, a central bank nobody believes, capital ready to run.",
    },
    weight: 0.9,
    piStar: 3,
    rStar: 2.5,
    uStar: 6.5,
    gStar: 3.8,
    openness: 0.45,
    passthrough: 0.35,
    rrrBase: 8,
    deficitNorm: 4,
    commodity: false,
    start: { rate: 13.5, pi: 11.5, piE: 10.5, gap: 0.5, u: 6.2, trust: 28, debt: 58, deficit: 5, reserves: 7, bubble: 0.35, bank: 0.74 },
  },
};

export const COUNTRY_ORDER: CountryId[] = ["velden", "lion", "nordlan", "dawei", "serein", "ramona"];

export function initialMacro(id: CountryId): Macro {
  const p = PROFILES[id];
  const s = p.start;
  return {
    rate: s.rate ?? p.rStar + p.piStar,
    rrr: s.rrr ?? p.rrrBase,
    qe: s.qe ?? 0,
    qePace: 0,
    pi: s.pi ?? p.piStar,
    piE: s.piE ?? p.piStar,
    gap: s.gap ?? 0,
    u: s.u ?? p.uStar,
    growth: s.growth ?? p.gStar,
    fx: 100,
    fxYoY: 0,
    reserves: s.reserves ?? 10,
    debt: s.debt ?? 60,
    deficit: s.deficit ?? p.deficitNorm,
    credit: s.credit ?? 6,
    bubble: s.bubble ?? 0.2,
    bank: s.bank ?? 0.9,
    equity: 100,
    trust: s.trust ?? 60,
    stance: (s.rate ?? p.rStar + p.piStar) - (s.piE ?? p.piStar) - p.rStar,
    demand: 0,
    supply: 0,
  };
}
