import { WORLD_DATA } from "./world.data.ts";

/**
 * The fictional world map (G3), generated by blender/world_map.py.
 * Atlas units: x right, y down, 2400 × 1500. three.js world space (glTF is
 * Y-up) is x = (ax − 1200) / 100, z = (ay − 750) / 100, height on y.
 */
export const WORLD_SHEET = WORLD_DATA.sheet;
export const WORLD_COUNTRIES = WORLD_DATA.countries;
export const WORLD_PROVINCES = WORLD_DATA.provinces;
export const WORLD_SEAS = WORLD_DATA.seas;

export type WorldCountry = (typeof WORLD_COUNTRIES)[number];
export type WorldCountryId = WorldCountry["id"];
export type WorldProvince = (typeof WORLD_PROVINCES)[number];

/** Byte value the pick grid and the province texture use for open sea. */
export const SEA_ID = 255;

let grid: Uint8Array | null = null;
function pickGrid(): Uint8Array {
  grid ??= Uint8Array.from(atob(WORLD_DATA.pick.u8), (c) => c.charCodeAt(0));
  return grid;
}

export function atlasToWorld(x: number, y: number, height = 0): [number, number, number] {
  return [(x - WORLD_SHEET.w / 2) / 100, height, (y - WORLD_SHEET.h / 2) / 100];
}

export function worldToAtlas(wx: number, wz: number): [number, number] {
  return [wx * 100 + WORLD_SHEET.w / 2, wz * 100 + WORLD_SHEET.h / 2];
}

/** Province under an atlas point (12-unit resolution), or null over sea / off the sheet. */
export function provinceAt(x: number, y: number): WorldProvince | null {
  const { step, w, h } = WORLD_DATA.pick;
  const i = Math.round(x / step);
  const j = Math.round(y / step);
  if (i < 0 || j < 0 || i >= w || j >= h) return null;
  const id = pickGrid()[j * w + i]!;
  return id === SEA_ID ? null : (WORLD_PROVINCES[id] ?? null);
}

export function countryOf(id: WorldCountryId): WorldCountry {
  return WORLD_COUNTRIES.find((c) => c.id === id)!;
}
