import type { Scenario } from "../types.ts";
import { retailObjective, traderObjective } from "./seats.ts";

/**
 * 炼狱 — the long winter.
 *
 * Every other scenario in this game is a fight over days or weeks. This one is
 * four years, and the thing that makes it 炼狱 is not any single wave: it is
 * that the information never stops. The president's office, the legislature,
 * the court, the exchange, the clearing houses, the farm belt and the papers
 * all want a decision from you today, and the ones you refuse to make are
 * decisions too.
 *
 * The design inverts the rest of the ladder on purpose. Everywhere else,
 * holding the line is the job. Here the line is the gold parity, and the
 * record is unambiguous: the countries that let it go earliest recovered
 * earliest. So this seat is scored on `revive` — what you saved, not what you
 * held — and losing the line is a turning point rather than an ending.
 *
 * That is why the lever is a trap. Defending the parity works: it does hold
 * the gold. It also takes the banks, the output and the four years with it.
 */
export const DEPRESSION: Scenario = {
  id: "depression",
  kind: "depression",
  nameZh: "大萧条",
  nameEn: "The Great Depression",
  year: "1929–1933",
  grade: 10,
  order: 14,
  major: true,
  // The whole point is the back half. By the last winter a session carries
  // several times what the first autumn did.
  escalation: 2.6,
  // Losing the parity is the beginning of the recovery, not the end of the run.
  endsOnBreak: false,
  breakRelief: 0.16,
  crown: {
    id: "lender-of-last-resort",
    nameZh: "最后贷款人",
    nameEn: "Lender of Last Resort",
    blurbZh:
      "用三小时的篇幅，从崩盘一路坐到银行重新开门，并且把银行体系和产出一起带了回来。这是本作最难拿的东西——因为历史上没有人做到。",
    blurbEn:
      "Three hours, from the crash to the morning the banks reopened, with the banking system and output both brought back. The hardest thing in this game to hold — because nobody in the record managed it.",
  },
  briefZh:
    "崩盘已经是去年的事了。现在是漫长的那一段：每个月都有银行关门，每个月的失业数字都更难看，而你坐在中央银行的主席位上。你手上那根最有力的杠杆叫「黄金平价」——本币按固定比例兑换黄金，十几年没变过，它是这个国家信用的全部内容。守它的办法只有一个：把贴现率拉上去，让钱贵到没有人愿意把黄金换走。代价是所有还活着的银行、所有还在还贷的农场、所有还在开工的工厂。这一关不比谁守得住，比谁先看明白：有些线，是拿来断的。",
  briefEn:
    "The crash was last year. This is the long part: banks closing every month, an unemployment figure that gets worse every month, and you in the chair at the central bank. The strongest lever you hold is the gold parity — the currency convertible at a fixed rate, unchanged for a generation, and the entire content of this country's credit. There is exactly one way to hold it: put the discount rate up until money is too dear for anyone to take the gold away. The price is every bank still open, every farm still servicing a mortgage and every factory still running a shift. This one is not about who holds the line. It is about who works out first that some lines are meant to be let go.",
  historyZh:
    "史实：本关取材自美国大萧条（1929–1933）。道琼斯工业平均指数自 1929 年 9 月 3 日的 381.17 点跌至 1932 年 7 月 8 日的 41.22 点，跌幅约 89%；1933 年失业率约 25%。1930 至 1933 年间约 9,000 家美国银行倒闭，货币供应量（M2）萎缩约三分之一。1931 年 9 月 21 日英国脱离金本位后，美联储于同年 10 月将纽约联储的贴现率由 1.5% 上调至 3.5%，以阻止黄金外流——此举被广泛认为严重加剧了国内的银行危机。1933 年 3 月 6 日罗斯福宣布全国银行假日，3 月 9 日国会通过《紧急银行法》；4 月 5 日第 6102 号行政命令要求上缴私人持有的黄金，美国事实上脱离金本位；1934 年《黄金储备法》将金价由每盎司 20.67 美元定为 35 美元。1933 年《银行法》（格拉斯—斯蒂格尔法）设立了联邦存款保险公司（FDIC），存款保险自 1934 年 1 月 1 日生效。弗里德曼与施瓦茨在《美国货币史》（1963）中认为，美联储未能履行最后贷款人职责，是衰退演变为大萧条的关键机制；2002 年伯南克在弗里德曼九十岁生日会上公开表示：「关于大萧条，你们是对的，是我们干的。我们非常抱歉。」",
  historyEn:
    "History: this scenario is drawn from the Great Depression in the United States, 1929–1933. The Dow Jones Industrial Average fell from 381.17 on 3 September 1929 to 41.22 on 8 July 1932, about 89%, and unemployment reached roughly 25% in 1933. Some 9,000 American banks failed between 1930 and 1933 and the money supply (M2) contracted by about a third. After Britain left the gold standard on 21 September 1931 the Federal Reserve raised the New York discount rate from 1.5% to 3.5% that October to stem the gold outflow — a move widely held to have sharply worsened the domestic banking crisis. On 6 March 1933 Roosevelt declared a national bank holiday and Congress passed the Emergency Banking Act on 9 March; Executive Order 6102 of 5 April required private gold to be surrendered, taking the United States off gold in practice, and the Gold Reserve Act of 1934 repriced gold from $20.67 to $35 an ounce. The Banking Act of 1933 created the FDIC, with deposit insurance effective 1 January 1934. Friedman and Schwartz argued in A Monetary History of the United States (1963) that the Federal Reserve's failure to act as lender of last resort is what turned a recession into the Depression; in 2002 Ben Bernanke said publicly, 'Regarding the Great Depression, you're right, we did it. We're very sorry.'",
  historyDeepZh: [
    "美联储当时是分权的：12 家地区储备银行各自设定贴现率，纽约联储的哈里森主张大规模公开市场购买，其他多家储备银行反对。缺一个能一锤定音的人，正是这套制度当时的缺陷。",
    "1932 年 2 月的《格拉斯—斯蒂格尔法》允许以政府债券作为联邦储备券的抵押，解开了公开市场操作的法律约束。当年 4 月至 6 月美联储买入约 10 亿美元政府债券，经济一度出现企稳迹象——随后购买停止，形势再度恶化。",
    "1932 年 7 月至 1933 年 3 月，挤兑从内华达蔓延到密歇根，再蔓延到全国；到 3 月初，大多数州已自行宣布银行假日。",
    "银行假日之后，1933 年 3 月 13 日起银行分批重开，只有经审查确认稳健的才准开门。重开第一周，存款净流入。这件事说明问题从来不是钱不够，是没有人相信钱还在。",
    "国际比较是这一段最硬的证据：英国 1931 年脱离金本位、美国 1933 年、法国等「黄金集团」国家拖到 1936 年。脱离得越早，工业产出恢复得越早，顺序几乎没有例外。",
    "1935 年《银行法》把权力集中到华盛顿的联邦公开市场委员会，正是为了确保下一次不会再出现「十二个人各说各话」的局面。",
  ],
  historyDeepEn: [
    "The Federal Reserve was then decentralised: twelve reserve banks each set their own discount rate, and while New York's Harrison pushed for large open-market purchases, several others resisted. The absence of anyone who could settle the argument was the institutional flaw of the period.",
    "The Glass-Steagall Act of February 1932 allowed government bonds as collateral for Federal Reserve notes, removing the legal constraint on open-market operations. The Fed bought roughly US$1bn of governments between April and June that year and conditions briefly steadied — then the purchases stopped and things deteriorated again.",
    "From July 1932 to March 1933 the runs spread from Nevada to Michigan and then nationwide; by early March most states had declared bank holidays of their own.",
    "After the holiday, banks reopened in stages from 13 March 1933, and only those examined and found sound were allowed to open at all. In the first week back, deposits flowed in. The problem had never been that the money was short — it was that nobody believed the money was still there.",
    "The international comparison is the hardest evidence in this period: Britain left gold in 1931, the United States in 1933, and the 'gold bloc' countries held on until 1936. The earlier a country left, the earlier its industrial production recovered, with almost no exceptions.",
    "The Banking Act of 1935 concentrated authority in the Federal Open Market Committee in Washington, precisely so that twelve people talking past each other could not happen again.",
  ],
  lessonZh:
    "这一战教的是：「有些防线是拿来断的，问题只是你什么时候承认」。黄金平价是真的能守住的——把钱贵到没人愿意换走就行。代价是银行、农场和工厂，而这三样东西恢复起来要十年。真正的判断不是「我守不守得住」，是「守住它之后，我还剩什么」。另一件更重要的事：这一关里没有任何一个时刻是「决定性的一天」。它是四年里几百个小决定，每一个看起来都不致命，加起来把货币供应抽掉了三分之一。灾难很少以一场总攻的形式出现，它通常以「今天先不动」的形式出现。",
  lessonEn:
    "The lesson: some lines are meant to be let go, and the only question is when you admit it. The gold parity really can be held — you simply make money dear enough that nobody takes the gold. The price is the banks, the farms and the factories, and those take a decade to come back. The judgement is not whether you can hold it, but what is left once you have. And something more important still: there is no decisive day in this scenario. It is several hundred small decisions across four years, none of which looks fatal on its own, which between them take a third of the money supply out of the economy. Catastrophe rarely arrives as an assault. It usually arrives as 'let us not move today'.",
  lexicon: {
    lineZh: "黄金平价",
    lineEn: "the gold parity",
    gaugeZh: "黄金外流压力",
    gaugeEn: "Gold drain",
    breakZh: "平价断了。本币停止兑换黄金——枷锁掉了，现在你终于能放手救人。",
    breakEn: "The parity goes. Convertibility is suspended — the shackle is off, and you can finally reach for the people.",
    rateZh: "贴现率（守平价）",
    rateEn: "Discount rate (defends the parity)",
    potZh: "可动用资金",
    potEn: "Available funds",
    spendZh: "动用黄金储备兑付",
    spendEn: "Meet the drain in gold",
    buyZh: "公开市场买入 / 向银行注资",
    buyEn: "Open-market purchases and bank capital",
    marketZh: "银行与产出",
    marketEn: "Banks and output",
    shortLineZh: "囤积黄金",
    shortLineEn: "Hoard gold",
    shortEqZh: "退出银行股与实业",
    shortEqEn: "Get out of banks and industry",
  },
  seatLabel: {
    governor: { zh: "中央银行主席", en: "Central bank chair" },
    fund: { zh: "黄金囤积者", en: "The gold hoarder" },
    trader: { zh: "银行资金台", en: "Bank treasury desk" },
    retail: { zh: "小储户", en: "Small depositor" },
  },
  // Parity in local units per ounce. It is a number nobody expected to move.
  pegRate: 20.67,
  band: 0.04,
  reserves: 90_000,
  committedForward: 0,
  startRate: 0.015,
  maxRate: 0.09,
  allowEquityDefence: true,
  allowPledge: true,
  allowHalt: true,
  // Gold walks out of the door faster than it can be bought back.
  reserveEfficiency: 0.5,
  rateDefenceCap: 0.62,
  // The heaviest drag in the game, and the entire trap: the lever that holds
  // the parity is the lever that closes the banks.
  rateDragK: 0.44,
  // Open-market purchases work here and they work slowly, against a system
  // destroying deposits faster than a central bank can create them. Nowhere
  // else in the game is the buy lever this blunt, and nowhere else is it this
  // necessary.
  buyPotency: 0.45,
  // The bank holiday is the single most effective thing anybody did in these
  // four years, and it cost nothing but nerve.
  pledgeRelief: 0.22,
  days: 16,
  historicalOutcome: "broke",
  outcomeNoteZh:
    "历史上这条平价断了——1933 年 4 月，而且断得比任何人预想的晚。断掉的那一刻不是失败，是复苏的开始：脱离金本位越早的国家，产出恢复得越早。",
  outcomeNoteEn:
    "In the record this parity broke — in April 1933, and later than anybody should have let it. The moment it went was not the defeat; it was the start of the recovery. The earlier a country left gold, the sooner its output came back.",
  // The historical defence, and the historical mistake: hold the parity, hike
  // into a banking crisis, and reach for the market far too late.
  autoDefence: { spend: 0.08, nudgeOnDay: 4, nudgeTo: 0.035, hikeOnDay: 7, buyFrom: 14, buy: 0.1 },
  phases: [
    {
      day: 1,
      titleZh: "第一个冬天",
      titleEn: "The first winter",
      bodyZh: "崩盘过去一年，指数还在跌，但真正的消息在别处：中西部有四十家小银行没有开门。报纸放在第七版。",
      bodyEn: "A year past the crash and the index is still falling, but the real news is elsewhere: forty small banks in the interior did not open. The papers put it on page seven.",
      pressure: 0.1,
      equityShock: 0.05,
    },
    {
      day: 2,
      titleZh: "一家大行倒了",
      titleEn: "A large bank goes",
      bodyZh: "一家名字里带「合众」的大银行关门，存款四亿。它其实不是国家银行，但名字让所有人以为它是。",
      bodyEn: "A large bank with 'United' in its name closes, holding four hundred million of deposits. It was not a national institution at all — the name simply made everyone think it was.",
      pressure: 0.14,
      equityShock: 0.08,
    },
    {
      day: 4,
      titleZh: "邻国先走了",
      titleEn: "The neighbour goes first",
      bodyZh: "海对面那个国家宣布本币停止兑换黄金。第二天早上，全世界的资金开始问同一个问题：下一个是谁。你的黄金开始上船。",
      bodyEn: "The country across the water suspends convertibility. By the next morning money everywhere is asking the same question — who is next — and your gold starts boarding ships.",
      pressure: 0.3,
      equityShock: 0.07,
    },
    {
      day: 5,
      titleZh: "第一次大幅加息",
      titleEn: "The first big hike",
      bodyZh: "理事会里多数人主张把贴现率拉上去止住外流。会议纪要里没有人提到那四十家银行。",
      bodyEn: "A majority on the board wants the discount rate up to stop the outflow. Nobody in the minutes mentions the forty banks.",
      pressure: 0.12,
      equityShock: 0.1,
      minDetail: 1,
    },
    {
      day: 6,
      titleZh: "农业带",
      titleEn: "The farm belt",
      bodyZh: "农产品价格跌了六成，农场抵押贷款还不上。乡村银行是当地唯一的银行，它一关，整个县就没有银行了。",
      bodyEn: "Farm prices are down six-tenths and the mortgages cannot be serviced. The country bank is the only bank there is; when it closes, the county has none.",
      pressure: 0.16,
      equityShock: 0.11,
    },
    {
      day: 8,
      titleZh: "法律松绑了",
      titleEn: "The constraint comes off",
      bodyZh: "议会通过一项法案，允许以政府债券作为发钞抵押。捆住公开市场操作的那根绳子断了——现在你可以真正下场买了。",
      bodyEn: "The legislature passes an act allowing government bonds as note collateral. The rope around open-market operations is cut. You can actually go in and buy now.",
      pressure: -0.06,
      equityShock: -0.03,
      minDetail: 1,
    },
    {
      day: 9,
      titleZh: "买了两个月，然后停了",
      titleEn: "Two months of buying, then it stops",
      bodyZh: "连续买了两个月，数据开始企稳。理事会里有人说「够了，别过头」。于是停了。三周之后，一切回到原样。",
      bodyEn: "Two months of buying and the numbers begin to steady. Somebody on the board says 'enough, let us not overdo it'. So it stops. Three weeks later everything is back where it was.",
      pressure: 0.2,
      equityShock: 0.13,
    },
    {
      day: 10,
      titleZh: "囤积",
      titleEn: "Hoarding",
      bodyZh: "人们开始把钱从银行取出来放在家里。不是投机，是常识——常识现在正在抽干整个体系。",
      bodyEn: "People start taking money out of the banks and keeping it at home. Not speculation, common sense — and common sense is now draining the entire system.",
      pressure: 0.24,
      equityShock: 0.12,
    },
    {
      day: 11,
      titleZh: "一个州先关了",
      titleEn: "One state closes first",
      bodyZh: "一位州长宣布本州银行放假八天。这一招救了那个州，也告诉了另外四十七个州的储户：该排队了。",
      bodyEn: "A governor declares an eight-day bank holiday in his state. It saves that state, and it tells depositors in forty-seven others that it is time to queue.",
      pressure: 0.3,
      equityShock: 0.14,
      minDetail: 1,
    },
    {
      day: 12,
      titleZh: "挤兑全国化",
      titleEn: "The run goes national",
      bodyZh: "两周之内，大多数州各自宣布了银行假日。这不是一个协调的决定，这是四十八个互相看着对方做的决定。",
      bodyEn: "Within a fortnight most states have declared holidays of their own. This is not a coordinated decision; it is forty-eight of them watching each other.",
      pressure: 0.38,
      equityShock: 0.16,
    },
    {
      day: 13,
      titleZh: "最后一批黄金",
      titleEn: "The last of the gold",
      bodyZh: "外国央行开始把存放在这里的黄金运走。每一船都上头版，每一条头版都让下一船更快。",
      bodyEn: "Foreign central banks start shipping out the gold they keep here. Every sailing makes the front page, and every front page makes the next sailing faster.",
      pressure: 0.42,
      equityShock: 0.1,
      minDetail: 2,
    },
    {
      day: 14,
      titleZh: "就职周",
      titleEn: "Inauguration week",
      bodyZh: "新政府周六上任。从现在到那一天，没有人有权力做任何事——而队伍还在排。",
      bodyEn: "The new administration takes office on Saturday. Between now and then nobody has the authority to do anything at all — and the queues are still there.",
      pressure: 0.34,
      equityShock: 0.15,
    },
    {
      day: 15,
      titleZh: "最后一周",
      titleEn: "The last week",
      bodyZh: "这一周之后，这个体系要么重新开门，要么不再存在。你手上还剩下的每一样东西，都要在这几天用完。",
      bodyEn: "After this week the system either reopens or it does not exist. Everything you have left has to be spent in these few days.",
      pressure: 0.4,
      equityShock: 0.17,
    },
  ],
  calls: [
    {
      id: "dep-c1",
      day: 1,
      direction: "in",
      fromZh: "中西部储备银行",
      fromEn: "An interior reserve bank",
      roleZh: "行长",
      roleEn: "President",
      lines: [
        { zh: "主席，我这个区今天有十一家会员银行没开门。", en: "Chair — eleven member banks in my district did not open today." },
        { zh: "他们的抵押品是农场贷款。按我们的规矩，那不算合格抵押品。", en: "Their collateral is farm paper. Under our rules that is not eligible." },
      ],
      options: [
        {
          id: "widen",
          zh: "改规矩。今天就放宽合格抵押品的范围。",
          en: "Change the rule. Widen what counts as eligible, today.",
          effect: { equityMul: 1.05, pressure: 0.05, credibility: 0.08 },
          replyZh: "……有几位理事会反对。但我照办。",
          replyEn: "…Some of the board will object. I will do it.",
          tone: "good",
        },
        {
          id: "rules",
          zh: "规矩就是规矩。我们不是救济机构。",
          en: "The rule is the rule. We are not a relief agency.",
          effect: { equityMul: 0.95, pressure: -0.02, credibility: 0.04 },
          replyZh: "明白。那明天我这里会少十一家银行。",
          replyEn: "Understood. Then tomorrow I have eleven fewer banks.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c2",
      day: 2,
      direction: "in",
      fromZh: "证券交易所",
      fromEn: "The stock exchange",
      roleZh: "理事会主席",
      roleEn: "Chairman of the board",
      lines: [
        { zh: "指数今天又是一根长阴。我们想知道中央银行打算做什么。", en: "Another long red day. We would like to know what the central bank intends to do." },
      ],
      options: [
        {
          id: "clear",
          zh: "我们会买。规模、期限，下周公布。",
          en: "We will buy. Size and duration announced next week.",
          effect: { equityMul: 1.04, credibility: -0.04 },
          replyZh: "那我把这句话告诉会员。希望下周真有数字。",
          replyEn: "I will pass that to the members. I hope there is a number next week.",
          tone: "good",
        },
        {
          id: "vague",
          zh: "我们会密切关注形势。",
          en: "We are watching the situation closely.",
          effect: { equityMul: 0.97, pressure: 0.04 },
          replyZh: "「密切关注」在我们这行的意思是「什么都不做」。",
          replyEn: "'Watching closely' means, in my trade, 'doing nothing'.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c3",
      day: 3,
      direction: "in",
      fromZh: "总统办公室",
      fromEn: "The President's office",
      roleZh: "秘书长",
      roleEn: "Chief of staff",
      lines: [
        { zh: "总统想知道一件事，而且要一句话的回答：金本位保不保得住。", en: "The President wants one thing, in one sentence: can the gold standard be held." },
      ],
      options: [
        {
          id: "honest",
          zh: "保得住。但保住它的代价，是这个国家的银行。",
          en: "It can be held. The price of holding it is this country's banks.",
          effect: { credibility: 0.14, pressure: 0.05 },
          replyZh: "……这句话我会原样转达。他不会喜欢，但他需要听。",
          replyEn: "…I will pass that on exactly. He will not like it and he needs to hear it.",
          tone: "good",
        },
        {
          id: "reassure",
          zh: "保得住。这是我们的首要职责。",
          en: "It can be held. That is our first responsibility.",
          effect: { pressure: -0.06, credibility: -0.1 },
          replyZh: "他松了一口气。希望你是对的。",
          replyEn: "He is relieved. I hope you are right.",
          tone: "info",
        },
        {
          id: "refuse",
          zh: "这个问题不该由中央银行来回答。",
          en: "That is not a question for the central bank to answer.",
          effect: { pressure: 0.08, credibility: -0.05 },
          replyZh: "那他会去问别人。别人的答案你未必喜欢。",
          replyEn: "Then he will ask somebody else. You may not care for their answer.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c4",
      day: 4,
      direction: "in",
      fromZh: "外国央行",
      fromEn: "A foreign central bank",
      roleZh: "行长",
      roleEn: "Governor",
      lines: [
        { zh: "我们今晚宣布停止兑换黄金。给你打这通电话是出于礼貌。", en: "We suspend convertibility tonight. This call is a courtesy." },
        { zh: "我的建议是：别学我们，或者赶紧学我们。两者之间没有第三条路。", en: "My advice: either do not follow us, or follow us immediately. There is no third road." },
      ],
      options: [
        {
          id: "ask",
          zh: "你们为什么现在放手？",
          en: "Why let go now?",
          effect: { credibility: 0.06 },
          replyZh: "因为我们算了一下守住要花多少，然后看了一眼还剩多少人在上班。",
          replyEn: "Because we worked out what holding it would cost, and then looked at how many people were still going to work.",
          tone: "info",
        },
        {
          id: "resent",
          zh: "你们这一步把压力全推给了我。",
          en: "That step pushes the whole weight onto me.",
          effect: { pressure: 0.06 },
          replyZh: "是的。总得有人先走，而先走的那个总是被这么说。",
          replyEn: "Yes. Somebody has to go first, and whoever goes first always hears this.",
          tone: "info",
        },
      ],
    },
    {
      id: "dep-c5",
      day: 5,
      direction: "in",
      fromZh: "理事会",
      fromEn: "The board",
      roleZh: "多数派",
      roleEn: "The majority",
      lines: [
        { zh: "黄金一周走了两亿。我们要求立刻把贴现率提高两个点。", en: "Two hundred million of gold left this week. We want the discount rate up two points, immediately." },
        { zh: "这是十二家储备银行里九家的意见。", en: "That is nine of the twelve reserve banks." },
      ],
      options: [
        {
          id: "comply",
          zh: "照做。先止住外流。",
          en: "Do it. Stop the outflow first.",
          effect: { pressure: -0.12, equityMul: 0.9 },
          replyZh: "明早生效。……主席，我希望我们是对的。",
          replyEn: "Effective in the morning. …Chair, I hope we are right.",
          tone: "bad",
        },
        {
          id: "refuse",
          zh: "不提。外面每关一家银行，就少一个人来换黄金。",
          en: "No. Every bank that closes out there is one fewer person coming for the gold.",
          effect: { pressure: 0.1, equityMul: 1.06, credibility: 0.1 },
          replyZh: "那这件事会写进纪要，署你的名字。",
          replyEn: "Then it goes in the minutes with your name on it.",
          tone: "good",
        },
        {
          id: "half",
          zh: "提一半，同时开始公开市场买入。两头都做。",
          en: "Half of it, and start buying in the open market at the same time. Both ends.",
          effect: { pressure: -0.06, equityMul: 0.97 },
          replyZh: "折中方案。通常意味着两件事都做不成。",
          replyEn: "A compromise. Which usually means neither thing gets done.",
          tone: "info",
        },
      ],
    },
    {
      id: "dep-c6",
      day: 6,
      direction: "in",
      fromZh: "农会",
      fromEn: "The farmers' association",
      roleZh: "会长",
      roleEn: "President",
      minDetail: 1,
      lines: [
        { zh: "主席先生，我们县今天有四百个农场被法拍。", en: "Mr Chairman, four hundred farms in my county went to foreclosure sale today." },
        { zh: "有人举着枪站在拍卖官前面。我不是在威胁你，我是在告诉你现在是什么样子。", en: "A man stood in front of the auctioneer with a rifle. I am not threatening you; I am telling you what it looks like out there." },
      ],
      options: [
        {
          id: "listen",
          zh: "我知道了。这件事我会在下次会议上原话念出来。",
          en: "I hear you. I will read that out, word for word, at the next meeting.",
          effect: { credibility: 0.1, equityMul: 1.02 },
          replyZh: "念出来不能让谁拿回农场。但至少有人听见了。",
          replyEn: "Reading it out will not give anybody their farm back. At least somebody heard it.",
          tone: "good",
        },
        {
          id: "mandate",
          zh: "农业价格不在中央银行的职责范围内。",
          en: "Farm prices are outside this bank's mandate.",
          effect: { credibility: -0.12, equityMul: 0.96, pressure: 0.05 },
          replyZh: "那请您告诉我，谁的职责范围里有我们。",
          replyEn: "Then tell me whose mandate we are inside.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c7",
      day: 7,
      direction: "out",
      fromZh: "财政部",
      fromEn: "The Treasury",
      roleZh: "部长",
      roleEn: "Secretary",
      minDetail: 1,
      lines: [
        { zh: "你要的东西需要立法。国会现在什么都不想通过。", en: "What you want needs legislation. This legislature does not want to pass anything." },
        { zh: "除非你给他们一个他们能在选区里说出口的理由。", en: "Unless you hand them a reason they can say out loud back home." },
      ],
      options: [
        {
          id: "frame",
          zh: "就说这是为了让小银行明天还能开门。这句话是真的。",
          en: "Tell them it is so the small banks can open tomorrow. That happens to be true.",
          effect: { pressure: -0.08, credibility: 0.08 },
          replyZh: "这个能过。我周一就递上去。",
          replyEn: "That passes. It goes up on Monday.",
          tone: "good",
        },
        {
          id: "technical",
          zh: "照技术理由写。抵押品范围、法定准备金比例。",
          en: "Write it on the technical grounds. Collateral eligibility, required reserves.",
          effect: { pressure: 0.04 },
          replyZh: "那就要吵三个月。三个月之后这些银行还在不在？",
          replyEn: "Then we argue for three months. Will those banks still be there in three months?",
          tone: "info",
        },
      ],
    },
    {
      id: "dep-c8",
      day: 8,
      direction: "in",
      fromZh: "国会银行委员会",
      fromEn: "The legislature's banking committee",
      roleZh: "主席",
      roleEn: "Chair",
      lines: [
        { zh: "法案过了。你现在可以用政府债券做抵押发钞。", en: "The bill passed. You may now issue against government bonds." },
        { zh: "我个人想问一句：你打算买多少？", en: "Personally I would like to ask: how much do you intend to buy?" },
      ],
      options: [
        {
          id: "big",
          zh: "买到形势转向为止。我不给数字，我给条件。",
          en: "Until conditions turn. I will not give a number; I will give a condition.",
          effect: { equityMul: 1.07, credibility: 0.12, pressure: 0.04 },
          replyZh: "这是我这几年听过最像个中央银行说的话。",
          replyEn: "That is the most central-bank thing I have heard anyone say in years.",
          tone: "good",
        },
        {
          id: "cautious",
          zh: "先买一亿，看看效果。",
          en: "A hundred million to start, and we see.",
          effect: { equityMul: 1.02 },
          replyZh: "「看看效果」的意思是，效果出来之前你什么都不会再买。",
          replyEn: "'And we see' means you will not buy anything else until you have seen.",
          tone: "info",
        },
      ],
    },
    {
      id: "dep-c9",
      day: 9,
      direction: "in",
      fromZh: "理事会",
      fromEn: "The board",
      roleZh: "两位反对者",
      roleEn: "Two dissenters",
      lines: [
        { zh: "买了两个月，数据确实好转了。所以我们认为可以停了。", en: "Two months of buying and the numbers are better. Which is why we think it can stop." },
        { zh: "再买下去会通货膨胀。", en: "Any more and we get inflation." },
      ],
      options: [
        {
          id: "continue",
          zh: "不停。好转是因为在买，不是因为可以不买了。",
          en: "It does not stop. It is better because we are buying, not because we can stop.",
          effect: { equityMul: 1.08, credibility: 0.1, pressure: 0.05 },
          replyZh: "我们会记录反对意见。但我们服从。",
          replyEn: "We will record our dissent. And we will comply.",
          tone: "good",
        },
        {
          id: "stop",
          zh: "停。见好就收。",
          en: "Stop. Take the improvement and hold.",
          effect: { equityMul: 0.88, pressure: 0.1 },
          replyZh: "三周之后，那份数据会回到原来的位置。",
          replyEn: "In three weeks that number will be back where it started.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c10",
      day: 10,
      direction: "in",
      fromZh: "《晨报》",
      fromEn: "The morning paper",
      roleZh: "总编",
      roleEn: "Editor",
      minDetail: 1,
      lines: [
        { zh: "我们拿到了一份名单：本周可能关门的银行。", en: "We have a list: banks that may not open this week." },
        { zh: "我可以登，也可以不登。我想先听听你的意见。", en: "I can run it or not run it. I wanted your view first." },
      ],
      options: [
        {
          id: "dontrun",
          zh: "别登。名单一上报纸，名单上的银行今天就会倒。",
          en: "Do not run it. The moment that list is printed, everything on it closes today.",
          effect: { pressure: -0.1, equityMul: 1.04, credibility: -0.08 },
          replyZh: "我压下来了。但如果有一家真的倒了，我会写我为什么压。",
          replyEn: "I am holding it. If one of them does fail, I will write about why I held it.",
          tone: "info",
        },
        {
          id: "run",
          zh: "登。储户有权知道自己的钱在哪。",
          en: "Run it. Depositors are entitled to know where their money is.",
          effect: { pressure: 0.14, equityMul: 0.94, credibility: 0.08 },
          replyZh: "明早见报。……我希望我们两个都做对了。",
          replyEn: "It runs in the morning. …I hope we have both done the right thing.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c11",
      day: 11,
      direction: "in",
      fromZh: "某州州长",
      fromEn: "A state governor",
      roleZh: "州政府",
      roleEn: "The statehouse",
      lines: [
        { zh: "我明早宣布本州银行放假八天。我不是在征求意见，我是在通知你。", en: "I declare an eight-day bank holiday in this state tomorrow morning. I am not asking; I am informing you." },
      ],
      options: [
        {
          id: "coordinate",
          zh: "那就别只有你一个州。我今晚联系其他人，一起来。",
          en: "Then do not do it alone. I will call the others tonight; all at once.",
          effect: { pressure: -0.14, equityMul: 1.03, credibility: 0.1 },
          replyZh: "一起来的话，我这里就不是最弱的那个了。谢谢。",
          replyEn: "If we all go, mine is not the weakest one. Thank you.",
          tone: "good",
        },
        {
          id: "oppose",
          zh: "别做。你一关，隔壁两个州明早就要排队。",
          en: "Do not. The moment you close, two states over start queueing in the morning.",
          effect: { pressure: 0.16, equityMul: 0.95 },
          replyZh: "我知道。可是今天要排队的是我的人。",
          replyEn: "I know. And the people queueing today are mine.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c12",
      day: 12,
      direction: "in",
      fromZh: "最高法院书记官",
      fromEn: "The court registrar",
      roleZh: "紧急申请",
      roleEn: "Emergency application",
      minDetail: 1,
      lines: [
        { zh: "有人提起诉讼，主张你扩大抵押品范围的决定超出了法定权限。", en: "A suit argues that widening eligible collateral exceeded your statutory powers." },
        { zh: "法院可以暂缓执行，等我们审。您有什么要陈述的？", en: "The court can stay the measure pending review. Do you wish to be heard?" },
      ],
      options: [
        {
          id: "defend",
          zh: "有。法条写的是「在非常时期」，现在就是非常时期。",
          en: "I do. The statute says 'in unusual circumstances'. These are unusual circumstances.",
          effect: { credibility: 0.12, pressure: -0.04 },
          replyZh: "记录在案。法院不会立刻暂缓。",
          replyEn: "So noted. The court will not stay it today.",
          tone: "good",
        },
        {
          id: "yield",
          zh: "我们暂停该措施，等法院裁决。",
          en: "We will suspend the measure pending the ruling.",
          effect: { equityMul: 0.92, pressure: 0.12 },
          replyZh: "那这几周里，那些银行就没有抵押品了。",
          replyEn: "Then for those weeks, those banks have no collateral.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c13",
      day: 12,
      direction: "out",
      fromZh: "十二家储备银行",
      fromEn: "All twelve reserve banks",
      roleZh: "同时接入的电话会议",
      roleEn: "All on one line",
      minDetail: 2,
      lines: [
        { zh: "主席，十二个人，十二个意见。这就是我们的制度。", en: "Chair — twelve people, twelve opinions. That is our constitution." },
        { zh: "您要我们统一行动，就得有人把话说死。", en: "If you want us to act as one, somebody has to say it and mean it." },
      ],
      options: [
        {
          id: "command",
          zh: "我说死：今天起统一贴现率，统一买入，谁反对写进纪要。",
          en: "I will say it: one discount rate, one buying programme, from today. Dissent goes in the minutes.",
          effect: { equityMul: 1.06, pressure: -0.08, credibility: 0.12 },
          replyZh: "……那就照办。这个先例以后会被写进法律。",
          replyEn: "…Then it is done. That precedent will end up in the statute one day.",
          tone: "good",
        },
        {
          id: "consensus",
          zh: "我们再开一次会，争取共识。",
          en: "We will meet again and try for consensus.",
          effect: { equityMul: 0.94, pressure: 0.1 },
          replyZh: "共识需要时间。外面的队伍不需要。",
          replyEn: "Consensus takes time. The queues outside do not.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c14",
      day: 13,
      direction: "in",
      fromZh: "外国央行 · 托管部",
      fromEn: "A foreign central bank — custody",
      roleZh: "运输通知",
      roleEn: "Shipping notice",
      minDetail: 2,
      lines: [
        { zh: "我们要把存放在贵行的黄金运回去。下周三装船。", en: "We are shipping home the gold we hold with you. It loads on Wednesday." },
      ],
      options: [
        {
          id: "let",
          zh: "照办。拦下来只会让明天来的人更多。",
          en: "Ship it. Blocking it only means more of them tomorrow.",
          effect: { pressure: 0.12, credibility: 0.1 },
          replyZh: "谢谢您的专业。我们会低调处理。",
          replyEn: "Thank you for being professional about it. We will keep it quiet.",
          tone: "info",
        },
        {
          id: "delay",
          zh: "请推迟两周。给我两周。",
          en: "Please hold it two weeks. Give me two weeks.",
          effect: { pressure: -0.08, credibility: -0.12 },
          replyZh: "……可以。但这件事会传出去，而且会被读成你没钱了。",
          replyEn: "…Very well. It will get out, and it will be read as you being short.",
          tone: "info",
        },
      ],
    },
    {
      id: "dep-c15",
      day: 14,
      direction: "in",
      fromZh: "候任政府",
      fromEn: "The incoming administration",
      roleZh: "过渡小组",
      roleEn: "The transition team",
      lines: [
        { zh: "周六之前我们没有权力，现任政府没有意愿。这四天是空的。", en: "We have no authority until Saturday and the outgoing side has no appetite. These four days are empty." },
        { zh: "你是这四天里唯一一个能做事的人。", en: "You are the only person who can do anything in them." },
      ],
      options: [
        {
          id: "act",
          zh: "那我来做。后果我担。",
          en: "Then I will do it, and I will carry it.",
          effect: { equityMul: 1.07, pressure: -0.1, credibility: 0.14 },
          replyZh: "周六之后我们会把它合法化。撑住。",
          replyEn: "We will make it lawful on Saturday. Hold on.",
          tone: "good",
        },
        {
          id: "wait",
          zh: "等周六。现在做，法律上站不住。",
          en: "Wait for Saturday. Anything now has no legal footing.",
          effect: { equityMul: 0.9, pressure: 0.14 },
          replyZh: "法律上站得住，人站不住。周六见。",
          replyEn: "Legally sound and humanly not. We will see you Saturday.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c16",
      day: 15,
      direction: "in",
      fromZh: "银行公会",
      fromEn: "The bankers' association",
      roleZh: "理事长",
      roleEn: "Chairman",
      minDetail: 1,
      lines: [
        { zh: "如果要放假，重开的时候怎么办？全部一起开，还是审过才开？", en: "If there is a holiday — what happens when we reopen? Everyone at once, or only those examined?" },
      ],
      options: [
        {
          id: "examined",
          zh: "审过才开。开门的那一家，必须是储户不用怀疑的那一家。",
          en: "Only those examined. A bank that opens has to be one nobody needs to wonder about.",
          effect: { equityMul: 1.08, pressure: -0.1, credibility: 0.12 },
          replyZh: "有些会员会永远开不了门。但剩下的会有人排队存钱，不是取钱。",
          replyEn: "Some members will never open again. And the ones that do will have a queue putting money in, not taking it out.",
          tone: "good",
        },
        {
          id: "all",
          zh: "一起开。不能让任何一家被贴上标签。",
          en: "All at once. Nobody gets labelled.",
          effect: { equityMul: 0.93, pressure: 0.12 },
          replyZh: "那开门第一天，最弱的那几家会再倒一次，然后一切重来。",
          replyEn: "Then on the first morning the weakest go again, and we start over.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c17",
      day: 16,
      direction: "out",
      fromZh: "全国广播",
      fromEn: "The national broadcast",
      roleZh: "麦克风已开",
      roleEn: "The microphone is live",
      minDetail: 1,
      lines: [
        { zh: "六千万人在收音机前面。您有十分钟。", en: "Sixty million people are at their radios. You have ten minutes." },
        { zh: "讲稿在您手上。也可以不念。", en: "The script is in your hand. You do not have to read it." },
      ],
      options: [
        {
          id: "plain",
          zh: "不念了。我用最简单的话讲银行是怎么运作的，以及为什么把钱放回去比放在床垫下面安全。",
          en: "I am not reading it. I will explain in the plainest words how a bank works, and why the money is safer back inside one than under a mattress.",
          effect: { equityMul: 1.12, pressure: -0.16, credibility: 0.15 },
          replyZh: "……播完了。第二天早上，排队的人是来存钱的。",
          replyEn: "…And it is done. The next morning, the queue is there to deposit.",
          tone: "good",
        },
        {
          id: "formal",
          zh: "照稿念。这种时候要庄重。",
          en: "Read the script. This is a moment for gravity.",
          effect: { equityMul: 1.01, credibility: 0.03 },
          replyZh: "很得体。第二天早上，排队的人还是来取钱的。",
          replyEn: "Very proper. The next morning, the queue is still there to withdraw.",
          tone: "info",
        },
        {
          id: "skip",
          zh: "不讲。中央银行不该上广播。",
          en: "No broadcast. A central bank does not go on the radio.",
          effect: { equityMul: 0.94, pressure: 0.12 },
          replyZh: "那这十分钟会留给别人。别人未必懂银行。",
          replyEn: "Then the ten minutes go to somebody else. Who may not understand banks.",
          tone: "bad",
        },
      ],
    },
    {
      id: "dep-c18",
      day: 16,
      direction: "in",
      fromZh: "一位小储户",
      fromEn: "A small depositor",
      roleZh: "打到公开热线",
      roleEn: "Through the public line",
      minDetail: 3,
      seats: ["governor", "retail"],
      lines: [
        { zh: "先生，我一辈子存了四百块，在街角那家银行里。", en: "Sir, I have four hundred dollars saved over a lifetime, in the bank on the corner." },
        { zh: "我不懂黄金。我只想知道礼拜一我能不能拿到。", en: "I do not understand gold. I want to know whether I can have it on Monday." },
      ],
      options: [
        {
          id: "yes",
          zh: "能。礼拜一它会开门，而且是审查过才开的。",
          en: "You can. It opens Monday, and it opens because it was examined first.",
          effect: { equityMul: 1.05, pressure: -0.08, credibility: 0.1 },
          replyZh: "……那我不去排队了。谢谢您接我的电话。",
          replyEn: "…Then I will not queue. Thank you for taking the call.",
          tone: "good",
        },
        {
          id: "unsure",
          zh: "我不能保证任何一家具体的银行。",
          en: "I cannot make a promise about any one bank.",
          effect: { equityMul: 0.95, pressure: 0.1 },
          replyZh: "我明白了。那我明天一早就去。",
          replyEn: "I understand. I will go first thing tomorrow.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.55,
      titleZh: "撑过这个冬天",
      titleEn: "Get through the winter",
      howZh: "你有四百块在街角那家银行里。这一关没有内线可听，只有一个判断：钱放在银行、放在床垫下面、还是换成黄金。三个答案在不同的年份各对一次。",
      howEn: "You have four hundred dollars in the bank on the corner. There is no inside line here, only one judgement: bank, mattress, or gold. Each of those three answers is right in a different year.",
      winZh: "最后一天净值还剩 55% 以上。这条线比别的关都低，因为这四年里没有人是完好的。",
      winEn: "End with 55% of your net worth or more. The bar is the lowest on the ladder, because nobody came through these four years whole.",
      trapZh: "所有人都把钱取出来，才是银行倒闭的原因。你是对的，而且正因为所有人都跟你一样对，所以大家都完了。",
      trapEn: "Everybody taking their money out is what closes the bank. You are right — and because everybody is right in the same way, everybody loses.",
    }),
    trader: traderObjective({
      target: 0.9,
      titleZh: "在通缩里活着",
      titleEn: "Make money in a deflation",
      howZh: "这四年里，现金每天都在变贵，而所有生意每天都在变便宜。你的台子要做的不是找机会，是别在还没到底的时候把子弹打光。",
      howEn: "For four years cash gets dearer every day and every business gets cheaper every day. Your desk's job is not to find the opportunity — it is to not be out of ammunition before the bottom.",
      winZh: "最后一天自己的账面收益 ≥ +90%。四年的通缩里，做对方向的人赚的不是一点点——这条线设得高，因为做对了本来就该赚这么多。",
      winEn: "Finish up 90% or more on your own book. Four years of deflation pays the people who read it correctly very well indeed — the bar is high because getting it right was worth that much.",
      trapZh: "「已经跌了 70%，不可能再跌」——从 381 点到 41 点，这句话被说了整整三年。",
      trapEn: "'Down seventy per cent, it cannot fall further.' From 381 to 41, that sentence was said for three straight years.",
    }),
    fund: {
      side: "attack",
      kind: "profit",
      target: 1.0,
      titleZh: "什么都不持有",
      titleEn: "Own nothing",
      howZh: "通缩里最好的仓位是「什么都不持有」，而这需要两个动作，不是一个。把纸换成金属只是其中一半；另一半是退出银行股、退出实业、退出所有靠借钱运转的东西。只做前一半的人，四年之后拿着一柜子金条和一堆废纸。",
      howEn: "In a deflation the best position is owning nothing, and that takes two moves rather than one. Turning paper into metal is half of it; the other half is getting out of the banks, out of industry, out of everything that runs on borrowed money. Whoever only does the first half ends these four years with a vault of bullion and a drawer of worthless paper.",
      winZh: "最后一天自己的账面收益 ≥ +100%。",
      winEn: "Finish up 100% or more on your own book.",
      trapZh: "只囤黄金是不够的——金价在平价断掉之前是固定的，它一分钱都不会涨。真正赚钱的那一半，是你没有持有的那些东西。",
      trapEn: "Gold alone is not enough: while the parity holds, the gold price is fixed and does not move a cent. The half that pays is the half you did not own.",
    },
    governor: {
      side: "defend",
      kind: "revive",
      // Measured on the banking-and-output board, not on the line.
      target: 58,
      titleZh: "把银行带回来",
      titleEn: "Bring the banks back",
      howZh: "这一关和阶梯上其它所有关都相反：「你不是来守住防线的」。 贴现率确实能守住黄金平价——但它每守一天，就关掉一批银行、拍卖一批农场。你的资金只有一份，花在守平价上就买不了债券。真正要做的是：把钱投向银行和产出，在该放手的时候放手，并且在最后那一周用掉你唯一的那次全国性承诺。信息会从总统、国会、法院、交易所、农会、报社同时压过来，你必须一直在线——漏掉的电话也是一种决定。",
      howEn: "This one runs against every other rung on the ladder — you are not here to hold the line. The discount rate really will hold the gold parity, and every day it does, it closes another set of banks and auctions another set of farms. You have one pot of money: spent on the parity, it is not buying bonds. What you actually do is put the money into the banks and into output, let go when it is time to let go, and spend your one national commitment in the final week. The information comes at you from the president, the legislature, the court, the exchange, the farm belt and the papers at once, and you have to stay on the line — a call you miss is a decision too.",
      winZh: "最后一天「银行与产出」指数在 58 以上（开局 100）。黄金平价断不断，不影响判定——历史上它断了，而断掉的那一天是复苏的开始。",
      winEn: "Finish with the banks-and-output index above 58 (it opens at 100). Whether the gold parity survives does not enter the verdict — in the record it broke, and the day it broke was the start of the recovery.",
      trapZh: "把贴现率拉满，平价一定守得住。四年之后你会守着一个完整的黄金平价，和一个关掉了三分之一银行、失业四分之一人口的国家。这一关的地狱之处在于：那个选项每一天看起来都是负责任的那一个。",
      trapEn: "Max the discount rate and the parity will certainly hold. Four years later you will be holding an intact gold parity, a third of the banks closed and a quarter of the workforce out. What makes this one 炼狱 is that on any given day, that option looks like the responsible one.",
    },
  },
};
