import type { Scenario } from "../types.ts";
import { LEVERAGE_LEXICON, retailObjective, traderObjective } from "./seats.ts";

/**
 * Two unwinds, ten years apart.
 *
 * 1998 is one fund with the best mathematics anybody had ever put in a room,
 * undone by the one assumption the mathematics could not carry: that when you
 * need to sell, somebody is buying. 2008 is the same failure wholesale — the
 * short-term funding of the entire system, run on collateral whose value
 * everybody had agreed not to argue about.
 */

export const LTCM: Scenario = {
  id: "ltcm",
  kind: "leverage",
  nameZh: "恒远资本的四十五天",
  nameEn: "Forty-five Days at Evergreen",
  year: "1998",
  grade: 6,
  order: 10,
  major: true,
  briefZh:
    "这家基金的合伙人名单上有两位诺贝尔奖得主。它的策略不赌方向：找两个本该收敛的价格，做多便宜的那个、做空贵的那个，等它们靠拢。每一笔的利润薄得像刀片，所以要用二十五倍杠杆把刀片叠起来。过去三年它每年赚四成，去年还把二十七亿资本退还给了投资人——因为「好机会不够多了」。杠杆因此更高。八月十七号，一个大国宣布对本币债务违约，而所有本该收敛的价格，开始朝相反的方向跑。",
  briefEn:
    "There are two Nobel laureates on this fund's masthead. The strategy does not bet on direction: find two prices that ought to converge, buy the cheap one, sell the dear one, and wait. Each trade's edge is razor-thin, so you stack twenty-five razors on top of each other. It has returned about forty per cent a year for three years and last winter it handed $2.7bn of capital back to investors, because there were not enough good trades to go round. Which made the leverage higher. On the seventeenth of August a large country defaults on its own domestic debt, and every price that was supposed to converge starts running the other way.",
  historyZh:
    "史实：长期资本管理公司（LTCM）成立于 1994 年，合伙人包括默顿与斯科尔斯（两人于 1997 年获诺贝尔经济学奖）。1995 至 1997 年净回报分别约为 21%、43%、41%。1997 年底公司向投资者返还约 27 亿美元资本。1998 年初，其权益资本约 47 亿美元，资产约 1,250 亿美元，杠杆约 25 倍，衍生品名义本金约 1.25 万亿美元。1998 年 8 月 17 日俄罗斯对国内债务违约并让卢布贬值，引发全球避险，本应收敛的利差反而扩大。LTCM 仅 8 月 21 日一天亏损约 5.5 亿美元，8 月全月亏损约 44%，累计亏损约 46 亿美元。9 月 23 日，纽约联储召集 14 家机构，最终由其中多家出资约 36.25 亿美元接管该基金（贝尔斯登拒绝参与）。基金于 2000 年初清盘。",
  historyEn:
    "History: Long-Term Capital Management was founded in 1994; its partners included Robert Merton and Myron Scholes, who shared the 1997 Nobel prize in economics. Net returns ran about 21%, 43% and 41% from 1995 to 1997. At the end of 1997 the fund returned roughly US$2.7bn of capital to investors. By early 1998 it held about US$4.7bn of equity against some US$125bn of assets — around 25 to 1 — with derivative notionals near US$1.25trn. On 17 August 1998 Russia defaulted on its domestic debt and devalued the rouble, triggering a flight to quality in which the spreads that were supposed to converge widened instead. LTCM lost roughly US$550m on 21 August alone, about 44% over the month, and some US$4.6bn in total. On 23 September the Federal Reserve Bank of New York convened fourteen institutions; a group of them recapitalised the fund with about US$3.625bn (Bear Stearns declined to take part). The fund was wound down by early 2000.",
  historyDeepZh: [
    "LTCM 的仓位在市场上并非秘密：许多交易对手同时是它的主经纪商，知道它持有什么，也知道它必须卖什么。8 月底开始，有交易台按这些仓位反向操作。",
    "该基金的风险模型以历史波动率为基础，其压力测试并未涵盖多个市场同时流动性枯竭的情形——当所有相关性一起趋近 1，分散化本身消失了。",
    "9 月初，合伙人曾尝试自行募集新资本，包括向多家机构与个人投资者发出邀约，均未成功。",
    "9 月 23 日的会议上，另一家机构曾提出以远低于账面的价格整体收购该基金，被合伙人拒绝；当天晚些时候达成的是 14 家机构的联合出资方案。",
    "这次救助没有动用公共资金，但它开创了一个先例：一家私人基金因为「太互联」而被有组织地救下来。这个先例在十年后被反复引用。",
  ],
  historyDeepEn: [
    "LTCM's positions were not a secret: many of its counterparties were also its prime brokers, knew what it held, and knew what it would have to sell. From late August some desks traded against exactly those positions.",
    "The fund's risk model was built on historical volatility, and its stress tests did not cover simultaneous illiquidity across several markets at once — when every correlation goes to one, diversification itself disappears.",
    "In early September the partners tried to raise fresh capital themselves, approaching institutions and individual investors. None of it came together.",
    "At the 23 September meeting another firm offered to buy the fund outright at far below book; the partners refused, and what was agreed later that day was the fourteen-institution consortium.",
    "No public money was used — but the rescue set a precedent: a private fund organised into safety because it was too interconnected to be allowed to fail. That precedent was cited repeatedly ten years later.",
  ],
  lessonZh:
    "这一战教的是：「分散化是一个假设，不是一个属性」。你的十六笔交易在不同的国家、不同的资产、不同的期限上，模型说它们互不相关——直到所有人在同一个早上都想变现，于是它们变成了同一笔交易。真正要问的问题不是「我赚的概率有多大」，是「如果我必须在最差的那一周卖掉它，我卖得掉吗」。杠杆不改变你对不对，它只决定你有没有机会等到自己对。",
  lessonEn:
    "The lesson: diversification is an assumption, not a property. Your sixteen trades sit in different countries, assets and maturities, and the model says they are uncorrelated — right up to the morning everybody wants cash, at which point they become one trade. The question worth asking is not what your probability of being right is, but whether you could sell the position in the worst week of the decade. Leverage does not change whether you are right. It decides whether you get to be there when you turn out to be.",
  lexicon: {
    ...LEVERAGE_LEXICON,
    lineZh: "基金的偿付能力",
    lineEn: "the fund's solvency",
    gaugeZh: "追缴压力",
    gaugeEn: "Margin pressure",
    breakZh: "追缴无法完成。主经纪商开始处置抵押品，仓位在最差的价格上被平掉。",
    breakEn: "The calls cannot be met. The prime brokers start selling collateral, and the positions come off at the worst price on the screen.",
    rateZh: "主经纪商保证金要求",
    rateEn: "Prime broker margin",
    potZh: "可动用资本",
    potEn: "Available capital",
    marketZh: "市场流动性",
    marketEn: "Market liquidity",
    spendZh: "注入新资本",
    spendEn: "Put capital in",
    buyZh: "整体接下账簿",
    buyEn: "Take the book over",
  },
  seatLabel: {
    governor: { zh: "中央银行主席", en: "Reserve bank president" },
    fund: { zh: "基金合伙人", en: "Fund partner" },
    trader: { zh: "主经纪商风控", en: "Prime broker risk" },
    retail: { zh: "基金投资人", en: "Fund investor" },
  },
  pegRate: 1,
  band: 0.04,
  reserves: 40_000,
  committedForward: 0,
  startRate: 0.05,
  maxRate: 0.4,
  allowEquityDefence: true,
  // The consortium's money is real, targeted and announced. It buys far more
  // than a central bank leaning on a market from the outside.
  reserveEfficiency: 0.95,
  rateDefenceCap: 0.5,
  // Tightening margin protects the lenders and forces the fire sale. Both at
  // once, which is why nobody could agree on what to do until the 23rd.
  rateDragK: 0.3,
  days: 8,
  historicalOutcome: "broke",
  autoDefence: { spend: 0.1, nudgeOnDay: 3, nudgeTo: 0.2, hikeOnDay: 6, buyFrom: 7, buy: 0.2 },
  phases: [
    {
      day: 1,
      titleZh: "违约",
      titleEn: "The default",
      bodyZh: "一个大国对自己发行的本币债务违约。所有人在同一个早上决定只要最安全的资产。",
      bodyEn: "A large country defaults on debt denominated in its own currency. On the same morning, everybody decides they want only the safest thing on the board.",
      pressure: 0.22,
      equityShock: 0.06,
    },
    {
      day: 2,
      titleZh: "利差往反方向走",
      titleEn: "The spreads go the wrong way",
      bodyZh: "该收敛的没有收敛。十六笔本该互不相关的交易，今天同时亏钱——相关性变成了 1。",
      bodyEn: "What should converge does not. Sixteen supposedly unrelated trades lose money on the same day. The correlations have gone to one.",
      pressure: 0.3,
      equityShock: 0.08,
    },
    {
      day: 3,
      titleZh: "有人知道你持有什么",
      titleEn: "Somebody knows what you hold",
      bodyZh: "你的主经纪商同时也是你的交易对手。今天有几张台子在按你的仓位反向做。",
      bodyEn: "Your prime brokers are also your counterparties. Today a few desks are trading against exactly the positions they clear for you.",
      pressure: 0.26,
      equityShock: 0.05,
      minDetail: 1,
    },
    {
      day: 4,
      titleZh: "一天亏掉一成",
      titleEn: "A tenth in a day",
      bodyZh: "单日亏损创纪录。合伙人在会议室里看着同一张表，没有人说话。",
      bodyEn: "A record single-day loss. The partners are looking at the same sheet in the same room and nobody is saying anything.",
      pressure: 0.34,
      equityShock: 0.1,
    },
    {
      day: 5,
      titleZh: "自行募资失败",
      titleEn: "The capital raise fails",
      bodyZh: "打了三十通电话。每一通的回答都是：让我们再看看。「再看看」的意思是不。",
      bodyEn: "Thirty calls. Every one of them ends with 'let us take another look'. Another look means no.",
      pressure: 0.24,
      minDetail: 1,
    },
    {
      day: 6,
      titleZh: "保证金要求提高",
      titleEn: "Margins go up",
      bodyZh: "主经纪商同时上调保证金。他们是对的——但所有人同时对，就是挤兑。",
      bodyEn: "The prime brokers raise margin at the same time. Each of them is right, and everybody being right at once is a run.",
      pressure: 0.36,
      equityShock: 0.12,
    },
    {
      day: 7,
      titleZh: "那个会议",
      titleEn: "The meeting",
      bodyZh: "十四家机构被叫到同一间会议室。没有公共资金，只有一个问题：你们各出多少。",
      bodyEn: "Fourteen institutions in one room. No public money is on the table, only one question: how much does each of you put in.",
      pressure: 0.2,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "ltcm-c1",
      day: 2,
      direction: "in",
      fromZh: "风险部",
      fromEn: "Risk",
      roleZh: "首席风险官",
      roleEn: "Chief risk officer",
      lines: [
        { zh: "模型说今天这种日子，一万年才该出现一次。", en: "The model says a day like today should happen once in ten thousand years." },
        { zh: "上周已经出现过两次了。", en: "It has now happened twice in the last week." },
      ],
      options: [
        {
          id: "cut",
          zh: "那就是模型错了。今天开始减仓，从最不流动的开始。",
          en: "Then the model is wrong. We start cutting today, beginning with the least liquid.",
          effect: { pressure: -0.16, bookMul: 0.96, credibility: 0.12 },
          replyZh: "会很疼。但我同意。",
          replyEn: "It will hurt. I agree with it.",
          tone: "good",
        },
        {
          id: "double",
          zh: "价差反而更好了。加仓。",
          en: "The spread is better than it was. We add.",
          effect: { pressure: 0.14, bookMul: 1.03 },
          replyZh: "……如果它们收敛，我们会赚很多。如果不收敛，我们就没了。",
          replyEn: "…If they converge we make a great deal. If they do not, we are gone.",
          tone: "bad",
        },
        {
          id: "hold",
          zh: "什么都不做。这种时候动手就是把亏损坐实。",
          en: "Do nothing. Moving now only realises the loss.",
          effect: { pressure: 0.05 },
          replyZh: "明白。我会每两小时更新一次。",
          replyEn: "Understood. I will update every two hours.",
          tone: "info",
        },
      ],
    },
    {
      id: "ltcm-c2",
      day: 3,
      direction: "in",
      fromZh: "一家主经纪商",
      fromEn: "One of the prime brokers",
      roleZh: "信用风险主管",
      roleEn: "Head of credit risk",
      lines: [
        { zh: "我们需要重新估值你们的抵押品。按我们的价格，不是按你们的模型价。", en: "We need to re-mark your collateral. At our price, not at your model price." },
      ],
      options: [
        {
          id: "negotiate",
          zh: "可以。但今天全市场都没有成交价，你们的价格也是估的。",
          en: "Fine. Though there are no prints in this market today either — your price is a mark too.",
          effect: { pressure: -0.06, credibility: 0.08 },
          replyZh: "这话公平。我们折中。",
          replyEn: "That is fair. We will split it.",
          tone: "good",
        },
        {
          id: "refuse",
          zh: "不接受。合同上写的是双方同意的估值方法。",
          en: "No. The agreement specifies a mutually agreed valuation method.",
          effect: { pressure: 0.12, credibility: -0.05 },
          replyZh: "那我们就走合同流程。流程走到第三天，你已经没时间了。",
          replyEn: "Then we go through the contractual process. By day three of that process you will have run out of time.",
          tone: "bad",
        },
        {
          id: "show",
          zh: "我把整本账给你看。你自己判断。",
          en: "I will show you the entire book. Judge it yourself.",
          effect: { pressure: -0.1, credibility: -0.12 },
          replyZh: "……我得说，你们的账比传言大得多。这件事我必须上报。",
          replyEn: "…I have to say, this is far larger than the rumour. I am obliged to escalate it.",
          tone: "info",
        },
      ],
    },
    {
      id: "ltcm-c3",
      day: 5,
      direction: "out",
      fromZh: "一位大投资者",
      fromEn: "A large investor",
      roleZh: "潜在出资方",
      roleEn: "Possible source of capital",
      minDetail: 1,
      lines: [
        { zh: "我可以出钱。条件是：我出的价格，按我看到的账面折一半。", en: "I can put money in. My price is half of the book as I read it." },
        { zh: "另外，合伙人全部离场。", en: "And the partners all leave." },
      ],
      options: [
        {
          id: "accept",
          zh: "接受。活下去比面子重要。",
          en: "Accept. Surviving matters more than dignity.",
          effect: { pressure: -0.3, reserves: 12000, bookMul: 0.72 },
          replyZh: "那我们今晚签。你会恨我，但你的基金还在。",
          replyEn: "We sign tonight. You will resent me, and your fund will exist.",
          tone: "info",
        },
        {
          id: "refuse",
          zh: "拒绝。这个价格是抢。",
          en: "Refuse. That price is a robbery.",
          effect: { pressure: 0.1, credibility: 0.05 },
          replyZh: "也许是。不过下一个报价会更低。",
          replyEn: "Perhaps. The next bid will be lower.",
          tone: "info",
        },
      ],
    },
    {
      id: "ltcm-c4",
      day: 6,
      direction: "in",
      fromZh: "中央银行",
      fromEn: "The reserve bank",
      roleZh: "市场部主管",
      roleEn: "Head of markets",
      minDetail: 1,
      lines: [
        { zh: "我们想知道一件事，而且要真话：如果你们明天被强平，市场上还有多少人跟着一起完？", en: "We want to know one thing, and we want it straight. If you are liquidated tomorrow, how many others go with you?" },
      ],
      options: [
        {
          id: "truth",
          zh: "我会把交易对手名单给你。你看了不会睡得着。",
          en: "I will send you the counterparty list. You will not sleep after reading it.",
          effect: { pressure: -0.14, credibility: 0.18 },
          replyZh: "谢谢。我今晚就开始打电话。",
          replyEn: "Thank you. I start making calls tonight.",
          tone: "good",
        },
        {
          id: "minimise",
          zh: "不多。我们自己能处理。",
          en: "Not many. We can handle this ourselves.",
          effect: { pressure: 0.12, credibility: -0.2 },
          replyZh: "但愿如此。那我们就先不介入。",
          replyEn: "Let us hope so. We will stay out of it, then.",
          tone: "bad",
        },
      ],
    },
    {
      id: "ltcm-c5",
      day: 7,
      direction: "in",
      fromZh: "十四家机构 · 会议室",
      fromEn: "Fourteen institutions — the conference room",
      roleZh: "主持人",
      roleEn: "In the chair",
      minDetail: 2,
      lines: [
        { zh: "在座各位都是这家基金的交易对手。它倒了，你们每一家都要在自己的账上认损失。", en: "Everyone in this room is a counterparty to this fund. If it goes, each of you books the loss on your own account." },
        { zh: "没有公共资金。今天要谈的只有一件事：各出多少。", en: "There is no public money. The only question today is how much each of you puts in." },
      ],
      options: [
        {
          id: "split",
          zh: "按敞口分摊。谁的敞口大，谁出得多。",
          en: "Pro rata to exposure. The largest exposure puts up the most.",
          effect: { pressure: -0.35, reserves: 16000, credibility: 0.12 },
          replyZh: "有一家拒绝参加。剩下的签了。",
          replyEn: "One house refuses. The rest sign.",
          tone: "good",
        },
        {
          id: "equal",
          zh: "平摊。今天不谈谁更该负责。",
          en: "Equal shares. Today is not the day to argue about who deserves it.",
          effect: { pressure: -0.28, reserves: 13000, credibility: 0.05 },
          replyZh: "敞口最小的那几家会不高兴，但他们会签。",
          replyEn: "The smallest exposures will grumble, and they will sign.",
          tone: "good",
        },
        {
          id: "public",
          zh: "由央行直接出钱。这是系统性风险。",
          en: "The central bank puts the money up. This is systemic.",
          effect: { pressure: -0.2, reserves: 9000, credibility: -0.25 },
          replyZh: "那这件事十年后会被反复引用——作为先例。",
          replyEn: "Then this gets cited for the next decade. As a precedent.",
          tone: "info",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.62,
      titleZh: "你的钱在别人的模型里",
      titleEn: "Your money is inside somebody's model",
      howZh: "你是这只基金的投资人。你看不到仓位，只看得到月报。这一关要判断的是：一个连续三年赚四成、而且去年主动退还资本的策略，凭什么还能赚四成。",
      howEn: "You are an investor in this fund. You cannot see the positions, only the monthly letter. What you have to judge is why a strategy that returned forty per cent for three years — and handed capital back last winter — should still return forty per cent.",
      winZh: "最后一天净值还剩 62% 以上。",
      winEn: "End with 62% of your net worth or more.",
      trapZh: "「退还资本」听起来是纪律。它也可能意味着：好机会不够了，而剩下的仓位要用更高的杠杆去撑同样的回报。",
      trapEn: "Returning capital sounds like discipline. It can also mean the good trades ran out, and the same return now has to come from more leverage on what is left.",
    }),
    trader: traderObjective({
      target: 0.16,
      titleZh: "你既是它的经纪商，也是它的对手",
      titleEn: "You clear for it and you trade against it",
      howZh: "你在主经纪商的风控台上。你知道这家基金持有什么，也知道它必须卖什么。这一关的问题不是能不能赚，是你打算怎么用这个信息。",
      howEn: "You sit on the prime broker's risk desk. You know what this fund holds and what it will have to sell. The question is not whether you can make money — it is what you intend to do with that knowledge.",
      trapZh: "按它的仓位反向做，短期最赚。但它一旦被强平，你自己的抵押品也在那堆里。",
      trapEn: "Trading against its book pays best in the short run. If it is liquidated, your own collateral is in the same pile.",
    }),
    fund: {
      side: "defend",
      kind: "survive",
      target: 0.65,
      titleZh: "活到收敛的那一天",
      titleEn: "Be there when it converges",
      howZh: "你的判断很可能是对的——这些价差最后确实收敛了。问题是「最后」在什么时候，以及你的保证金能不能撑到那时候。你能做的只有一件事：在被别人强制减仓之前，自己先减。每减一笔都是在承认自己错了，而这一关里，承认得越早活得越久。",
      howEn: "Your analysis is probably right: these spreads did converge in the end. The question is when 'the end' is, and whether your margin lasts that long. You can do exactly one thing — cut before somebody cuts for you. Every cut is an admission that you were wrong, and in this scenario the earlier you admit it the longer you live.",
      winZh: "最后一天基金净值还剩 65% 以上，而且没有被强制平仓。坐着不动是不够的——账面会自己往下走。",
      winEn: "Finish with at least 65% of the fund's value and without having been liquidated. Sitting still is not enough: the book goes down on its own.",
      trapZh: "「价差更宽了，所以现在的机会更好」——这句话在数学上成立，在现金流上不成立。你需要活着的那笔钱，不在模型里。",
      trapEn: "'The spread is wider, so the opportunity is better.' True in the mathematics and false in the cash flow. The money you need to still be here is not in the model.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.72,
      equityFloor: 52,
      titleZh: "不花公共的钱，把它接住",
      titleEn: "Catch it without public money",
      howZh: "你手上没有一张干净的牌。提高保证金要求能保护出借人，但会立刻逼出强平；注入资本能买回压力，可这笔钱不是你的，你只能去借别人的；直接接下账簿最有效，也最像在救一家私人基金。你要做的是把十四家不情愿的机构摆到同一间会议室里，并且在它被强平之前办完。",
      howEn: "You do not hold a single clean card. Raising margin protects the lenders and forces the fire sale. Putting capital in buys the pressure back, and the capital is not yours — you have to go and ask for it. Taking the book over works best and looks most like bailing out a private fund. The job is to get fourteen reluctant institutions into one room, and to do it before the liquidation.",
      winZh: "撑满全部时段、基金没有被强制平仓，市场流动性指数收在 52 以上，并且追缴压力压回 0.72 以下。",
      winEn: "Last every session without the fund being liquidated, with the market liquidity index above 52 at the close and margin pressure back under 0.72.",
      trapZh: "等着看是最贵的选项。你多等一天，会议室里的人就更少一个愿意出钱——因为他们也在同一天亏钱。",
      trapEn: "Waiting to see is the expensive option. Every day you wait, one more institution in that room stops being willing to put money up, because they are losing money on the same days you are.",
    },
  },
};

export const LEHMAN: Scenario = {
  id: "lehman",
  kind: "leverage",
  nameZh: "第三家投行的周末",
  nameEn: "The Third Bank's Weekend",
  year: "2008",
  grade: 9,
  order: 13,
  major: true,
  briefZh:
    "整个体系每天早上要把几万亿的短期借款重新借一遍。抵押品是结构化证券，评级是 AAA，折扣率多年来是零点几个百分点——因为没有人认为需要争论它值多少钱。现在有人开始争论了。三月份一家投行被安排卖掉，九月初两家住房贷款机构被接管，现在第三家在你桌上：它有六千多亿资产、一百多万笔衍生品合约，和一个周一早上的问题。你有五张牌，没有一张是干净的，而且每一张都会成为下一次危机的先例。",
  briefEn:
    "Every morning this system rolls trillions of dollars of short-term borrowing. The collateral is structured paper, the ratings are AAA, and the haircuts have been a fraction of a per cent for years — because nobody thought it was worth arguing about what it was worth. People have started arguing. In March an investment bank was arranged into a sale; in early September two housing agencies were taken into conservatorship; now the third one is on your desk, with six hundred billion of assets, more than a million derivative contracts, and a problem that arrives on Monday morning. You hold five cards. None of them is clean, and every one of them becomes the precedent for the next crisis.",
  historyZh:
    "史实：2008 年 3 月，贝尔斯登在美联储提供约 290 亿美元融资支持下被摩根大通收购。9 月 7 日，房利美与房地美被接管。9 月 15 日，雷曼兄弟申请破产保护，资产规模约 6,390 亿美元，为美国史上最大破产案。9 月 16 日，美联储向 AIG 提供 850 亿美元信贷额度（后累计扩大至约 1,820 亿美元）；同日，货币市场基金 Reserve Primary Fund 因持有雷曼商业票据而「跌破一美元」（净值 0.97 美元），触发货币基金赎回潮，财政部于 9 月 19 日宣布临时担保计划。9 月 29 日众议院首次否决救助法案，道指当日下跌 777.68 点；10 月 3 日 7,000 亿美元的问题资产救助计划（TARP）签署生效。10 月 8 日多国央行协同降息，10 月 13 日美国向九家大型银行注资 1,250 亿美元。道指自 2007 年 10 月的 14,164 点跌至 2009 年 3 月 9 日的 6,547 点，跌幅约 54%。",
  historyEn:
    "History: in March 2008 Bear Stearns was bought by JPMorgan with roughly US$29bn of Federal Reserve financing behind it. On 7 September Fannie Mae and Freddie Mac were placed into conservatorship. On 15 September Lehman Brothers filed for bankruptcy protection with about US$639bn of assets, the largest filing in US history. On 16 September the Federal Reserve extended an US$85bn credit facility to AIG, ultimately expanded to roughly US$182bn; the same day the Reserve Primary Fund 'broke the buck' at US$0.97 on its Lehman commercial paper, triggering a run on money market funds, and the Treasury announced a temporary guarantee programme on 19 September. On 29 September the House first rejected the rescue bill and the Dow fell 777.68 points; the US$700bn Troubled Asset Relief Program was signed on 3 October. Coordinated central bank rate cuts followed on 8 October, and on 13 October the US injected US$125bn into nine large banks. The Dow fell from 14,164 in October 2007 to 6,547 on 9 March 2009, about 54%.",
  historyDeepZh: [
    "这场危机的核心机制是「回购挤兑」：短期融资并未被取消，而是抵押品的折扣率被大幅提高——同样一份证券，昨天能借到 99 元，今天只能借到 80 元，差额要当天补上。",
    "衡量银行间恐慌的 TED 利差在 2008 年 10 月升至约 4.6 个百分点，为有记录以来最高。",
    "雷曼破产当周，货币市场基金一周内净流出数千亿美元；财政部的临时担保把这场挤兑止住，而它保的是一个此前被认为不需要保的市场。",
    "9 月 19 日美国证监会对数百只金融股实施临时卖空禁令。事后多项研究认为该禁令并未阻止下跌，却显著恶化了这些股票的流动性与买卖价差。",
    "TARP 最初的设计是购买问题资产，实际执行时改为直接注资银行——因为给资产定价需要时间，而注资可以在一个周末完成。",
    "欧洲同步发生：9 月末至 10 月初，数家欧洲银行被国有化或获得注资，爱尔兰于 9 月 30 日宣布为其银行体系提供全面担保。",
  ],
  historyDeepEn: [
    "The central mechanism was a run on repo: the short-term funding was not withdrawn so much as repriced, as haircuts on collateral jumped. The same security that borrowed 99 yesterday borrowed 80 today, and the difference was due that afternoon.",
    "The TED spread, the standard gauge of interbank fear, reached roughly 4.6 percentage points in October 2008 — the highest on record.",
    "In the week of the Lehman filing, money market funds saw hundreds of billions of dollars of outflows. The Treasury's temporary guarantee stopped that run, and what it guaranteed was a market everybody had previously agreed needed no guarantee.",
    "On 19 September the SEC imposed a temporary ban on short selling in hundreds of financial stocks. Later studies generally found that the ban did not stop the decline while it markedly worsened liquidity and spreads in exactly those names.",
    "TARP was designed to buy troubled assets and was executed as direct capital injections instead — pricing the assets takes time, and a capital injection can be done over a weekend.",
    "The same thing was happening in Europe: several banks were nationalised or recapitalised between late September and early October, and Ireland guaranteed its entire banking system on 30 September.",
  ],
  lessonZh:
    "这一战教的是：「短期融资的抵押品，是整个体系的地基，而没有人给地基定过价」。回购挤兑不像银行挤兑那样有队伍和照片，它只是折扣率从 0.5% 变成 20%——同一天，同一份证券，同一个借款人。到那个时候你已经没有「救不救某一家」的选择题了，你只有「担保哪一类负债」这一道题。而你答的每一句话，都会变成下一次危机里所有人的预期。",
  lessonEn:
    "The lesson: the collateral behind short-term funding is the foundation of the whole system, and nobody ever priced the foundation. A run on repo has no queue and no photograph — it is a haircut going from half a per cent to twenty, on the same day, the same security, the same borrower. By the time you see it, you no longer get to choose which firm to save. You only get to choose which class of liability to guarantee. And every sentence you say about it becomes what everybody expects the next time.",
  lexicon: {
    ...LEVERAGE_LEXICON,
    lineZh: "回购市场",
    lineEn: "the repo market",
    gaugeZh: "抵押品折扣",
    gaugeEn: "Haircut",
    breakZh: "回购市场关闭。没有折扣率能让这批抵押品借到钱——不是贵，是没有对手方。",
    breakEn: "The repo market shuts. There is no haircut at which this collateral funds — not expensive, no counterparty.",
    rateZh: "强制资本充足要求",
    rateEn: "Capital requirement",
    potZh: "公共资金",
    potEn: "Public funds",
    spendZh: "向银行注资",
    spendEn: "Inject capital",
    buyZh: "直接接下问题资产",
    buyEn: "Take the assets onto the public books",
  },
  seatLabel: {
    governor: { zh: "财政部长 / 央行主席", en: "Treasury and the central bank" },
    fund: { zh: "做空金融股的基金", en: "The fund short the banks" },
    trader: { zh: "回购交易台", en: "Repo desk" },
    retail: { zh: "货币基金持有人", en: "Money market fund holder" },
  },
  pegRate: 1,
  band: 0.03,
  reserves: 150_000,
  committedForward: 0,
  startRate: 0.04,
  maxRate: 0.14,
  allowEquityDefence: true,
  allowPledge: true,
  allowHalt: true,
  reserveEfficiency: 0.85,
  rateDefenceCap: 0.45,
  rateDragK: 0.26,
  days: 14,
  historicalOutcome: "broke",
  autoDefence: { spend: 0.08, nudgeOnDay: 4, nudgeTo: 0.07, hikeOnDay: 10, buyFrom: 11, buy: 0.12, pledgeOn: 9 },
  phases: [
    {
      day: 1,
      titleZh: "折扣率开始动",
      titleEn: "The haircuts start moving",
      bodyZh: "同一份证券，昨天借到 99，今天只借得到 95。四个点听起来不多，乘上几万亿就不是了。",
      bodyEn: "The same security borrowed 99 yesterday and borrows 95 today. Four points does not sound like much until you multiply it by a few trillion.",
      pressure: 0.16,
    },
    {
      day: 2,
      titleZh: "两家住房机构被接管",
      titleEn: "The housing agencies go into conservatorship",
      bodyZh: "政府接管了两家最大的住房贷款机构。市场松了半天，然后开始数下一个。",
      bodyEn: "The government takes the two largest housing lenders. The market is relieved for half a day and then starts counting who is next.",
      pressure: 0.18,
      equityShock: 0.04,
    },
    {
      day: 4,
      titleZh: "第三家投行",
      titleEn: "The third investment bank",
      bodyZh: "它的回购账簿一夜之间少了三分之一。买家还在谈，但没有人愿意在没有政府兜底的情况下签字。",
      bodyEn: "A third of its repo book disappears overnight. A buyer is still talking, and nobody will sign without a government backstop.",
      pressure: 0.34,
      equityShock: 0.08,
    },
    {
      day: 5,
      titleZh: "周一早上",
      titleEn: "Monday morning",
      bodyZh: "它没有被救。一百多万笔衍生品合约同时进入清算程序，全世界的交易台都在算同一个问题：我的对手方是谁的对手方。",
      bodyEn: "It was not saved. More than a million derivative contracts go into an insolvency process at once, and every desk on earth is working out the same thing: who is my counterparty's counterparty.",
      pressure: 0.44,
      equityShock: 0.14,
    },
    {
      day: 6,
      titleZh: "保险公司",
      titleEn: "The insurer",
      bodyZh: "一家保险公司卖出了几千亿的信用保护，现在被要求补抵押品。它补不出来，而买了这些保护的是所有人。",
      bodyEn: "An insurer wrote hundreds of billions of credit protection and is being asked for collateral. It cannot post, and the people who bought that protection are everybody.",
      pressure: 0.42,
      equityShock: 0.1,
    },
    {
      day: 7,
      titleZh: "货币基金跌破一美元",
      titleEn: "A money fund breaks the buck",
      bodyZh: "一只货币市场基金的净值报 0.97。这类基金被所有人当成现金——现在现金有了价格波动。赎回在一小时内排到了门外。",
      bodyEn: "A money market fund marks at 0.97. These funds are what everybody calls cash, and cash has just developed a price. The redemptions are out of the door within the hour.",
      pressure: 0.4,
      equityShock: 0.12,
    },
    {
      day: 9,
      titleZh: "法案被否决",
      titleEn: "The bill fails",
      bodyZh: "救助法案在议会被否决。指数当天跌掉两年来最大的一根。政治和市场用的是两个时钟。",
      bodyEn: "The rescue bill fails in the legislature. The index prints its worst day in two years. Politics and markets run on two different clocks.",
      pressure: 0.4,
      equityShock: 0.13,
      minDetail: 1,
    },
    {
      day: 11,
      titleZh: "银行间利差创纪录",
      titleEn: "Interbank spreads hit a record",
      bodyZh: "银行不肯借给银行。不是因为算出了谁会倒，是因为算不出来。",
      bodyEn: "Banks will not lend to banks. Not because they have worked out who fails, but because they cannot work it out.",
      pressure: 0.36,
      equityShock: 0.09,
      minDetail: 1,
    },
    {
      day: 12,
      titleZh: "海那边也开盘了",
      titleEn: "The other side of the water opens too",
      bodyZh: "同一周，海对面几家银行被国有化，一个邻国宣布为全部银行负债提供担保。担保是会传染的——一个国家做了，邻国就必须做。",
      bodyEn: "In the same week several banks across the water are nationalised and a neighbouring country guarantees every liability of its banking system. Guarantees are contagious: once one country does it, its neighbours have to.",
      pressure: 0.3,
      equityShock: 0.07,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "lb-c1",
      day: 3,
      direction: "in",
      fromZh: "第三家投行",
      fromEn: "The third investment bank",
      roleZh: "首席执行官",
      roleEn: "Chief executive",
      lines: [
        { zh: "部长，我这里有一个买家，但他要一笔政府担保才肯签。", en: "Secretary — I have a buyer. He will not sign without a government backstop." },
        { zh: "三月份那一家你们给了。", en: "You gave one in March." },
      ],
      options: [
        {
          id: "backstop",
          zh: "给。这个周末必须有人接。",
          en: "Give it. Somebody has to take this over by Monday.",
          effect: { pressure: -0.24, reserves: -26000, credibility: -0.15 },
          replyZh: "谢谢。……你知道，明天早上所有人都会来要同样的东西。",
          replyEn: "Thank you. …You realise everybody asks for the same thing tomorrow morning.",
          tone: "info",
        },
        {
          id: "no",
          zh: "不给。这次没有公共资金。",
          en: "No. There is no public money in this one.",
          effect: { pressure: 0.2, equityMul: 0.94, credibility: 0.15 },
          replyZh: "那我周日晚上申请破产。部长，你会在教科书里见到这个决定。",
          replyEn: "Then I file on Sunday night. Secretary — you will meet this decision again in the textbooks.",
          tone: "bad",
        },
        {
          id: "private",
          zh: "你去找同业凑。我把他们叫到一个房间里，但钱是他们的。",
          en: "Go to your peers. I will put them in a room; the money is theirs.",
          effect: { pressure: -0.1, credibility: 0.08 },
          replyZh: "我试过了。他们要看我的账，而我的账现在没人敢看。",
          replyEn: "I have tried. They want to see my book, and right now nobody dares look at my book.",
          tone: "info",
        },
      ],
    },
    {
      id: "lb-c2",
      day: 6,
      direction: "in",
      fromZh: "保险集团",
      fromEn: "The insurance group",
      roleZh: "财务总监",
      roleEn: "Chief financial officer",
      lines: [
        { zh: "我们的评级被下调，对手方要求追加抵押品。金额是我们全部现金的六倍。", en: "We have been downgraded and our counterparties want collateral. The number is six times the cash we hold." },
        { zh: "我们不是银行，所以我们没有贴现窗口。", en: "We are not a bank, so there is no discount window for us." },
      ],
      options: [
        {
          id: "facility",
          zh: "开一条专门的额度给你们，抵押品是整个集团。",
          en: "You get a facility of your own, secured on the whole group.",
          effect: { pressure: -0.26, reserves: -30000, equityMul: 1.04, credibility: -0.1 },
          replyZh: "我们接受所有条件。谢谢。",
          replyEn: "We accept every condition. Thank you.",
          tone: "good",
        },
        {
          id: "sell",
          zh: "先卖掉能卖的子公司，缺口自己补。",
          en: "Sell what you can sell and cover the gap yourselves.",
          effect: { pressure: 0.24, equityMul: 0.92 },
          replyZh: "卖一家子公司要三个月。我们缺的是明天下午三点的钱。",
          replyEn: "Selling a subsidiary takes three months. What we are short of is money at three o'clock tomorrow.",
          tone: "bad",
        },
      ],
    },
    {
      id: "lb-c3",
      day: 7,
      direction: "in",
      fromZh: "货币市场基金公会",
      fromEn: "The money market fund association",
      roleZh: "会长",
      roleEn: "President",
      lines: [
        { zh: "一只基金跌破了一美元。今天上午全行业净流出创纪录。", en: "One fund has broken the buck. Industry outflows this morning are a record." },
        { zh: "部长，这是全国人民放现金的地方。", en: "Secretary — this is where the country keeps its cash." },
      ],
      options: [
        {
          id: "guarantee",
          zh: "财政部临时担保全部货币基金。今天就宣布。",
          en: "The Treasury guarantees every money fund, temporarily. Announced today.",
          effect: { pressure: -0.4, equityMul: 1.06, credibility: -0.12, reserves: -8000 },
          replyZh: "赎回会在半天内停下来。……你也知道，以后所有人都会以为这个担保永远在。",
          replyEn: "The redemptions stop within half a day. …And from now on everybody assumes that guarantee is permanent.",
          tone: "good",
        },
        {
          id: "partial",
          zh: "只担保现有余额，新钱不保。",
          en: "Existing balances only. New money is not covered.",
          effect: { pressure: -0.26, equityMul: 1.03, credibility: 0.05, reserves: -5000 },
          replyZh: "这样银行不会骂得太厉害。够用。",
          replyEn: "That keeps the banks from screaming. It will do.",
          tone: "good",
        },
        {
          id: "none",
          zh: "不担保。货币基金不是存款。",
          en: "No guarantee. A money fund is not a deposit.",
          effect: { pressure: 0.3, equityMul: 0.92 },
          replyZh: "法律上您是对的。星期三之后，法律上对不对就不重要了。",
          replyEn: "Legally you are correct. After Wednesday, legally correct will not be the relevant category.",
          tone: "bad",
        },
      ],
    },
    {
      id: "lb-c4",
      day: 8,
      direction: "in",
      fromZh: "证券监管机构",
      fromEn: "The securities regulator",
      roleZh: "主席",
      roleEn: "Chair",
      minDetail: 1,
      lines: [
        { zh: "我们可以对金融股实施临时卖空禁令。政治上非常受欢迎。", en: "We can impose a temporary short-selling ban on financials. Politically it is extremely popular." },
        { zh: "市场效果……有争议。", en: "The market effect is… contested." },
      ],
      options: [
        {
          id: "ban",
          zh: "禁。至少先把恐慌的节奏打断。",
          en: "Ban it. At least break the rhythm of the panic.",
          effect: { pressure: -0.14, equityMul: 0.97, credibility: -0.16 },
          replyZh: "今天生效。价差会变宽，流动性会变差，但头条会好看。",
          replyEn: "Effective today. Spreads widen, liquidity gets worse, and the headline looks better.",
          tone: "info",
        },
        {
          id: "refuse",
          zh: "不禁。卖空不是这次的原因，禁了只会让做市更难。",
          en: "No ban. Short selling is not what caused this, and a ban only makes markets harder to make.",
          effect: { pressure: 0.06, credibility: 0.14, equityMul: 1.01 },
          replyZh: "我同意，但我要提醒您：明天的听证会上这句话会被念出来。",
          replyEn: "I agree. I will warn you that sentence gets read back at tomorrow's hearing.",
          tone: "good",
        },
      ],
    },
    {
      id: "lb-c5",
      day: 10,
      direction: "out",
      fromZh: "议会党团",
      fromEn: "The legislative caucus",
      roleZh: "党鞭",
      roleEn: "The whip",
      minDetail: 1,
      lines: [
        { zh: "法案昨天被否了。我的人回选区听到的全是一句话：凭什么用纳税人的钱救金融街。", en: "The bill failed yesterday. What my members hear back home is one sentence: why is taxpayer money going to the financial district." },
        { zh: "你得给我一个能在选区说出口的版本。", en: "Give me a version I can say in a town hall." },
      ],
      options: [
        {
          id: "equity",
          zh: "改成注资换股份。钱进去，纳税人拿股权，以后卖掉。",
          en: "Make it capital for equity. The money goes in, the taxpayer takes shares, and we sell them later.",
          effect: { pressure: -0.3, reserves: 22000, credibility: 0.16 },
          replyZh: "这个能过。而且事后如果赚了钱，我们都能站直。",
          replyEn: "That passes. And if it turns a profit later, all of us get to stand up straight.",
          tone: "good",
        },
        {
          id: "buyassets",
          zh: "坚持原方案：买下问题资产。",
          en: "Stick to the original: buy the troubled assets.",
          effect: { pressure: -0.12, reserves: 14000, credibility: -0.05 },
          replyZh: "那我们还得先给这些资产定价。定价要几个月，你有几个月吗？",
          replyEn: "Then we have to price them first. Pricing takes months. Do you have months?",
          tone: "info",
        },
        {
          id: "threaten",
          zh: "告诉他们：不通过，下周他们选区的银行就取不出钱。",
          en: "Tell them that if it fails, next week their constituents cannot get money out of their own bank.",
          effect: { pressure: -0.2, reserves: 18000, credibility: -0.2 },
          replyZh: "会过。但这句话会被录下来，而且会被放很多年。",
          replyEn: "It will pass. That sentence gets recorded, and it gets played for years.",
          tone: "info",
        },
      ],
    },
    {
      id: "lb-c6",
      day: 12,
      direction: "out",
      fromZh: "九家大型银行",
      fromEn: "The nine largest banks",
      roleZh: "同一间会议室",
      roleEn: "All in one room",
      minDetail: 2,
      lines: [
        { zh: "部长，我们当中有几家不需要这笔钱。接受了等于自认有问题。", en: "Secretary, several of us do not need this money. Taking it is an admission that we have a problem." },
      ],
      options: [
        {
          id: "allnine",
          zh: "九家全部接受，同一天，同样的条件。没有人是被挑出来的。",
          en: "All nine take it, on the same day, on the same terms. Nobody has been singled out.",
          effect: { pressure: -0.34, reserves: -34000, equityMul: 1.07, credibility: 0.12 },
          replyZh: "……那就都签。至少没有人会被指着说是他。",
          replyEn: "…Then we all sign. At least nobody gets pointed at.",
          tone: "good",
        },
        {
          id: "voluntary",
          zh: "自愿。需要的来拿。",
          en: "Voluntary. Whoever needs it can come and take it.",
          effect: { pressure: 0.22, equityMul: 0.94 },
          replyZh: "那没有人会来拿。第一个来拿的人，第二天就会被挤兑。",
          replyEn: "Then nobody comes. Whoever comes first gets run on the next morning.",
          tone: "bad",
        },
      ],
    },
    {
      id: "lb-c7",
      day: 13,
      direction: "in",
      fromZh: "一位储户",
      fromEn: "A depositor",
      roleZh: "打到公开热线",
      roleEn: "Through the public line",
      minDetail: 3,
      seats: ["governor", "retail"],
      lines: [
        { zh: "我不懂什么叫回购。我只想知道我明天能不能取到我的钱。", en: "I do not know what repo means. I want to know whether I can get my money out tomorrow." },
      ],
      options: [
        {
          id: "plain",
          zh: "能。存款有保险，上限我告诉您，超出的部分我们这周会处理。",
          en: "Yes. Deposits are insured — here is the limit, and we are dealing with the part above it this week.",
          effect: { pressure: -0.12, credibility: 0.15 },
          replyZh: "……谢谢。您是第一个直接回答我的人。",
          replyEn: "…Thank you. You are the first person who answered the question.",
          tone: "good",
        },
        {
          id: "jargon",
          zh: "体系整体是稳健的，我们正在采取一切必要措施。",
          en: "The system is fundamentally sound and we are taking all necessary measures.",
          effect: { pressure: 0.1, credibility: -0.12 },
          replyZh: "这句话我在电视上听过四遍了。我明天还是去排队。",
          replyEn: "I have heard that four times on television. I am going to queue tomorrow anyway.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.66,
      titleZh: "你以为你持有的是现金",
      titleEn: "You thought you were holding cash",
      howZh: "你的钱在一只货币市场基金里。所有人——包括你——都把它当成现金。这一关要判断的是：你的「现金」到底是谁的负债，以及那个人靠什么还。",
      howEn: "Your money is in a money market fund. Everybody, including you, calls that cash. What you have to work out is whose liability your 'cash' actually is, and what they are paying it back with.",
      winZh: "最后一天净值还剩 66% 以上。",
      winEn: "End with 66% of your net worth or more.",
      trapZh: "这一关最危险的不是股票，是你根本没当成投资的那一笔。",
      trapEn: "The dangerous position here is not the stock. It is the one you never thought of as a position.",
    }),
    trader: traderObjective({
      target: 0.22,
      titleZh: "回购台",
      titleEn: "The repo desk",
      howZh: "你每天早上要把几百亿的短期融资重新借一遍。这一关你要盯的不是价格，是折扣率——折扣率动了，价格明天才会动。",
      howEn: "You roll tens of billions of short-term funding every morning. What matters here is not the price, it is the haircut. The haircut moves today and the price moves tomorrow.",
      trapZh: "「我们的抵押品是 AAA」——这句话在 2008 年的意思是「还没有人去争论它值多少钱」。",
      trapEn: "'Our collateral is AAA.' In 2008 that sentence meant 'nobody has started arguing about what it is worth yet'.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "做空那个假设",
      titleEn: "Short the assumption",
      howZh: "你做空的不是某一家银行，是「短期融资永远借得到」这个假设。你要做的就是盯着折扣率，并且比所有人都早一周开始怀疑抵押品。",
      howEn: "You are not short a bank. You are short the assumption that short-term funding always rolls. Watch the haircuts, and start doubting the collateral a week before everybody else.",
      winZh: "在最后一天结束前让回购市场关闭。",
      winEn: "Shut the repo market before the last day ends.",
      trapZh: "对面手上有一张你没法建模的牌：全面担保。它不需要通过议会，也不需要花现金，而它一出，你的整套论证当天失效。",
      trapEn: "The other side holds a card you cannot model: a blanket guarantee. It needs no legislature and no cash, and the day it lands your entire thesis stops working.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.82,
      equityFloor: 44,
      titleZh: "五张牌，没有一张干净",
      titleEn: "Five cards, none of them clean",
      howZh: "注资能直接把压力买回来，但每一笔都是先例；提高资本要求让体系明天更安全，代价是今天所有人同时去杠杆；直接接下问题资产最有效，也最难向纳税人解释；一次全面担保可以在半天内止住挤兑，但只有在你还有弹药的时候说才有人信；停市和卖空禁令能打断节奏，代价是信心。顺序比力度重要：先止住取钱的地方，再谈救谁。",
      howEn: "Capital injections buy pressure back directly, and every one of them is a precedent. Raising capital requirements makes the system safer tomorrow at the cost of everybody deleveraging today. Taking the assets on works best and is hardest to explain to a taxpayer. One blanket guarantee can stop a run in half a day — but only while there is still ammunition behind it. A halt or a short-selling ban breaks the rhythm and costs you confidence. Sequence matters more than size: stop the place people are taking money out of, then argue about who gets saved.",
      winZh: "撑满全部时段、回购市场不关闭，收盘时股指在 44 以上，并且折扣压力压回 0.82 以下。",
      winEn: "Last every session with the repo market open, the index above 44 at the close, and haircut pressure back under 0.82.",
      trapZh: "历史上这一关是输的——不是因为没人努力，是因为每一次出手都比上一次更贵，而前面那几次出手，恰好让市场以为下一次也会出手。",
      trapEn: "History lost this one. Not for want of effort: each intervention cost more than the last, and the earlier ones had taught the market to expect the next.",
    },
  },
};
