import type { Scenario } from "../types.ts";
import { MANIA_LEXICON, retailObjective, traderObjective } from "./seats.ts";

/**
 * Two bubbles, a hundred and twenty years apart, that die of opposite things.
 *
 * The Oceanic Company dies of a feedback loop it runs itself: lending buyers
 * the money hollows out its own balance sheet. The railway mania dies of
 * arithmetic nobody needed a loop for — when a hundred companies are issuing
 * at once on ten-per-cent deposits, the market does not need bad news to fall.
 * It needs only more paper than money.
 */

/** The railway vocabulary: same arithmetic, an industry instead of a company. */
const RAILWAY_LEXICON: Scenario["lexicon"] = {
  lineZh: "铁轨股行情",
  lineEn: "the railway market",
  gaugeZh: "发行热度",
  gaugeEn: "Issue froth",
  breakZh: "发行被中止。认购单作废，缴过的首付停在新线永远动不了工的地方。",
  breakEn: "Issues are suspended. Subscription money is recalled and deposits end up in lines that will never carry a train.",
  rateZh: "认购首付比例",
  rateEn: "Deposit fraction",
  potZh: "承销集团金库",
  potEn: "Syndicate treasury",
  spendZh: "回购铁轨股",
  spendEn: "Buy railway stock back",
  buyZh: "为认购垫资",
  buyEn: "Finance the subscriptions",
  marketZh: "集团清偿能力",
  marketEn: "Syndicate solvency",
  shortLineZh: "做空铁轨股",
  shortLineEn: "Short the rails",
  shortEqZh: "清掉手上的认购单",
  shortEqEn: "Sell your subscriptions",
};

export const RAILWAY: Scenario = {
  id: "railway",
  kind: "mania",
  nameZh: "铁轨狂潮",
  nameEn: "The Railway Fever",
  year: "1846",
  grade: 3,
  order: 3,
  major: false,
  briefZh:
    "狮子国通过了一部新法：开办铁路公司不再需要逐家求议会发牌照，注册就行。两年之内，提交议会的铁路方案数以百计，报纸为它们辟出整版整版的表格。买一张认购单只要先付一成，其余分期——而缴款日之前，单子本身就能转手赚钱。你坐在承销集团的主席位上：每一份新方案你都有份，每一份也都押着你的名字。城里所有的钱都在涌向同一样东西，而你是那个往里灌纸的人。",
  briefEn:
    "Leo has passed a new act: a railway company no longer needs a private Act of Parliament — it registers, and it exists. Within two years hundreds of schemes are before the House, and the papers give over whole pages to their tables. A subscription costs a tenth down, the balance by instalments — and until the call dates arrive, the slip itself trades at a profit. You chair the underwriting syndicate: every new scheme carries a slice of you, and your name stands behind every one of them. All the money in the city is running at the same thing, and you are the one feeding it paper.",
  historyZh:
    "史实：1844 年英国《股份公司法》将开办公司从逐家特别立法改为注册制，铁路公司数量随之暴涨。1845 年议会收到约 272 项铁路法案；当年秋天铁路资本的名义承诺额据估算约达 1.32 亿英镑——接近英国年税收的两倍。认购普遍只需 10% 首付，余款分期缴付。1845 年 10 月，英格兰银行两度上调贴现率，流动性收紧；《泰晤士报》同年 10 月 23 日刊出著名社论，提醒公众计算铁路公司将要运的乘客与货物根本填不满这么多线路。1846 年起股价与认购单价格崩落。至 1850 年代初，已获准的线路中约有一半从未建成。以兼并扩张闻名的「铁路大王」乔治·哈德森后来因账目问题身败名裂；狄更斯在《董贝父子》中写下了被铁路改变的城市。",
  historyEn:
    "History: the UK Companies Act of 1844 replaced charter-by-Parliament with registration, and the number of railway companies exploded. In the 1845 session Parliament received roughly 272 railway bills; by that autumn the capital nominally committed to railways has been estimated at about £132m — close to twice the year's tax revenue. Subscriptions commonly took 10% down with the balance by instalments. In October 1845 the Bank of England raised its discount rate twice as liquidity tightened, and on 23 October The Times ran its famous leader inviting readers to count whether the passengers and freight existed to fill so many lines. From 1846 the shares and subscription slips collapsed. By the early 1850s about half the authorized mileage had never been built. George Hudson, the 'Railway King' who grew by consolidation, was later ruined by his accounts; Dickens caught the railway-remade city in Dombey and Son.",
  historyDeepZh: [
    "1845 年的议会会期里，平均每周有十余项新铁路方案提交。报纸上的铁路专版成了最畅销的版面，行情表比股票版还长。",
    "多数认购单在缴款日之前就已转手数次。很多人从头到尾没有打算缴清全款——他们买的不是铁路，是下一家更傻的买家。",
    "流动性收紧后，最先倒下的不是铁路公司，是靠垫付认购款吃饭的放贷人：抵押品是认购单，而认购单正在贬值。",
    "乔治·哈德森通过兼并把多条铁路并成大系统，一度身兼多家铁路公司董事长、受封从男爵；1849 年账目问题曝光后被逐出董事会。",
    "泡沫破灭后修建仍在继续——钱已经缴了大半，修完比停工更便宜。英国的路网密度因此超前于当时的经济水平，这算是这场狂热留给后人的遗产。",
  ],
  historyDeepEn: [
    "Through the 1845 session new schemes arrived at the House at a rate of better than one a day. The railway column became the best-read page in the papers, its tables longer than the stock list.",
    "Most subscription slips changed hands several times before any call was met. Plenty of subscribers never intended to pay in full — what they were buying was not a railway but the next buyer.",
    "When liquidity tightened the first casualties were not the railways but the men lending against subscriptions: the collateral was a slip of paper that was itself falling.",
    "George Hudson assembled whole systems by amalgamation, chaired several companies at once and was made a baronet; in 1849 his accounting caught up with him and he was voted off his boards.",
    "Building continued after the mania burst — the money was mostly paid in, and finishing was cheaper than stopping. Britain ended with a denser network than its economy yet needed, which is the one gift the fever left behind.",
  ],
  lessonZh:
    "这一战教的是：「行情的敌人不一定是坏消息，可以是供给本身」。南海是一家公司把买家喂到撑死；这一次是一百三十家同时往一个盘子里放纸，每一张只要一成首付。当发行量足够大，市场不需要任何利空就会跌——需要钱的人比有钱的人多的那天，就是顶。还有那把双刃剑：首付越低行情越热，但缴款日是一定会来的，而到那天，杠杆会把行情的每一分下跌放大成违约。看见「人人都能用一成钱买一成货」的市场，先问一句：缴款日是哪天。",
  lessonEn:
    "The lesson: a market does not need bad news to fall — supply alone will do it. The Oceanic Company was one house feeding its own buyers; this is a hundred and thirty houses putting paper into the same bowl at ten per cent down. Past some volume of issue the market falls on arithmetic: the day there are more people who need the money than people who have it is the top. And the lever cuts both ways — a smaller deposit makes a hotter market, but the call dates arrive regardless, and by then every point the market falls becomes a default. In any market where everyone can buy the goods with a tenth of the price, find out when the calls are due.",
  lexicon: RAILWAY_LEXICON,
  seatLabel: {
    governor: { zh: "承销集团主席", en: "Underwriting syndicate chairman" },
    fund: { zh: "做空的老银行家", en: "The old bear banker" },
    trader: { zh: "行情巷经纪", en: "Share-dealer" },
    retail: { zh: "分期认购人", en: "Subscription holder" },
  },
  pegRate: 1,
  band: 0.05,
  reserves: 24_000,
  committedForward: 0,
  startRate: 0.1,
  // "Rate" here is the deposit fraction demanded on a new subscription.
  maxRate: 0.7,
  allowEquityDefence: false,
  reserveEfficiency: 0.85,
  rateDefenceCap: 0.6,
  // Every point of deposit you waive is leverage somebody else is running at
  // the call date — and at the call date it lands on you. Raising the deposit
  // also starves the subscription of the day: cheap now, but the rally cools.
  rateDragK: 0.1,
  days: 8,
  escalation: 1.3,
  historicalOutcome: "broke",
  autoDefence: { spend: 0.06, nudgeOnDay: 3, nudgeTo: 0.24, hikeOnDay: 6 },
  phases: [
    {
      day: 1,
      titleZh: "注册制",
      titleEn: "The Registration Act",
      bodyZh: "新法生效：开办铁路公司不再需要逐家立法。想开一条线？注册就行。报纸管这叫「自由」。",
      bodyEn: "The new act is in force: no private bill per railway, only registration. Want a line? File the papers. The papers call it freedom.",
      pressure: 0.1,
    },
    {
      day: 2,
      titleZh: "方案潮",
      titleEn: "The avalanche of schemes",
      bodyZh: "每周十几条新线提交议会。报纸的铁路专版比股票版还长。有些线路画在同一片山谷里——它们不知道彼此存在。",
      bodyEn: "Better than a scheme a day reaches the House. The railway column outgrew the stock list. Two of the lines are surveyed through the same valley, each unaware of the other.",
      pressure: 0.14,
    },
    {
      day: 3,
      titleZh: "认购日",
      titleEn: "Subscription day",
      bodyZh: "一成首付，余款分期。认购单排队的人从经纪行的门口排到街角。到傍晚，单子已经在转手加价了。",
      bodyEn: "A tenth down, the balance by instalment. The queue for the slips runs from the broker's door round the corner. By evening the slips are already trading at a markup.",
      pressure: 0.15,
    },
    {
      day: 4,
      titleZh: "贴现率上调",
      titleEn: "The discount rate goes up",
      bodyZh: "中央银行把贴现率调高了。理由说得很清楚：市面上「投机性的占用」太多了。钱一夜之间变贵。",
      bodyEn: "The central bank has raised its discount rate. The reason is stated plainly: too much money is 'occupied by speculation'. Money got expensive overnight.",
      pressure: 0.2,
      equityShock: 0.04,
    },
    {
      day: 5,
      titleZh: "那篇社论",
      titleEn: "The leader",
      bodyZh: "报纸头版做了一道算术题：把所有已批准线路的预测货运量和客运量加起来，再除以全国的产量和人口。它请读者自己看余数。",
      bodyEn: "The front page sets one sum: add the projected freight and passengers of every authorized line, divide by the nation's output and population. It invites the reader to look at what is left over.",
      pressure: 0.24,
      equityShock: 0.05,
    },
    {
      day: 6,
      titleZh: "缴款日",
      titleEn: "The call dates",
      bodyZh: "分期款的第一批到期。认购人开始违约——不是亏了钱，是从来没打算付全款。放贷收认购单做抵押的人最先倒。",
      bodyEn: "The first instalments fall due. Subscribers begin to default — not because they lost money, but because they never meant to pay in full. The men lending against slips go first.",
      pressure: 0.3,
      equityShock: 0.09,
    },
    {
      day: 7,
      titleZh: "还在发行",
      titleEn: "Still issuing",
      bodyZh: "行情崩落的一周里，仍有十七份新方案交到了议会。其中一份申请修一条通往同一座港口的第四条铁路。",
      bodyEn: "In the week the market is going down, seventeen further schemes reach the House. One of them applies to build a fourth line to the same port.",
      pressure: 0.34,
      equityShock: 0.07,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "rw-c1",
      day: 2,
      direction: "in",
      fromZh: "铁路专版主编",
      fromEn: "Editor, railway column",
      roleZh: "报社",
      roleEn: "The press",
      lines: [
        { zh: "主席先生，铁路版这周加印了三次。广告费排到下个月。", en: "Mr Chairman, we have reprinted the railway column three times this week. Advertisements are booked a month out." },
        { zh: "有一条消息想请您确认：明年提交的方案数，会超过今年吗？", en: "One thing we would like confirmed: will next year's list of schemes be longer than this year's?" },
      ],
      options: [
        {
          id: "honest",
          zh: "不会。方案数已经到顶了——我劝投资人别按今年的速度外推。",
          en: "It will not. The list has peaked — and I would tell investors not to extrapolate from this year.",
          effect: { credibility: 0.12, pressure: 0.05 },
          replyZh: "这句话会上头版。您确定？明天全城都会读到你亲口说「到顶了」。",
          replyEn: "That sentence will run at the head of the page. Are you certain? The whole city will read you saying 'peaked' by morning.",
          tone: "good",
        },
        {
          id: "hype",
          zh: "会。明年是铁路的世纪，现在下车的人会在站台上看着世纪开走。",
          en: "It will. This is the century of the rails, and whoever gets off now will watch the century leave without them.",
          effect: { pressure: -0.08, equityMul: 0.98, credibility: -0.1 },
          replyZh: "好句子。我原样印。明天的认购队伍会更长。",
          replyEn: "That is a fine sentence. I shall print it as it stands. Tomorrow's queues will be longer.",
          tone: "bad",
        },
      ],
    },
    {
      id: "rw-c2",
      day: 4,
      direction: "in",
      fromZh: "一位总工程师",
      fromEn: "A chief engineer",
      roleZh: "勘测顾问",
      roleEn: "Surveying consultant",
      minDetail: 1,
      lines: [
        { zh: "主席，我测了三十年线。现在有人拿我的图纸去卖「第二干线」的认购单。", en: "Chairman, I have surveyed lines for thirty years. Men are now selling subscriptions for 'second trunk lines' off my drawings." },
        { zh: "那条坡度，蒸汽机车拉不动满载的货车。数学不允许这条铁路存在。", en: "That gradient will not take a loaded freight behind a locomotive. The mathematics do not permit this railway to exist." },
      ],
      options: [
        {
          id: "listen",
          zh: "把勘测报告全交给我。凡是我们承销的方案，按您的坡度表重新过一遍。",
          en: "Give me every survey you have. Every scheme we underwrite goes back through your gradient tables.",
          effect: { credibility: 0.14, pressure: 0.08 },
          replyZh: "报告明天送到。您会损失一半的承销量——和保住另一半的可能。",
          replyEn: "The reports will be with you tomorrow. You will lose half the book — and keep the possibility of the other half.",
          tone: "good",
        },
        {
          id: "dismiss",
          zh: "数学可以修订，认购单不能作废。下一个。",
          en: "The mathematics can be revised; the subscriptions cannot. Next.",
          effect: { pressure: -0.06, equityMul: 0.97, credibility: -0.12 },
          replyZh: "……是。那我只提醒您一句：铁轨不会因为认购单写满数字就变平。",
          replyEn: "…Very well. One reminder only: rails do not grow flatter because the subscription paper is full of numbers.",
          tone: "bad",
        },
      ],
    },
    {
      id: "rw-c3",
      day: 5,
      direction: "out",
      fromZh: "中央银行行长",
      fromEn: "The central bank governor",
      roleZh: "贴现窗口",
      roleEn: "The discount window",
      minDetail: 1,
      lines: [
        { zh: "主席，我把话说在前面：下个月贴现率还要再调。市面上的钱都躺在认购单里，实体贸易在失血。", en: "Chairman, I will say it plainly: the rate moves again next month. The city's money is lying in subscription slips and the real trade is bleeding." },
        { zh: "你们那一行，是继续按一成首付放量，还是自己先收一收？", en: "Your side of the market: do you keep issuing at a tenth down, or do you collect yourselves first?" },
      ],
      options: [
        {
          id: "tighten",
          zh: "我们先收。从明天起，我们承销的新方案首付提到四成，旧认购按期缴款不得展期。",
          en: "We collect first. From tomorrow our new issues take four-tenths down, and no instalment from the old book is rolled.",
          effect: { pressure: 0.1, equityMul: 1.05, credibility: 0.15 },
          replyZh: "记下了。行情会冷，但清算所会记得是谁先把脚从火里拿出来的。",
          replyEn: "Noted. The market will cool, and the clearing house will remember who pulled their foot out of the fire first.",
          tone: "good",
        },
        {
          id: "defy",
          zh: "行长，利率管的是钱，管不住世纪。我们照发。",
          en: "Governor, the rate governs money, not a century. We issue on.",
          effect: { pressure: -0.1, credibility: -0.15 },
          replyZh: "那就祝您的认购人和您的金库一样长寿。窗口对你们关到缴款日之后。",
          replyEn: "Then may your subscribers live as long as your treasury. The window stays shut to you past the call dates.",
          tone: "bad",
        },
      ],
    },
    {
      id: "rw-c4",
      day: 6,
      direction: "in",
      fromZh: "认购人代表",
      fromEn: "A delegation of subscribers",
      roleZh: "持单人",
      roleEn: "Slip holders",
      minDetail: 2,
      lines: [
        { zh: "主席，缴款日到了，我们中间一半人缴不出第二期。", en: "Chairman, the call date is here and half of us cannot meet the second instalment." },
        { zh: "有个提议：拿认购单本身做抵押，您垫这一期。行情回暖我们连本带息还您。", en: "A proposal: pledge the slips themselves to you for this instalment. When the market recovers we repay you with interest." },
      ],
      options: [
        {
          id: "refuse",
          zh: "不行。抵押品就是正在违约的东西，这笔垫款我赔不起。违约的按章程处理，其余的照常。",
          en: "No. The collateral would be the very thing that is defaulting; I cannot carry that. Defaults follow the articles, the rest pay as scheduled.",
          effect: { pressure: 0.12, equityMul: 1.06, credibility: 0.1 },
          replyZh: "我们会破产的。您明白吗？——明白。但您也明白，接了这张纸，下一批缴款日来的就不止一半人了。",
          replyEn: "You will ruin us. Do you understand? — I do. And you understand that if you take this paper, at the next call date it will not be half of us at this door.",
          tone: "good",
        },
        {
          id: "carry",
          zh: "垫。行情就差一口气，这口气我来出。",
          en: "We carry them. The market is one breath short, and I will supply the breath.",
          effect: { pressure: -0.16, equityMul: 0.9 },
          replyZh: "上帝保佑您，主席。您刚才买下的每一张认购单，明天都会有人拿新的来换。",
          replyEn: "God keep you, Chairman. Every slip you just carried, tomorrow there will be a fresh one asking the same.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.85,
      titleZh: "在缴款日之前下车",
      titleEn: "Be out before the call dates",
      howZh: "你拿着分期认购单。这门生意里只有一种技术：在下一期缴款日之前把单子卖掉，而且要在所有人同时想到这件事之前。看两个信号——新方案提交的速度，和中央银行的贴现率。",
      howEn: "You hold subscription slips. There is one skill in this trade: sell before the next call date, and before everyone else has the same thought at once. Watch two signals — the rate at which new schemes are filed, and the central bank's discount rate.",
      winZh: "最后一天净值还剩 85% 以上。这场狂热的赢家不是赚最多的人，是把单子变成现金的人。",
      winEn: "End with 85% of your net worth or more. The winners of this fever were not the ones who made most — they were the ones who turned slips into cash.",
      trapZh: "「这轮结束我再卖」是这场狂热里最贵的一句话：等到想卖的时候，柜台前面站满了同一张认购单的持有人。",
      trapEn: "'I will sell after this tranche' is the dearest sentence of this fever: by the time you go to sell, the counter is ringed by holders of your own slip.",
    }),
    trader: traderObjective({
      target: 0.25,
      howZh: "你在行情巷做认购单的转手生意。涨的时候人人向你买，缴款日临近的时候没人向你买——这门生意的全部利润都在于，存货在缴款日之前清干净。",
      howEn: "You deal in subscription slips. On the way up everybody buys from you; as the call dates approach nobody does — the whole profit of this trade is an inventory that is empty before the calls arrive.",
      trapZh: "别接最后一手认购单。那不是货，是一张写着缴款日期的账单。",
      trapEn: "Do not take the last lot of slips. That is not inventory, it is an invoice with a date on it.",
    }),
    fund: {
      side: "attack",
      kind: "profit",
      target: 0.3,
      titleZh: "做空纸上的铁路",
      titleEn: "Short the paper railways",
      howZh: "你不需要把行情打崩——供给自己会把它压垮。你等的是两个日子中间的那一段：贴现率上调之后、缴款日之前。在那一段里，每一天都有新发行从市场里抽走现金，而做空的人只需要收租。",
      howEn: "You do not need to break the market — the supply will do it for you. What you wait for is the gap between two dates: after the discount rate rises, before the calls arrive. In that gap every new issue is pulling cash out of the market, and a bear is just collecting rent.",
      winZh: "最后一天自己的账面收益 ≥ +45%。",
      winEn: "Finish the last day up 45% or more on your own book.",
      trapZh: "供给崩盘不需要理由，但它需要时间。做空太早，你会替整场狂热垫资；这关的杠杆不在你手上，在认购人手上——等他们违约，别催。",
      trapEn: "The supply collapse needs no reason, but it does need time. Short too early and you are financing the whole fever. The leverage is not in your book — it is in the subscribers'. Wait for their defaults; do not rush them.",
    },
    governor: {
      side: "defend",
      kind: "holdPeg",
      target: 0,
      equityFloor: 55,
      titleZh: "停掉印刷机，保住承销集团",
      titleEn: "Stop the presses, keep the syndicate",
      howZh: "你手里有两样互相拆台的东西。「首付比例」调得越低，今天的认购越火——而缴款日的违约越多，每一分都记在你集团的清偿能力上。「回购」能把卖压直接买走，但金库是有限的。这一关的正解不是最热的认购季，是把新发行停下来、把首付提上去，让集团活着见到真正开工的那条铁路。",
      howEn: "You hold two things that dismantle each other. The lower the deposit fraction, the hotter today's subscription — and the heavier the defaults at the call dates, every penny of it charged to your syndicate's solvency. Buying the stock back takes the selling straight off the board, and the treasury is finite. The right answer here is not the hottest subscription season: it is stopping the new issues, raising the deposit, and having a syndicate still standing when a real rail is actually laid.",
      winZh: "撑满全部交易日、发行没有被中止，并且收盘时集团清偿能力仍在 55 以上（开局 100）。",
      winEn: "Last every session with the issue calendar alive and syndicate solvency still above 55 at the close (it opens at 100).",
      trapZh: "把首付降到一成以下，认购会排到街角——然后你会在同一个星期里，既失去行情，又失去集团。这一关输得最惨的玩法，是把「市场想要什么」当成「集团需要什么」。",
      trapEn: "Drop the deposit below a tenth and the queue runs round the corner — and in the same week you lose the market and the syndicate together. The surest way to lose this one is mistaking what the market wants for what the syndicate needs.",
    },
  },
};
/**
 * A bubble, from inside the company that is inflating it.
 *
 * Every other scenario in the game hands you something to defend. This one
 * hands you something to inflate, and the only question is whether you can
 * still be solvent when it stops. The lever that keeps the price up — lending
 * buyers the money to buy your own stock — is the same lever that hollows out
 * the balance sheet you will need in September.
 */
export const SOUTHSEA: Scenario = {
  id: "southsea",
  kind: "mania",
  nameZh: "远洋公司泡沫",
  nameEn: "The Oceanic Company Bubble",
  year: "1720",
  grade: 2,
  order: 2,
  major: false,
  briefZh:
    "公司成立的时候没打算做生意。它的生意就是国债：把政府欠公众的债换成自家的股票，政府付给它利息，它付给股东分红。真正的关键是换股比例——股价越高，换同样一笔债需要的股票越少，公司剩下的股票就越多，那些多出来的可以卖钱。所以有一件事是数学上确定的：股价越高，这套方案越赚。于是全城都在算同一道题，而你坐在能决定答案的那个位子上。",
  briefEn:
    "The company was never meant to trade. Its business is the national debt: swap what the government owes the public into shares of itself, collect interest from the state and pay dividends to shareholders. The whole thing turns on the conversion ratio — the higher the share price, the fewer shares it takes to retire the same debt, and the more shares are left over to sell. So one thing is mathematically certain: the higher the price, the better the scheme works. The entire city is doing that arithmetic, and you are sitting in the chair that decides the answer.",
  historyZh:
    "史实：南海公司成立于 1711 年，以承接部分英国国债换取与西属美洲贸易的专营权。1720 年，议会通过法案允许其将约 3,000 万英镑国债转换为公司股票。股价从 1 月约 128 英镑涨至 3 月约 330 英镑、5 月约 550 英镑，8 月初见顶于约 1,000 英镑，9 月底跌回约 150 英镑，年底约 124 英镑。公司在认购中允许分期付款，并直接借钱给买家购买自家股票。1720 年 6 月通过的《泡沫法案》限制未经特许的合股公司，8 月对若干仿效公司的执法被普遍认为加速了崩盘——投资者为补缴其他认购款而抛售南海股票。牛顿据载在此役中亏损约两万英镑。1721 年议会调查后，多名董事的财产被没收。",
  historyEn:
    "History: the South Sea Company was founded in 1711, taking on part of the British national debt in exchange for a monopoly on trade with Spanish America. In 1720 Parliament allowed it to convert roughly £30m of government debt into company stock. The share price rose from about £128 in January to roughly £330 in March and £550 in May, peaking near £1,000 in early August, then falling to about £150 by late September and £124 by December. The company sold subscriptions on instalments and lent money directly to buyers to purchase its own shares. The Bubble Act of June 1720 restricted unchartered joint-stock companies, and enforcement against imitators in August is widely thought to have accelerated the collapse, as investors sold South Sea stock to meet calls elsewhere. Isaac Newton is reported to have lost around £20,000. A parliamentary inquiry in 1721 led to the confiscation of several directors' estates.",
  historyDeepZh: [
    "公司先后推出四次认购（money subscriptions），每次都只需先付一部分，余款分期——这等于让买家用极小的首付买入，与两百年后的保证金交易在数学上是同一件事。",
    "公司向买家发放贷款，抵押品就是它自己的股票。股价下跌时，抵押品和借款人同时变差。",
    "1720 年夏天出现了大量仿效的合股公司，其中包括若干只有招股书没有业务的项目。《泡沫法案》压制了它们，却也迫使投资者卖出手中最容易变现的资产——南海股票。",
    "崩盘后，罗伯特·沃波尔主持善后，将部分股本转入东印度公司与英格兰银行，并保住了政府信用；这场处理使他成为事实上的首位首相。",
    "十九世纪之前，英国对合股公司的严格限制一直延续，直到 1825 年《泡沫法案》被废除。",
  ],
  historyDeepEn: [
    "The company ran four successive money subscriptions, each taking only a part payment with the balance by instalment — small money down for a large position, which is arithmetically the same thing as margin two centuries later.",
    "It lent to buyers against its own shares as collateral. When the price fell, the collateral and the borrower deteriorated simultaneously.",
    "The summer of 1720 produced a swarm of imitator companies, some with a prospectus and no business at all. The Bubble Act suppressed them — and in doing so forced investors to sell the asset they could most easily sell, which was South Sea stock.",
    "Robert Walpole managed the aftermath, moving part of the capital into the East India Company and the Bank of England and preserving government credit; the episode effectively made him the first Prime Minister.",
    "Britain's restrictions on joint-stock companies outlived the bubble by a century — the Bubble Act was not repealed until 1825.",
  ],
  lessonZh:
    "这一战教的是：「借钱给买家买你自己的东西，等于把销售额记在自己的负债上」。行情涨的时候这招看起来无本万利：你创造了需求，需求抬高了价格，价格让方案更赚。问题是你收到的不是钱，是一张欠条，而欠条的抵押品就是你自己的股票。等价格转头，抵押品和借款人同时变差，你手上什么都没有。任何时代，只要看到一个卖家在给买家融资，就该问：这笔销售额里，有多少其实是应收款？",
  lessonEn:
    "The lesson: lending buyers the money to buy your own product means booking your sales as your own liability. On the way up it looks like free money — you create the demand, the demand lifts the price, the price makes the scheme better. What you actually received was not cash but a note, secured on your own stock. When the price turns, the collateral and the borrower go bad at the same moment and you are holding nothing. In any century, when a seller is financing its buyers, ask how much of the revenue is really a receivable.",
  lexicon: MANIA_LEXICON,
  seatLabel: {
    governor: { zh: "公司司库", en: "Company treasurer" },
    fund: { zh: "做空的银行家", en: "The bear banker" },
    trader: { zh: "交易巷经纪", en: "Exchange Alley broker" },
    retail: { zh: "认购人", en: "Subscriber" },
  },
  pegRate: 1,
  band: 0.05,
  reserves: 20_000,
  committedForward: 0,
  startRate: 0,
  // "Rate" here is the share of the purchase price the company itself lends.
  maxRate: 0.6,
  allowEquityDefence: false,
  reserveEfficiency: 0.9,
  rateDefenceCap: 0.62,
  // Every pound lent against your own stock comes straight out of the solvency
  // you will be judged on in September. This is the scenario's whole trade.
  rateDragK: 0.34,
  days: 8,
  historicalOutcome: "broke",
  autoDefence: { spend: 0.05, nudgeOnDay: 3, nudgeTo: 0.26, hikeOnDay: 6 },
  phases: [
    {
      day: 1,
      titleZh: "法案通过",
      titleEn: "The Act passes",
      bodyZh: "议会批准了换股方案。股价当天从 128 跳到 180。所有人都看懂了同一件事：价格越高，方案越赚。",
      bodyEn: "Parliament approves the conversion. The price goes from 128 to 180 on the day. Everybody has understood the same thing: the higher the price, the better the scheme.",
      pressure: 0.1,
    },
    {
      day: 2,
      titleZh: "第一次认购",
      titleEn: "The first subscription",
      bodyZh: "只要先付两成，余款分期。排队的人从交易巷一直排到教堂。",
      bodyEn: "Two-tenths down, the balance by instalment. The queue runs from Exchange Alley to the church.",
      pressure: 0.14,
    },
    {
      day: 3,
      titleZh: "仿效者",
      titleEn: "The imitators",
      bodyZh: "一个月里冒出上百家新公司，其中一家的招股书写着「一项极有利可图的事业，但无人可知其内容」。",
      bodyEn: "A hundred new companies in a month, one of them promising 'an undertaking of great advantage, but nobody to know what it is'.",
      pressure: 0.16,
      minDetail: 1,
    },
    {
      day: 4,
      titleZh: "顶",
      titleEn: "The top",
      bodyZh: "股价到了 1,000。没有钟声，没有公告。只是买单少了一点，而少了一点就够了。",
      bodyEn: "One thousand. No bell, no announcement. Just slightly fewer buyers — and slightly fewer is enough.",
      pressure: 0.24,
      equityShock: 0.04,
    },
    {
      day: 5,
      titleZh: "《合股公司法》",
      titleEn: "The Joint-Stock Act",
      bodyZh: "议会压掉了那些仿效公司。你以为这是利好——直到你发现，被压掉的那些公司的认购款，是靠卖你的股票来补的。",
      bodyEn: "Parliament crushes the imitators. You read it as good news — until you notice that the calls on those subscriptions are being met by selling your stock.",
      pressure: 0.34,
      equityShock: 0.06,
    },
    {
      day: 6,
      titleZh: "分期款收不上来",
      titleEn: "The instalments stop coming",
      bodyZh: "认购人付不出下一期。你手上不是现金，是一叠以自家股票为抵押的欠条。",
      bodyEn: "The subscribers cannot meet the next instalment. What you are holding is not cash — it is a stack of notes secured on your own stock.",
      pressure: 0.4,
      equityShock: 0.1,
      minDetail: 1,
    },
    {
      day: 7,
      titleZh: "银行也不续了",
      titleEn: "The bank will not roll",
      bodyZh: "一家合作银行拒绝继续承兑。消息传到交易巷用了半个小时。",
      bodyEn: "An allied bank refuses to keep accepting the paper. It takes half an hour to reach Exchange Alley.",
      pressure: 0.36,
      equityShock: 0.08,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "ss-c1",
      day: 2,
      direction: "in",
      fromZh: "认购处",
      fromEn: "The subscription room",
      roleZh: "主管",
      roleEn: "Clerk in charge",
      lines: [
        { zh: "司库先生，门外的人要求把首付比例再降一点。", en: "Treasurer — the crowd outside is asking for a smaller first payment." },
        { zh: "降了，今天能多卖一倍。", en: "Lower it and we sell twice as much today." },
      ],
      options: [
        {
          id: "lower",
          zh: "降。趁热把这一轮卖完。",
          en: "Lower it. Sell this tranche while the heat is on.",
          effect: { pressure: -0.1, equityMul: 0.95 },
          replyZh: "照办。我们今天会收到很多签名，和很少的钱。",
          replyEn: "Done. We shall take a great many signatures today, and very little money.",
          tone: "info",
        },
        {
          id: "hold",
          zh: "不降。我要的是现金，不是签名。",
          en: "No. I want cash, not signatures.",
          effect: { pressure: 0.07, equityMul: 1.04, credibility: 0.1 },
          replyZh: "那队伍会短一些。金库会厚一些。",
          replyEn: "The queue will be shorter. The vault will be heavier.",
          tone: "good",
        },
      ],
    },
    {
      id: "ss-c2",
      day: 4,
      direction: "in",
      fromZh: "一位数学家",
      fromEn: "A mathematician",
      roleZh: "股东",
      roleEn: "Shareholder",
      minDetail: 1,
      lines: [
        { zh: "先生，我卖掉了我的股份，赚了一倍。", en: "Sir — I have sold my holding at twice what I paid." },
        { zh: "……但它又涨了三成。我想再买回来。你们的下一轮认购还有名额吗？", en: "…And it has risen a further third since. I should like to buy back in. Is there room in your next subscription?" },
      ],
      options: [
        {
          id: "warn",
          zh: "先生，我劝您别买。这个价格没有道理。",
          en: "Sir, I would advise against it. There is no reason in this price.",
          effect: { credibility: 0.12, pressure: 0.05 },
          replyZh: "我能算出天体的运行，算不出人们的疯狂。……我还是买。",
          replyEn: "I can calculate the motions of the heavenly bodies, but not the madness of people. …I shall buy anyway.",
          tone: "info",
        },
        {
          id: "sell",
          zh: "有名额。您要多少？",
          en: "There is room. How much would you like?",
          effect: { pressure: -0.06, equityMul: 0.98 },
          replyZh: "全部。我这辈子只做一次这样的决定。",
          replyEn: "All of it. I shall make such a decision only once in my life.",
          tone: "bad",
        },
      ],
    },
    {
      id: "ss-c3",
      day: 5,
      direction: "out",
      fromZh: "财政大臣",
      fromEn: "The Chancellor",
      roleZh: "国库",
      roleEn: "The Exchequer",
      minDetail: 1,
      lines: [
        { zh: "《合股公司法》已经生效。那些仿效的公司会被清掉。", en: "The Joint-Stock Act is in force. The imitators will be swept away." },
        { zh: "这对你们是好事——我猜。", en: "That is good for you. I presume." },
      ],
      options: [
        {
          id: "seeit",
          zh: "不一定。他们的认购人要补款，会卖我们的股票去补。",
          en: "Not necessarily. Their subscribers must meet calls, and they will sell our stock to do it.",
          effect: { pressure: -0.1, credibility: 0.12 },
          replyZh: "……你是第一个说出这句话的人。你打算怎么办？",
          replyEn: "…You are the first person to say that out loud. What do you propose to do?",
          tone: "good",
        },
        {
          id: "cheer",
          zh: "是好事。少了竞争，钱都会回到我们这里。",
          en: "It is good news. With the competition gone the money comes back to us.",
          effect: { pressure: 0.08 },
          replyZh: "那就好。祝贺。",
          replyEn: "Splendid. My congratulations.",
          tone: "bad",
        },
      ],
    },
    {
      id: "ss-c4",
      day: 7,
      direction: "in",
      fromZh: "公司出纳",
      fromEn: "The company cashier",
      roleZh: "金库",
      roleEn: "The vault",
      minDetail: 2,
      lines: [
        { zh: "司库先生，今天进来的钱只有上周的六分之一。", en: "Treasurer, today's receipts are a sixth of last week's." },
        { zh: "而我们放出去的贷款，抵押品全是我们自己的股票。", en: "And every loan we have out is secured on our own stock." },
      ],
      options: [
        {
          id: "callin",
          zh: "停止放贷，开始收回。难看，但现在必须做。",
          en: "Stop lending. Start calling them in. It will look ugly and it has to be done.",
          effect: { pressure: 0.12, equityMul: 1.08, credibility: 0.1 },
          replyZh: "价格会掉。但至少掉完之后我们还在。",
          replyEn: "The price will fall. At least we shall still be here when it has.",
          tone: "good",
        },
        {
          id: "lendmore",
          zh: "继续放。把价格撑住，撑住就还有机会。",
          en: "Keep lending. Hold the price up and there is still a chance.",
          effect: { pressure: -0.14, equityMul: 0.88 },
          replyZh: "……是。那我们就把最后一点真钱也换成纸。",
          replyEn: "…Very well. We shall turn the last of the real money into paper.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.85,
      titleZh: "在音乐停之前下车",
      titleEn: "Be off before the music stops",
      howZh: "你是认购人。这一关唯一的技术是「退出」：涨的时候没人会提醒你，跌的时候你卖不掉。看两个东西——分期款有没有人在按时缴，以及公司是不是在借钱给买家。",
      howEn: "You are a subscriber. The only skill here is exit: nobody reminds you on the way up and you cannot sell on the way down. Watch two things — whether the instalments are being paid on time, and whether the company is lending buyers the money.",
      winZh: "最后一天净值还剩 85% 以上。这一关的通关线很高，因为这场泡沫里真正的赢家是全身而退的人，不是赚得最多的人。",
      winEn: "End with 85% of your net worth or more. The bar is high here because the winners of this bubble were the ones who got out whole, not the ones who made the most.",
      trapZh: "「我上次卖早了」是这一关最贵的一句话。赚过一次的人会用两倍的仓位再进来一次。",
      trapEn: "'I sold too early last time' is the most expensive sentence in this scenario. Whoever won once comes back with twice the size.",
    }),
    trader: traderObjective({
      target: 0.25,
      howZh: "你在交易巷做市。这一关的利润不在方向，在你手上的存货——涨的时候人人要买，跌的时候柜台前一个人都没有。",
      howEn: "You make markets in Exchange Alley. The profit here is not in the direction, it is in your inventory: on the way up everyone wants it, on the way down nobody comes to the counter at all.",
      trapZh: "别用公司的贷款进货。那笔贷款的抵押品，就是你进的那批货。",
      trapEn: "Do not finance your inventory with the company's loans. The collateral on that loan is the inventory.",
    }),
    fund: {
      side: "attack",
      kind: "profit",
      target: 0.45,
      titleZh: "做空这场泡沫",
      titleEn: "Short the bubble",
      howZh: "这一关你赢不了「把行情打崩」——撑价格的是公司自己，而它有的是办法撑到把自己掏空为止。你要赚的是另一样东西：它的清偿能力。盯住那条线，做空股票，然后等分期款收不上来的那一周。",
      howEn: "You will not win this one by breaking the rally — the company itself is holding the price up, and it has ways of doing that right until it is hollow. What you are short is the other number: its solvency. Watch that line, short the stock, and wait for the week the instalments stop coming.",
      winZh: "最后一天自己的账面收益 ≥ +45%。",
      winEn: "Finish the last day up 45% or more on your own book.",
      trapZh: "泡沫最后一段是最陡的那一段。做空做得太早，你会在正确的判断上被轧死；只做空「行情」而不做空它的账本，你会发现行情根本没崩，崩的是公司。",
      trapEn: "The last leg of a bubble is the steepest one: short it too early and a correct call will run you over. And short only the rally rather than the book, and you will find the rally never broke — the company did.",
    },
    governor: {
      side: "defend",
      kind: "holdPeg",
      target: 0,
      equityFloor: 50,
      titleZh: "撑住行情，并且还剩下一家公司",
      titleEn: "Hold the rally, and still have a company",
      howZh: "你有两张牌，而且它们互相抵消。「给买家放贷」能立刻造出买盘，但每一镑贷款都从你的清偿能力里扣掉，因为抵押品是你自己的股票。「回购自家股票」直接买回卖压，但金库是有限的。你要的不是最高的价格，是一条能走到最后一天的路。",
      howEn: "Two cards, and they cancel each other. Lending buyers the money manufactures demand instantly, and every pound of it comes out of your solvency, because the collateral is your own stock. Buying your own shares back takes the selling off the board, and the vault is finite. What you want is not the highest price — it is a path that reaches the last day.",
      winZh: "撑满全部交易日、行情不崩，并且收盘时账面清偿能力仍在 50 以上（开局 100）。",
      winEn: "Last every session with the rally intact and book solvency still above 50 at the close (it opens at 100).",
      trapZh: "把放贷比例拉满，价格确实会撑住——撑到你已经没有公司了为止。这一关不是输在股价上，是输在清偿能力上。",
      trapEn: "Max out the lending and the price does hold — right up to the point where there is no company left. This one is not lost on the share price. It is lost on solvency.",
    },
  },
};
