import type { Scenario } from "../types.ts";
import { LEVERAGE_LEXICON, RUN_LEXICON, retailObjective, traderObjective } from "./seats.ts";

/**
 * Three panics, a century apart, that are the same panic.
 *
 * 1907 is a run on institutions. 1929 is a run on leverage. 1987 is a run on
 * a piece of software that was selling because the price was falling because
 * it was selling. What connects them is that in each one the thing that
 * spread the fire was a mechanism nobody had looked at closely — the trust
 * companies' reserve rules, the call-loan book, the hedging programs.
 */

export const PANIC07: Scenario = {
  id: "panic07",
  kind: "run",
  nameZh: "银行家的恐慌",
  nameEn: "The Bankers' Panic",
  year: "1907",
  grade: 1,
  order: 1,
  major: false,
  briefZh:
    "狮子国还没有中央银行。清算所是一个私人俱乐部，最后贷款人是一个人——不是一个机构。十月，一场逼空铜矿股的行动失败，操盘的人恰好还控制着几家银行；消息传开，储户开始排队。真正危险的不是银行，是「信托公司」：它们做着银行的生意，却不必遵守银行的准备金规矩。你手上有一个临时凑出来的资金池，和一部电话。",
  briefEn:
    "Leo has no central bank. The clearing house is a private club and the lender of last resort is a man, not an institution. In October a squeeze on a copper stock fails, and the man behind it turns out to control several banks as well. Word spreads and the queues form. The real danger is not the banks — it is the trust companies, which do a bank's business without a bank's reserve rules. What you have is a pool of money scraped together this morning, and a telephone.",
  historyZh:
    "史实：1907 年 10 月，一场逼空联合铜业（United Copper）的行动失败，牵连出其操盘者控制的多家银行，引发挤兑。10 月 22 日，纽约第三大信托公司尼克博克信托（Knickerbocker Trust）在挤兑中暂停营业。信托公司当时的现金准备率远低于国民银行。10 月 24 日纽交所拆借利率一度报至 100% 以上，交易所濒临提前收市；摩根在数十分钟内组织约 2,500 万美元资金投入拆借市场，交易所得以开到收盘。美国财政部亦存入约 2,500 万美元。11 月初，摩根将信托公司负责人召集至其图书馆，直到各方同意再出资约 2,500 万美元救助为止。道指自 1906 年高点回落近一半。这场恐慌直接促成了 1908 年《奥尔德里奇—弗里兰法案》和 1913 年《联邦储备法》。",
  historyEn:
    "History: in October 1907 a failed corner in United Copper implicated the banks controlled by the men behind it and set off runs. On 22 October the Knickerbocker Trust Company, New York's third largest trust, suspended after a run; trust companies then held far less cash against deposits than national banks. On 24 October call money on the NYSE was quoted above 100% and the exchange came close to closing early; J. P. Morgan assembled roughly US$25m for the call-money market within the hour and it stayed open to the bell. The US Treasury deposited about US$25m as well. In early November Morgan kept the trust company presidents in his library until they agreed to put up a further US$25m. The Dow fell nearly half from its 1906 high. The panic led directly to the Aldrich-Vreeland Act of 1908 and the Federal Reserve Act of 1913.",
  historyDeepZh: [
    "信托公司当时的现金准备约为存款的 5%，而国民银行约为 25%。同样的挤兑，信托公司先倒。",
    "10 月 23 日，美国信托公司（Trust Company of America）成为下一个目标；摩根在核对其资产后判断「这里就是要止住挤兑的地方」，并把资金投向它而不是已经倒下的那家。",
    "10 月 24 日下午，纽交所主席告知摩根交易所必须提前收市；摩根在十几分钟内从多家银行凑出约 2,500 万美元，并要求以不高于 10% 的利率放出。",
    "清算所发行「清算所贷款证券」（clearing house loan certificates）作为银行间的临时支付手段，相当于一种应急货币。",
    "11 月 2 日至 4 日，为救援濒临倒闭的经纪行 Moore & Schley，美国钢铁公司收购了田纳西煤铁（TC&I），该交易需要总统默许其不受反垄断追究。",
  ],
  historyDeepEn: [
    "Trust companies held roughly 5% of deposits in cash against roughly 25% at the national banks. Facing the same run, the trusts fell first.",
    "On 23 October the Trust Company of America became the next target. After going through its books Morgan judged 'this is the place to stop the trouble', and put the money there rather than into the house that had already gone.",
    "On the afternoon of 24 October the president of the NYSE told Morgan the exchange would have to close early. Morgan raised about US$25m from a room of bankers within minutes, on condition it was lent at no more than 10%.",
    "The clearing house issued loan certificates for use between banks — in effect an emergency currency — to economise on cash.",
    "Between 2 and 4 November, to save the failing brokerage Moore & Schley, U.S. Steel acquired Tennessee Coal and Iron, a deal that needed the President's assurance it would not be pursued under antitrust law.",
  ],
  lessonZh:
    "这一战教的是：「挤兑打的是流动性，不是偿付能力」。排队的人不在乎你账上有多少资产，他们在乎今天能不能取到钱。所以救助必须又快又公开——慢慢救等于不救，偷偷救等于没救。另外记住那个真正的漏洞：同样在做银行生意，规矩最松的那一类机构会先倒，而它会把别人一起拖下去。",
  lessonEn:
    "The lesson: a run attacks liquidity, not solvency. Nobody in the queue cares what is on your balance sheet; they care whether they get their money today. So a rescue has to be fast and public — a slow one is not a rescue, and a quiet one does not count. And remember where the hole actually was: whichever class of institution does banking under the loosest rules fails first, and takes the others with it.",
  lexicon: RUN_LEXICON,
  seatLabel: {
    governor: { zh: "清算所委员会主席", en: "Clearing house chairman" },
    fund: { zh: "做空辛迪加", en: "The bear syndicate" },
    trader: { zh: "交易所经纪人", en: "Floor broker" },
    retail: { zh: "储户", en: "Depositor" },
  },
  pegRate: 1,
  band: 0.05,
  reserves: 26_000,
  committedForward: 0,
  startRate: 0.06,
  maxRate: 0.3,
  allowEquityDefence: false,
  allowPledge: true,
  allowHalt: true,
  // A coordinated pool of real money, put where everyone can see it, buys back
  // far more panic than a central bank selling into a one-way forward market.
  reserveEfficiency: 1.5,
  rateDefenceCap: 0.55,
  rateDragK: 0.12,
  days: 8,
  historicalOutcome: "held",
  // What actually happened: money put out fast, in public, and a rate high
  // enough to pull the rest of the city back into the call market.
  autoDefence: { spend: 0.25, nudgeOnDay: 3, nudgeTo: 0.18, hikeOnDay: 5, pledgeOn: 4 },
  phases: [
    {
      day: 1,
      titleZh: "逼空失败",
      titleEn: "The corner fails",
      bodyZh: "一场逼空铜矿股的行动砸了。操盘的人还控制着三家银行，这件事所有人今天下午才知道。",
      bodyEn: "A squeeze on a copper stock collapses. The men behind it also control three banks — a fact everybody learns this afternoon.",
      pressure: 0.16,
      equityShock: 0.04,
    },
    {
      day: 2,
      titleZh: "第一家信托公司",
      titleEn: "The first trust",
      bodyZh: "城里第三大的信托公司门口排了一条街。它的现金准备只有存款的一成。",
      bodyEn: "A queue runs down the block outside the city's third largest trust company. It holds cash against barely a tenth of its deposits.",
      pressure: 0.28,
      equityShock: 0.06,
    },
    {
      day: 3,
      titleZh: "队伍变长了",
      titleEn: "The queue grows",
      bodyZh: "隔壁两家信托也开始排队。报纸登了照片，照片比谣言有效得多。",
      bodyEn: "Two more trusts down the street start queueing. The papers run a photograph, which works far better than any rumour.",
      pressure: 0.24,
      equityShock: 0.05,
      minDetail: 1,
    },
    {
      day: 4,
      titleZh: "拆借市场没有钱",
      titleEn: "No money on the floor",
      bodyZh: "交易所拆借利率报到三位数，还是借不到。交易所主席说：我们可能要提前收市。",
      bodyEn: "Call money is quoted in three figures and still nobody lends. The exchange president says they may have to close early.",
      pressure: 0.32,
      equityShock: 0.1,
    },
    {
      day: 6,
      titleZh: "经纪行要倒",
      titleEn: "A brokerage goes",
      bodyZh: "一家大经纪行的抵押品卖不出去。它一倒，后面还有一串。",
      bodyEn: "A large brokerage cannot sell its collateral. If it goes, there is a line of others behind it.",
      pressure: 0.26,
      equityShock: 0.08,
      minDetail: 1,
    },
  ],
  calls: [
    {
      id: "p07-c1",
      day: 2,
      direction: "in",
      fromZh: "美洲信托公司",
      fromEn: "Trust Company of America",
      roleZh: "总裁",
      roleEn: "President",
      lines: [
        { zh: "主席先生，我们今天付出去了四分之一的存款。明天开门我撑不过中午。", en: "Mr Chairman, we paid out a quarter of our deposits today. If we open tomorrow I do not last past noon." },
        { zh: "我的资产是好的。我只是拿不出现金。", en: "My assets are sound. I simply cannot turn them into cash." },
      ],
      options: [
        {
          id: "audit",
          zh: "把账本送到我这里来。今晚我自己看。",
          en: "Send me the books. I will go through them myself tonight.",
          effect: { credibility: 0.12 },
          replyZh: "马车已经在路上了。谢谢您愿意看。",
          replyEn: "The carriage is already on its way. Thank you for looking.",
          tone: "good",
        },
        {
          id: "blind",
          zh: "钱明早就到，不用看账本。",
          en: "The money will be there in the morning. I do not need to see the books.",
          effect: { pressure: -0.08, reserves: -3000, credibility: -0.1 },
          replyZh: "……您真是个好人。不过您还没问我为什么缺钱。",
          replyEn: "…That is generous of you. You have not asked me why I am short, though.",
          tone: "info",
        },
        {
          id: "refuse",
          zh: "先自救。把能卖的都卖了。",
          en: "Help yourself first. Sell whatever you can sell.",
          effect: { pressure: 0.1, equityMul: 0.96 },
          replyZh: "我卖不动。今天全城没有一个买家。",
          replyEn: "There is no selling it. There is not a bid in this city today.",
          tone: "bad",
        },
      ],
    },
    {
      id: "p07-c2",
      day: 4,
      direction: "in",
      fromZh: "证券交易所",
      fromEn: "The stock exchange",
      roleZh: "交易所主席",
      roleEn: "President of the exchange",
      lines: [
        { zh: "主席先生，拆借报到 100% 还是没人肯借。我要在两点半宣布提前收市。", en: "Mr Chairman, call money is at 100% and nobody will lend. I am going to close early at half past two." },
        { zh: "我需要知道：您有没有钱？", en: "I need to know one thing. Do you have money?" },
      ],
      options: [
        {
          id: "fund",
          zh: "别关。半小时内我给你凑够，利率不许超过 10%。",
          en: "Do not close. I will have it inside the half hour, and it goes out at no more than 10%.",
          effect: { pressure: -0.2, reserves: -6500, equityMul: 1.06, credibility: 0.15 },
          replyZh: "……那我不关。我在场内等您的人。",
          replyEn: "…Then we stay open. I will wait on the floor for your man.",
          tone: "good",
        },
        {
          id: "close",
          zh: "关吧。关了就没有强平了。",
          en: "Close it. Nothing gets liquidated if there is no market.",
          effect: { pressure: 0.22, credibility: -0.2, equityMul: 0.93 },
          replyZh: "好。不过明天再开的时候，价格是多少，我们都不知道。",
          replyEn: "Very well. Though when we reopen, none of us knows what the price will be.",
          tone: "bad",
        },
      ],
    },
    {
      id: "p07-c3",
      day: 5,
      direction: "out",
      fromZh: "国库",
      fromEn: "The Treasury",
      roleZh: "财政部长",
      roleEn: "Secretary of the Treasury",
      minDetail: 1,
      lines: [
        { zh: "我可以把国库的钱存进几家银行。但我需要你告诉我存进哪几家。", en: "I can place government funds with some of the banks. I need you to tell me which ones." },
        { zh: "存错了地方，这笔钱和它买来的信心会一起消失。", en: "Put it in the wrong house and the money disappears, and the confidence with it." },
      ],
      options: [
        {
          id: "strong",
          zh: "存进最强的几家，让它们往下放。",
          en: "Place it with the strongest houses and let them lend it down the chain.",
          effect: { pressure: -0.12, reserves: 5200 },
          replyZh: "照办。明早见报。",
          replyEn: "Done. It will be in the morning papers.",
          tone: "good",
        },
        {
          id: "weak",
          zh: "存进正在排队的那几家。要救就救在火场里。",
          en: "Place it with the houses that have queues outside. Put the water where the fire is.",
          effect: { pressure: -0.18, reserves: 5200, credibility: -0.08 },
          replyZh: "风险在我头上。……好，照你说的办。",
          replyEn: "The risk is mine to carry. …Very well. As you say.",
          tone: "info",
        },
      ],
    },
    {
      id: "p07-c4",
      day: 6,
      direction: "in",
      fromZh: "各信托公司负责人",
      fromEn: "The trust company presidents",
      roleZh: "在您的图书馆里",
      roleEn: "In your library",
      minDetail: 2,
      lines: [
        { zh: "主席先生，我们已经在这个房间里坐了四个小时了。", en: "Mr Chairman, we have been sitting in this room for four hours." },
        { zh: "您把门锁上，是想让我们签哪一份文件？", en: "You have locked the door. Which paper is it you want us to sign?" },
      ],
      options: [
        {
          id: "pool",
          zh: "一人一份额，凑出救助资金。签完才开门。",
          en: "A share each, into the rescue pool. The door opens when it is signed.",
          effect: { pressure: -0.22, reserves: 6800, credibility: 0.1 },
          replyZh: "……给我笔。反正我们谁也逃不掉。",
          replyEn: "…Give me the pen. None of us gets out of this alone anyway.",
          tone: "good",
        },
        {
          id: "shame",
          zh: "谁不签，明天的报纸上会有他的名字。",
          en: "Whoever does not sign will find his name in tomorrow's paper.",
          effect: { pressure: -0.18, reserves: 5200, credibility: -0.15 },
          replyZh: "我们会签。但这件事我们会记很久。",
          replyEn: "We will sign. And we will remember this for a long time.",
          tone: "info",
        },
      ],
    },
    {
      id: "p07-c5",
      day: 7,
      direction: "out",
      fromZh: "清算所",
      fromEn: "The clearing house",
      roleZh: "秘书长",
      roleEn: "Secretary",
      minDetail: 2,
      lines: [
        { zh: "我们可以发行清算所贷款证券，让银行之间用它结算，省下现金。", en: "We can issue clearing house loan certificates so the banks settle between themselves and save the cash." },
        { zh: "说白了，这是我们自己印的临时货币。", en: "To be blunt: it is a temporary currency of our own making." },
      ],
      options: [
        {
          id: "issue",
          zh: "发。现在最缺的就是支付手段。",
          en: "Issue them. What this town is short of is a means of payment.",
          effect: { pressure: -0.14, credibility: -0.05 },
          replyZh: "今晚就印。愿意没人事后来问这算不算合法。",
          replyEn: "We print tonight. Let us hope nobody asks afterwards whether it was lawful.",
          tone: "good",
        },
        {
          id: "refuse",
          zh: "不发。我们不能自己印钱。",
          en: "No. We are not going to print money.",
          effect: { pressure: 0.08, credibility: 0.08 },
          replyZh: "那现金就还是不够。明白了。",
          replyEn: "Then the cash stays short. Understood.",
          tone: "info",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.72,
      howZh: "你是储户，不是银行家。你要做的只有一件事：判断你的钱放在哪一类机构里。规矩最松的那一类，最先关门。",
      howEn: "You are a depositor, not a banker. You have exactly one job: work out which kind of institution your money sits in. The one with the loosest rules closes first.",
      trapZh: "排队是理性的，但全城都排队就没人拿得到钱。真正的判断是提前一天，不是当天。",
      trapEn: "Queueing is rational; everybody queueing means nobody gets paid. The decision that matters is made the day before, not on the day.",
    }),
    trader: traderObjective({
      target: 0.12,
      howZh: "拆借利率报到三位数的时候，现金比任何股票都值钱。你的机会在于：所有人都在被迫卖出，而你只要有钱就能接。",
      howEn: "When call money is quoted in three figures, cash is worth more than any stock on the board. Your edge is simple: everyone is a forced seller and you only need money to be the buyer.",
      trapZh: "别用借来的钱接。这一周随时可能借不到下一笔。",
      trapEn: "Do not do it with borrowed money. There may be no next loan this week.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "把队伍变长",
      titleEn: "Make the queue longer",
      howZh: "你不需要真的打垮谁。你只要让排队的人再多一点，让拆借市场再干一点——剩下的事挤兑自己会做。",
      howEn: "You do not need to break anybody. You only need the queue a little longer and the call market a little drier. The run does the rest by itself.",
      winZh: "在最后一天结束前让清算体系停摆。",
      winEn: "Force the clearing system to stop before the last day ends.",
      trapZh: "这一关历史上是守住的，而且守得干净利落。对面只要有人肯在正确的时间掏出真金白银，你的压力就会被一次性买回去。",
      trapEn: "History held this one, and held it cleanly. The moment somebody on the other side puts real money down at the right hour, your pressure gets bought back in one go.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.55,
      equityFloor: 58,
      titleZh: "止住挤兑",
      titleEn: "Stop the run",
      howZh: "你有两张牌，而且两张都得用。注入流动性能直接把压力买回去——这个资金池不大，但花在明处的每一块钱都算数。抬高拆借利率能把外面的钱吸进市场，代价是所有靠借钱持股的人都要被挤出来。最重要的是快：今天救，比明天救多值一倍。",
      howEn: "Two cards, and you need both. Injecting liquidity buys the pressure straight back — the pool is not large, but every unit spent in public view counts double. Raising the call rate pulls outside money into the market, at the cost of squeezing out everyone who holds stock on credit. Above all, be fast: rescuing today is worth twice rescuing tomorrow.",
      winZh: "撑满全部交易日、清算体系不停摆，收盘时股指在 58 以上，并且挤兑指数压回 0.55 以下——光是熬到最后一天不算数，队伍得真的散掉。",
      winEn: "Last every session with clearing intact, the index above 58 at the close, and the run index back under 0.55. Merely surviving to the last day does not count — the queue has to actually go away.",
      trapZh: "省钱是这一关唯一的输法。资金池留到第七天再用，你会发现它买不回第二天就该买回来的东西。",
      trapEn: "Saving the money is the only way to lose this. Hold the pool back until day seven and you will find it cannot buy back what it should have bought on day two.",
    },
  },
};

export const CRASH29: Scenario = {
  id: "crash29",
  kind: "leverage",
  nameZh: "大崩盘",
  nameEn: "The Great Crash",
  year: "1929",
  grade: 4,
  order: 6,
  major: true,
  briefZh:
    "过去两年，街上每一个人都在用借来的钱买股票。保证金一成就能开仓——你付一块，经纪行借你九块，抵押品就是刚买的那只股票。经纪行的钱从哪来？从企业、从外国银行、从任何愿意拿到八九个点拆借利息的人。这套机器只有一个前提：价格不能跌。现在是十月，价格开始跌了，而追缴通知是按当天收盘价发出去的。",
  briefEn:
    "For two years everybody on this street has been buying stock with borrowed money. Ten per cent down: you put up one and the broker lends you nine, secured on the shares you just bought. Where does the broker's money come from? Corporations, foreign banks, anyone who will take eight or nine per cent on call. The machine has exactly one requirement: the price must not fall. It is October, the price is falling, and the margin calls go out against tonight's close.",
  historyZh:
    "史实：道琼斯工业平均指数于 1929 年 9 月 3 日见顶 381.17 点。10 月 24 日「黑色星期四」成交约 1,290 万股，午间由数家大银行组成的护盘团入场，一度稳住盘面。10 月 28 日「黑色星期一」下跌 12.8%，10 月 29 日「黑色星期二」再跌 11.7%，成交约 1,640 万股。当时经纪商贷款（broker loans）规模约 85 亿美元，而典型的保证金要求低至 10%。美联储曾于 1929 年 8 月将贴现率上调至 6%。道指最终于 1932 年 7 月 8 日见底 41.22 点，较高点下跌约 89%。",
  historyEn:
    "History: the Dow Jones Industrial Average peaked at 381.17 on 3 September 1929. On Black Thursday, 24 October, roughly 12.9m shares traded and a pool of large banks stepped in at midday, steadying the tape for a time. Black Monday, 28 October, fell 12.8%; Black Tuesday, 29 October, fell a further 11.7% on about 16.4m shares. Broker loans then stood around US$8.5bn against margin requirements as low as 10%. The Federal Reserve had raised its discount rate to 6% in August 1929. The Dow finally bottomed at 41.22 on 8 July 1932, about 89% below the peak.",
  historyDeepZh: [
    "10 月 24 日中午，几家大银行的代表在交易所碰头，随后一位经纪人走到美国钢铁的柜台，以高于市价的价格公开报买——盘面当天确实被拉了回来，但只撑了一个周末。",
    "崩盘本身并不是大萧条的原因；1930 至 1933 年间约 9,000 家银行倒闭，货币供应萎缩约三分之一，那才是把衰退拖成萧条的机制。",
    "1929 年 10 月的经纪商贷款中，有很大一部分来自非银行机构——企业和外国出借人，它们可以在任何一天不续做。",
    "1934 年《证券交易法》把保证金要求的设定权交给了美联储，这正是从这次崩盘学到的教训之一。",
    "道指要到 1954 年 11 月才重新回到 1929 年的高点。",
  ],
  historyDeepEn: [
    "At midday on 24 October representatives of several large banks met at the exchange; a broker then walked to the U.S. Steel post and bid publicly above the market. The tape did steady that day — for a weekend.",
    "The crash itself did not cause the Depression. Roughly 9,000 banks failed between 1930 and 1933 and the money supply contracted by about a third; that is the mechanism that turned a recession into a depression.",
    "A large share of October 1929's broker loans came from non-bank lenders — corporations and foreign institutions — any of whom could decline to roll on any given day.",
    "The Securities Exchange Act of 1934 handed the setting of margin requirements to the Federal Reserve, one of the direct lessons of this crash.",
    "The Dow did not regain its 1929 high until November 1954.",
  ],
  lessonZh:
    "这一战教的是：「杠杆不会创造亏损，它只会把亏损提前」。保证金要求这张牌只能管住新进来的杠杆，管不住已经建好的——所以它必须在泡沫的路上提，不能在崩盘的当天提。当天提的结果是强平，强平的结果是更多强平。这个回路一旦转起来，没有任何一笔护盘资金追得上它。",
  lessonEn:
    "The lesson: leverage does not create the loss, it just brings the loss forward. A margin requirement governs new leverage and does nothing to the leverage already on the books — which means it has to be raised on the way up, not on the day. Raised on the day it produces forced selling, and forced selling produces more forced selling. Once that loop is turning, no support pool moves fast enough to catch it.",
  lexicon: {
    ...LEVERAGE_LEXICON,
    rateZh: "保证金比例",
    rateEn: "Margin requirement",
    potZh: "护盘资金池",
    potEn: "Support pool",
    spendZh: "护盘买入",
    spendEn: "Bid the market",
  },
  seatLabel: {
    governor: { zh: "交易所理事会主席", en: "Chairman of the exchange" },
    fund: { zh: "空头集团", en: "The bear pool" },
    trader: { zh: "经纪行合伙人", en: "Brokerage partner" },
    retail: { zh: "融资散户", en: "Margin speculator" },
  },
  pegRate: 1,
  band: 0.04,
  reserves: 34_000,
  committedForward: 0,
  startRate: 0.1,
  maxRate: 0.5,
  allowEquityDefence: false,
  allowHalt: true,
  reserveEfficiency: 0.5,
  rateDefenceCap: 0.66,
  // Leverage taken out early stays out. Leverage forced out during the fall is
  // the fall. Same lever, and the difference between them is this scenario.
  rateRatchets: true,
  // Holding the requirement high through the crash keeps forcing liquidation,
  // which is why the drag here is the heaviest in the game.
  rateDragK: 0.3,
  days: 10,
  historicalOutcome: "broke",
  // The historical sequence: margin tightened only after the fall had started,
  // and a support pool that arrived once and did not come back.
  autoDefence: { spend: 0.1, nudgeOnDay: 6, nudgeTo: 0.22, hikeOnDay: 9 },
  phases: [
    {
      day: 1,
      titleZh: "顶已经过去了",
      titleEn: "The top is behind you",
      bodyZh: "指数离高点不远，但成交在萎缩，涨的股票越来越少。没有人敲锣，顶从来不敲锣。",
      bodyEn: "The index is near its high, but volume is thinning and fewer names are rising. Nobody rings a bell. Tops never ring a bell.",
      pressure: 0.12,
    },
    {
      day: 3,
      titleZh: "第一批追缴",
      titleEn: "The first calls",
      bodyZh: "跌了两天，一成保证金的账户就不够了。追缴通知按收盘价发出，明早十点之前要补钱。",
      bodyEn: "Two down days is all a ten per cent account can take. The calls go out against the close, to be met by ten tomorrow morning.",
      pressure: 0.26,
      equityShock: 0.06,
    },
    {
      day: 4,
      titleZh: "外国出借人不续做",
      titleEn: "The foreign lenders do not roll",
      bodyZh: "拆借给经纪行的那部分外国资金今天没有续做。经纪行只好向客户要钱，客户只好卖股票。",
      bodyEn: "The foreign money on the broker loan book does not roll today. The brokers ask their clients, and the clients sell.",
      pressure: 0.22,
      equityShock: 0.05,
      minDetail: 1,
    },
    {
      day: 5,
      titleZh: "黑色星期四",
      titleEn: "Black Thursday",
      bodyZh: "开盘就是断崖。行情纸带落后实际成交一个多小时——你看到的价格，是一小时前的价格。",
      bodyEn: "It gaps at the open. The ticker runs more than an hour behind the floor — the price you are looking at is an hour old.",
      pressure: 0.42,
      equityShock: 0.12,
    },
    {
      day: 6,
      titleZh: "护盘团",
      titleEn: "The bankers' pool",
      bodyZh: "几家大银行在交易所碰头。中午，一位经纪人走到钢铁股柜台，用高于市价的价格公开报买。盘面回来了——这个周末。",
      bodyEn: "The large banks meet at the exchange. At midday a broker walks to the steel post and bids publicly above the market. The tape comes back — for the weekend.",
      pressure: -0.1,
      equityShock: -0.04,
      minDetail: 1,
    },
    {
      day: 8,
      titleZh: "黑色星期二",
      titleEn: "Black Tuesday",
      bodyZh: "护盘团自己也在卖。成交一千六百万股，很多股票根本找不到买家——不是价格低，是没有价格。",
      bodyEn: "The pool itself is selling. Sixteen million shares, and for many names there is simply no bid — not a low price, no price.",
      pressure: 0.62,
      equityShock: 0.18,
    },
    {
      day: 9,
      titleZh: "经纪行开始倒",
      titleEn: "The brokerages start to go",
      bodyZh: "抵押品的价值低于贷款。经纪行卖掉客户的股票也补不上窟窿，于是它自己成了下一个被追缴的人。",
      bodyEn: "The collateral is worth less than the loan. Selling the client's stock does not fill the hole, so the broker becomes the next one facing a call.",
      pressure: 0.3,
      equityShock: 0.1,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "c29-c1",
      day: 2,
      direction: "in",
      fromZh: "中央银行 · 理事",
      fromEn: "The central bank — a governor",
      roleZh: "货币政策",
      roleEn: "Monetary policy",
      lines: [
        { zh: "主席，我们打算再提一次保证金要求。八月那次提到 6% 没有用。", en: "Chairman — we mean to raise the margin requirement again. August's move to six per cent did nothing." },
        { zh: "您在交易所那边，感觉怎么样？", en: "You are on the exchange side. How does it feel from there?" },
      ],
      options: [
        {
          id: "now",
          zh: "现在提。现在提是降温，跌起来再提就是点火。",
          en: "Raise it now. Now it cools things. Raised into a fall, it lights the fire.",
          effect: { pressure: -0.12, equityMul: 0.97, credibility: 0.1 },
          replyZh: "下周生效。街上会骂我们。",
          replyEn: "Effective next week. The street will curse us.",
          tone: "good",
        },
        {
          id: "wait",
          zh: "别提。市场自己会调整。",
          en: "Leave it. The market will adjust itself.",
          effect: { pressure: 0.1 },
          replyZh: "但愿如此。那我们就先看着。",
          replyEn: "Let us hope so. We will watch, then.",
          tone: "bad",
        },
      ],
    },
    {
      id: "c29-c2",
      day: 3,
      direction: "in",
      fromZh: "一家大经纪行",
      fromEn: "A large brokerage",
      roleZh: "高级合伙人",
      roleEn: "Senior partner",
      lines: [
        { zh: "我们今晚要发出四千份追缴通知。明早十点不到钱就强平。", en: "We send out four thousand margin calls tonight. Anything unmet by ten in the morning gets sold." },
        { zh: "您要不要我们晚一天？", en: "Do you want us to hold off a day?" },
      ],
      options: [
        {
          id: "hold",
          zh: "晚一天。给他们一个早上去凑钱。",
          en: "Hold a day. Give them a morning to find the money.",
          effect: { pressure: 0.06, equityMul: 1.03 },
          replyZh: "那我们自己的资金缺口要自己扛一天。记住是您说的。",
          replyEn: "Then we carry our own hole for a day. I am noting that it was your call.",
          tone: "info",
        },
        {
          id: "send",
          zh: "照发。拖一天只会让窟窿更大。",
          en: "Send them. A day's delay only makes the hole deeper.",
          effect: { pressure: -0.05, equityMul: 0.96 },
          replyZh: "明早十点。我会把成交单送给您看。",
          replyEn: "Ten o'clock. I will send you the fills.",
          tone: "info",
        },
      ],
    },
    {
      id: "c29-c3",
      day: 5,
      direction: "out",
      fromZh: "六大银行",
      fromEn: "The six largest banks",
      roleZh: "紧急碰头",
      roleEn: "An emergency meeting",
      minDetail: 1,
      lines: [
        { zh: "我们可以凑一个池子入场买。但你要告诉我们买多久。", en: "We can put a pool together and bid. But you have to tell us for how long." },
        { zh: "如果只是买一天，那一天之后卖压还在，我们就成了最后的买家。", en: "If it is only for a day, the selling is still there on day two and we are simply the last buyer." },
      ],
      options: [
        {
          id: "oneday",
          zh: "买一天。把恐慌打断就够了。",
          en: "One day. Breaking the panic is enough.",
          effect: { pressure: -0.16, reserves: -9000, equityMul: 1.07 },
          replyZh: "成交。明天中午我们进场，公开报买。",
          replyEn: "Agreed. Midday tomorrow, and we bid where everyone can see it.",
          tone: "good",
        },
        {
          id: "week",
          zh: "买一周。要做就做到卖压耗完。",
          en: "A week. If we do this we do it until the selling is exhausted.",
          effect: { pressure: -0.26, reserves: -22000, equityMul: 1.05, credibility: 0.08 },
          replyZh: "那池子就这么大了。希望一周够。",
          replyEn: "Then that is the whole pool. Let us hope a week is enough.",
          tone: "info",
        },
        {
          id: "none",
          zh: "不入场。护盘只会让卖的人卖得更从容。",
          en: "No pool. Supporting the market only gives the sellers a better exit.",
          effect: { pressure: 0.05, credibility: 0.12 },
          replyZh: "这话是对的。可惜今天下午没人想听对的话。",
          replyEn: "You are right. Unfortunately nobody wants to hear the right answer this afternoon.",
          tone: "info",
        },
      ],
    },
    {
      id: "c29-c4",
      day: 7,
      direction: "in",
      fromZh: "行情纸带房",
      fromEn: "The ticker room",
      roleZh: "主管",
      roleEn: "Supervisor",
      minDetail: 2,
      lines: [
        { zh: "纸带落后一个半小时。客户看到的价格是一个半小时前的。", en: "The tape is ninety minutes behind. What the customers see happened ninety minutes ago." },
        { zh: "我们要不要干脆停掉报价，等赶上来？", en: "Do we stop quoting altogether until it catches up?" },
      ],
      options: [
        {
          id: "keep",
          zh: "继续报。慢的价格也比没有价格强。",
          en: "Keep printing. A slow price still beats no price.",
          effect: { pressure: 0.03, credibility: 0.06 },
          replyZh: "明白。我们通宵。",
          replyEn: "Understood. We will run all night.",
          tone: "info",
        },
        {
          id: "stop",
          zh: "停。免得他们照着错的价格做决定。",
          en: "Stop it. Better than letting them decide on a wrong price.",
          effect: { pressure: 0.12, equityMul: 0.96, credibility: -0.1 },
          replyZh: "……那他们就照着传言做决定了。",
          replyEn: "…Then they will decide on rumour instead.",
          tone: "bad",
        },
      ],
    },
    {
      id: "c29-c5",
      day: 9,
      direction: "in",
      fromZh: "分行经理",
      fromEn: "A branch manager",
      roleZh: "城郊营业部",
      roleEn: "Suburban office",
      minDetail: 3,
      seats: ["governor", "trader", "retail"],
      lines: [
        { zh: "今天来了一位客户，把房契押在柜台上要补保证金。", en: "A customer came in today and put the deed to his house on the counter to meet a call." },
        { zh: "我该收吗？", en: "Do I take it?" },
      ],
      options: [
        {
          id: "refuse",
          zh: "不收。告诉他强平，然后回家。",
          en: "Do not take it. Tell him to be sold out and go home.",
          effect: { credibility: 0.1, equityMul: 0.99 },
          replyZh: "我会照做。他会恨我，但他还有房子。",
          replyEn: "I will. He will hate me, and he will still have a house.",
          tone: "good",
        },
        {
          id: "take",
          zh: "收。这是他的选择。",
          en: "Take it. It is his decision to make.",
          effect: { pressure: 0.04, credibility: -0.12 },
          replyZh: "……是。我会给他开收据。",
          replyEn: "…Yes. I will write him a receipt.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.6,
      howZh: "你用一成保证金持股。跌 10% 你的本金就没了——不是亏一成，是全部。你唯一的动作是在追缴来之前主动降杠杆。",
      howEn: "You are holding on ten per cent margin. A ten per cent fall does not cost you a tenth, it costs you everything. Your only move is to cut leverage before the call arrives.",
      winZh: "最后一天净值还剩 60% 以上。这一关的通关线比别的低，因为没人能在这场崩盘里全身而退。",
      winEn: "End with 60% of your net worth or more. The bar is lower here than elsewhere, because nobody walked out of this one whole.",
      trapZh: "「跌了这么多，该反弹了」——这句话在 1929 年从 381 点一路说到了 41 点。",
      trapEn: "'It has fallen so far, it must bounce' — in 1929 that sentence was said continuously from 381 all the way to 41.",
    }),
    trader: traderObjective({
      target: 0.2,
      howZh: "你的台子既有自营仓，也有客户的融资盘。真正的风险不在你的仓位，在客户还不上钱的时候谁来还。先把客户的杠杆降下来，再谈赚钱。",
      howEn: "Your desk carries its own book and your clients' margin loans. The real risk is not your position — it is who pays when the client cannot. Cut the clients' leverage first, then talk about making money.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "让追缴自己滚起来",
      titleEn: "Let the calls compound",
      howZh: "你不需要卖很多。你只需要在几个关键的位置把价格压下去，追缴通知会替你卖掉剩下的。",
      howEn: "You do not need to sell much. Push the price through a few levels and the margin clerks will sell the rest for you.",
      winZh: "在最后一天结束前让保证金体系崩掉——追缴无法完成，经纪商开始代客强平。",
      winEn: "Break the margin system before the last day ends: the calls cannot be met and brokers start liquidating for clients.",
      trapZh: "护盘团一入场，短线会被轧。但他们的钱是有限的，而追缴通知是每天发的。",
      trapEn: "The bankers' pool will squeeze you when it bids. Their money is finite; the margin calls go out every night.",
    },
    governor: {
      side: "defend",
      kind: "holdPeg",
      target: 0,
      equityFloor: 42,
      titleZh: "把杠杆拆下来，而不是引爆它",
      titleEn: "Take the leverage down, do not set it off",
      howZh: "你有两张牌，而且都很危险。提高保证金比例只能压住「新增」杠杆——它对已经建好的融资盘毫无作用，却会立刻逼出强平。护盘买入能直接买回压力，但池子有限，而且你一停，卖压还在。这一关的正解是在崩盘之前把比例提上去。",
      howEn: "Two cards, both dangerous. Raising the margin requirement governs new leverage only — it does nothing to the loans already written, and it forces liquidation immediately. Bidding the market buys pressure back directly, but the pool is finite and the selling is still there when you stop. The answer to this scenario is to raise the requirement before the fall, not during it.",
      winZh: "撑满全部交易日、保证金体系不崩，并且收盘时股指仍在 42 以上。",
      winEn: "Last every session with the margin system intact and the index still above 42 at the close.",
      trapZh: "在黑色星期四当天猛提保证金，是把最后一批还能撑住的账户也推下去。这张牌的正确用法在第一天，不在第五天。",
      trapEn: "Slamming the requirement up on Black Thursday pushes the last accounts that could still have held. This card is played on day one, not day five.",
    },
  },
};

export const BLACKMON: Scenario = {
  id: "blackmon",
  kind: "leverage",
  nameZh: "黑色星期一",
  nameEn: "Black Monday",
  year: "1987",
  grade: 5,
  order: 7,
  major: true,
  briefZh:
    "这一次没有坏消息。没有银行倒闭，没有货币贬值，没有人破产。有的只是几百亿美元的资金在用同一套程序做同一件事：价格跌了就卖期指对冲，卖了期指价格更跌，价格更跌就要卖更多。这套东西叫「投资组合保险」，销售的时候说它能保护你。它确实保护了买它的人——代价是市场。周一开盘，机器开始转了。",
  briefEn:
    "There is no bad news this time. No bank failed, no currency devalued, nobody went under. There is only tens of billions of dollars running the same program: when the price falls, sell futures to hedge; selling futures pushes the price down; a lower price means selling more. It is called portfolio insurance and it was sold as protection. It did protect the people who bought it — the market paid for it. Monday opens, and the machine starts turning.",
  historyZh:
    "史实：1987 年 10 月 19 日，道琼斯工业平均指数单日下跌 508 点，跌幅 22.6%，为其历史上最大单日百分比跌幅。当日标普 500 期货一度相对现货大幅贴水，指数套利链条断裂。10 月 20 日上午，多家交易所濒临停市；美联储在开盘前发表了一句话声明，表示「准备好作为流动性来源支持经济与金融体系」。同周多家上市公司宣布回购。1988 年美国推出了熔断机制（Rule 80B）。布雷迪委员会于 1988 年 1 月提交报告，将投资组合保险与指数套利的相互作用列为关键机制。",
  historyEn:
    "History: on 19 October 1987 the Dow Jones Industrial Average fell 508 points, or 22.6% — its largest one-day percentage decline. S&P 500 futures traded at a steep discount to cash and the index arbitrage link broke down. On the morning of 20 October several exchanges came close to halting for good; before the open the Federal Reserve issued a one-sentence statement affirming its 'readiness to serve as a source of liquidity to support the economic and financial system'. Corporate buyback announcements followed that week. Circuit breakers (Rule 80B) were introduced in 1988. The Brady Commission report of January 1988 identified the interaction of portfolio insurance and index arbitrage as a central mechanism.",
  historyDeepZh: [
    "10 月 19 日，纽交所有相当数量的股票因订单失衡而延迟开盘；开盘价本身就是一个断层。",
    "当日期货市场的抛压主要来自少数几家执行组合保险策略的机构；布雷迪报告估计其中三家的卖出量占期货总卖压的很大一部分。",
    "10 月 20 日中午，芝加哥的期货与期权交易所相继暂停交易，现货市场一度失去定价参照。",
    "美联储的声明只有一句话，但它把「谁是最后贷款人」这个问题的答案公开了——银行随后得到指示，继续向证券公司放贷。",
    "标普 500 在 1987 年全年仍录得正回报；崩盘之后的经济衰退并未发生。这一点与 1929 年形成了最刺眼的对照。",
  ],
  historyDeepEn: [
    "On 19 October a substantial number of NYSE stocks were delayed at the open on order imbalances. The opening price was itself a discontinuity.",
    "Selling in the futures market came overwhelmingly from a handful of institutions running portfolio insurance; the Brady report attributed a large share of total futures selling to three of them.",
    "Around midday on 20 October the Chicago futures and options exchanges suspended trading in turn, leaving the cash market briefly without a pricing reference.",
    "The Federal Reserve's statement was a single sentence, but it made the answer to 'who is the lender of last resort' public — banks were then encouraged to keep lending to securities firms.",
    "The S&P 500 still finished 1987 up on the year, and the recession everyone expected did not arrive. That is the sharpest contrast with 1929 there is.",
  ],
  lessonZh:
    "这一战教的是：「流动性不是一个数字，是一个承诺」。1987 年没有基本面坏消息，跌的是市场对「还有没有人接」的信心。把这个信心买回来，不需要花一分钱——需要的是一句所有人都相信的话，和一个能兑现它的资产负债表。这也是为什么这一关的「口头承诺」是真的有用的，而且只有一次。",
  lessonEn:
    "The lesson: liquidity is not a number, it is a promise. Nothing fundamental broke in 1987; what fell was the market's belief that somebody would still be there to take the other side. Buying that belief back does not have to cost anything — it takes one sentence everybody believes, and a balance sheet that could make it good. That is why the public commitment in this scenario genuinely works, and why you only get one.",
  lexicon: {
    ...LEVERAGE_LEXICON,
    lineZh: "做市体系",
    lineEn: "the market-making system",
    gaugeZh: "抛压",
    gaugeEn: "Sell pressure",
    breakZh: "做市商退出。买盘消失，报价断了——不是价格低，是没有价格。",
    breakEn: "The market makers step away. The bid disappears and the quote breaks — not a low price, no price.",
    rateZh: "贴现窗口利率",
    rateEn: "Discount window rate",
    potZh: "流动性额度",
    potEn: "Liquidity facility",
    spendZh: "向做市商与券商注资",
    spendEn: "Fund the dealers",
  },
  seatLabel: {
    governor: { zh: "央行主席", en: "Central bank chair" },
    fund: { zh: "组合保险方", en: "The portfolio insurers" },
    trader: { zh: "指数套利台", en: "Index arbitrage desk" },
    retail: { zh: "共同基金持有人", en: "Mutual fund holder" },
  },
  pegRate: 1,
  band: 0.03,
  reserves: 60_000,
  committedForward: 0,
  startRate: 0.06,
  maxRate: 0.09,
  allowEquityDefence: false,
  allowPledge: true,
  allowHalt: true,
  reserveEfficiency: 0.8,
  // The rate lever barely works here: this is not a crisis about the price of
  // money. It is about whether anyone will quote a price at all.
  rateDefenceCap: 0.3,
  rateDragK: 0.3,
  days: 6,
  historicalOutcome: "held",
  // One sentence before the open on the second morning, and the dealers funded.
  autoDefence: { spend: 0.16, hikeOnDay: 4, pledgeOn: 3 },
  phases: [
    {
      day: 1,
      titleZh: "上周五已经不对了",
      titleEn: "Friday was already wrong",
      bodyZh: "上周五跌了 4%，组合保险的模型按规则挂出了周一的卖单。这些单子在开盘前就已经存在了。",
      bodyEn: "Friday fell four per cent, and the insurance models placed Monday's sell orders by rule. Those orders existed before the market opened.",
      pressure: 0.2,
      equityShock: 0.05,
    },
    {
      day: 2,
      titleZh: "黑色星期一",
      titleEn: "Black Monday",
      bodyZh: "开盘即断层：很多股票因为订单失衡根本开不出来。期指贴水拉到离谱，套利链条断了——现货和期货变成了两个市场。",
      bodyEn: "The open is a discontinuity: many stocks cannot open at all on order imbalances. Futures fall to an absurd discount and the arbitrage link snaps — cash and futures become two different markets.",
      pressure: 0.75,
      equityShock: 0.22,
    },
    {
      day: 3,
      titleZh: "周二上午",
      titleEn: "Tuesday morning",
      bodyZh: "做市商自己也没钱了。银行不肯给券商续贷，因为没人知道券商还值多少钱。期货那边已经暂停交易。",
      bodyEn: "The market makers are out of money themselves. Banks will not roll the dealers' credit because nobody knows what a dealer is worth this morning. The futures floor has already halted.",
      pressure: 0.55,
      equityShock: 0.14,
    },
    {
      day: 4,
      titleZh: "回购公告",
      titleEn: "The buybacks",
      bodyZh: "几十家上市公司同时宣布回购自家股票。这是市场上唯一一批不看价格也要买的人。",
      bodyEn: "Dozens of listed companies announce buybacks at once. They are the only buyers on the board who are not looking at the price.",
      pressure: -0.14,
      minDetail: 1,
    },
    {
      day: 5,
      titleZh: "第二次试探",
      titleEn: "The second test",
      bodyZh: "模型还在跑。只要今天再跌一点，同一批卖单会再出来一遍。",
      bodyEn: "The models are still running. One more down day and the same orders come out again.",
      pressure: 0.3,
      equityShock: 0.08,
      minDetail: 1,
    },
  ],
  calls: [
    {
      id: "bm-c1",
      day: 2,
      direction: "in",
      fromZh: "证券交易所",
      fromEn: "The exchange",
      roleZh: "主席",
      roleEn: "Chairman",
      lines: [
        { zh: "主席先生，我们有三分之一的股票还没开出来，专家做市商的资本在一小时里烧掉了一半。", en: "Mr Chairman — a third of our stocks have not opened and the specialists have burned half their capital in an hour." },
        { zh: "我想停市。您怎么看？", en: "I want to halt. What is your view?" },
      ],
      options: [
        {
          id: "open",
          zh: "别停。停了就没人知道东西值多少钱了。",
          en: "Do not halt. Stop quoting and nobody knows what anything is worth.",
          effect: { pressure: 0.05, credibility: 0.12 },
          replyZh: "那我需要银行继续给我的做市商放贷。您管得了银行吗？",
          replyEn: "Then I need the banks to keep lending to my specialists. Can you deliver the banks?",
          tone: "info",
        },
        {
          id: "halt",
          zh: "停。把这个下午从机器手里拿回来。",
          en: "Halt. Take this afternoon away from the machine.",
          effect: { pressure: -0.18, credibility: -0.18, equityMul: 0.97 },
          replyZh: "停了。明早重开的时候，祈祷有人报价。",
          replyEn: "Halted. Pray there is a bid when we reopen.",
          tone: "info",
        },
      ],
    },
    {
      id: "bm-c2",
      day: 3,
      direction: "out",
      fromZh: "五家清算银行",
      fromEn: "The five clearing banks",
      roleZh: "同时接入的电话会议",
      roleEn: "All on the same line",
      lines: [
        { zh: "主席先生，我们不敢给券商放贷。今天早上没人知道他们的抵押品值多少。", en: "Mr Chairman, we will not lend to the securities firms. Nobody knows what their collateral is worth this morning." },
      ],
      options: [
        {
          id: "backstop",
          zh: "你们放，我在后面。这句话我会公开说。",
          en: "You lend. I am behind you, and I will say so publicly.",
          effect: { pressure: -0.26, equityMul: 1.06, credibility: -0.05 },
          replyZh: "那我们放。请您今天就说出来——我们需要它见报。",
          replyEn: "Then we lend. Say it today, please. We need it in print.",
          tone: "good",
        },
        {
          id: "cash",
          zh: "我给你们流动性，按额度来。",
          en: "I will give you liquidity, against the facility.",
          effect: { pressure: -0.16, reserves: -14000, equityMul: 1.03 },
          replyZh: "收到。额度用完之前我们照放。",
          replyEn: "Received. We lend until the facility is used up.",
          tone: "good",
        },
        {
          id: "none",
          zh: "这是你们的信用判断，不是我的。",
          en: "That is your credit decision, not mine.",
          effect: { pressure: 0.16, equityMul: 0.94 },
          replyZh: "明白。那今天就没有人放贷了。",
          replyEn: "Understood. Then nobody lends today.",
          tone: "bad",
        },
      ],
    },
    {
      id: "bm-c3",
      day: 3,
      direction: "in",
      fromZh: "新闻处",
      fromEn: "The press office",
      roleZh: "发言人",
      roleEn: "Spokesperson",
      minDetail: 1,
      lines: [
        { zh: "开盘前十分钟。您要不要发一份声明？", en: "Ten minutes to the open. Do you want to put out a statement?" },
        { zh: "我草拟了三页。", en: "I have drafted three pages." },
      ],
      options: [
        {
          id: "oneline",
          zh: "一句话。三页纸没人读，一句话所有人都记得。",
          en: "One sentence. Nobody reads three pages; everybody remembers one sentence.",
          effect: { pressure: -0.2, credibility: 0.15, equityMul: 1.04 },
          replyZh: "「准备好作为流动性来源，支持经济与金融体系。」——就这一句？",
          replyEn: "'Ready to serve as a source of liquidity to support the economic and financial system.' Just that?",
          tone: "good",
        },
        {
          id: "threepage",
          zh: "发三页。要说清楚我们的工具和条件。",
          en: "Run the three pages. People should understand the tools and the conditions.",
          effect: { pressure: -0.04, credibility: 0.05 },
          replyZh: "好。不过第二页的条件，市场会读成犹豫。",
          replyEn: "Very well. Though the conditions on page two will read as hesitation.",
          tone: "info",
        },
        {
          id: "silent",
          zh: "不发。央行不评论市场。",
          en: "Nothing. Central banks do not comment on markets.",
          effect: { pressure: 0.14, credibility: -0.08 },
          replyZh: "明白。那今天的头条会由别人来写。",
          replyEn: "Understood. Then somebody else writes today's headline.",
          tone: "bad",
        },
      ],
    },
    {
      id: "bm-c4",
      day: 4,
      direction: "in",
      fromZh: "一家蓝筹公司",
      fromEn: "A blue-chip company",
      roleZh: "首席财务官",
      roleEn: "Chief financial officer",
      minDetail: 2,
      lines: [
        { zh: "我们想宣布回购。但律师说敏感期不能买。", en: "We want to announce a buyback. Our lawyers say we cannot buy in a closed period." },
        { zh: "您能不能让监管给一个临时豁免？", en: "Can you get the regulator to give a temporary waiver?" },
      ],
      options: [
        {
          id: "waive",
          zh: "我去要。今天下午就要到。",
          en: "I will get it. This afternoon.",
          effect: { pressure: -0.12, equityMul: 1.05 },
          replyZh: "那我们开盘就买。谢谢。",
          replyEn: "Then we buy at the open. Thank you.",
          tone: "good",
        },
        {
          id: "no",
          zh: "规则就是规则。危机里改规则，以后每次危机都要改。",
          en: "Rules are rules. Change them in a crisis and you change them in every crisis after.",
          effect: { credibility: 0.1, pressure: 0.04 },
          replyZh: "我理解。那我们只能宣布，不能买。",
          replyEn: "I understand. Then we can announce it and not buy it.",
          tone: "info",
        },
      ],
    },
    {
      id: "bm-c5",
      day: 5,
      direction: "out",
      fromZh: "组合保险策略的销售方",
      fromEn: "The people who sold portfolio insurance",
      roleZh: "合伙人",
      roleEn: "Partner",
      minDetail: 3,
      lines: [
        { zh: "主席先生……我们的模型假设你随时能卖出去。", en: "Mr Chairman… our model assumes you can always sell." },
        { zh: "上周一证明这个假设在最需要它的那一天是不成立的。", en: "Monday proved that assumption fails on precisely the day you need it." },
      ],
      options: [
        {
          id: "stop",
          zh: "今天停掉你们的程序。手动，人来做决定。",
          en: "Switch the program off today. Manual. People make the decisions.",
          effect: { pressure: -0.16, credibility: 0.06 },
          replyZh: "已经关了。我们的客户会不高兴。",
          replyEn: "Already off. Our clients will not be pleased.",
          tone: "good",
        },
        {
          id: "record",
          zh: "把你们的卖出规则全部交给委员会，写进报告里。",
          en: "Hand your selling rules to the commission. All of them, for the report.",
          effect: { credibility: 0.14, pressure: -0.06 },
          replyZh: "……会交。这份报告会让这个行业改掉很多东西。",
          replyEn: "…We will. That report is going to change a great deal in this industry.",
          tone: "good",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.78,
      howZh: "你手上是一只共同基金。这一关最重要的判断是：这次跌是基本面坏了，还是机器在自己转。前者要跑，后者不要。",
      howEn: "You hold a mutual fund. The judgement that matters here is whether something broke or a machine is simply turning. You run from the first. You do not run from the second.",
      trapZh: "1987 年之后一年，指数收正。那一周赎回的人，用最坏的价格换来了最坏的结果。",
      trapEn: "The index finished that year up. Everyone who redeemed that week took the worst price on the board and got the worst outcome from it.",
    }),
    trader: traderObjective({
      target: 0.14,
      howZh: "你在指数套利台。现货和期货之间的价差裂开到了历史级别——问题是，你敢不敢在报价都断了的时候去吃它。",
      howEn: "You run index arbitrage. The basis between cash and futures has blown out to a historic gap — the question is whether you dare take it when the quotes themselves have broken.",
      trapZh: "价差看起来白送，前提是两条腿都能成交。星期一那天，现货那条腿根本开不出来。",
      trapEn: "The spread looks free, provided both legs fill. On Monday the cash leg did not open at all.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "让机器替你卖",
      titleEn: "Let the machine sell for you",
      howZh: "你不用建仓，你只要把价格推到模型的触发线以下。剩下的卖单是别人的程序发出来的，而且免费。",
      howEn: "You do not need a position. You need the price under the models' triggers. The rest of the selling is somebody else's program, and it is free.",
      winZh: "在最后一天结束前让做市体系断掉——买盘消失、报价中断。",
      winEn: "Break the market-making system before the last day ends: no bid, no quote.",
      trapZh: "这一关对面有一张你算不出来的牌：一句话的流动性承诺。它不花钱，而且一旦说出口就会把你的回路掐断。",
      trapEn: "The other side holds a card you cannot price: a one-sentence liquidity commitment. It costs nothing and it cuts your loop the moment it is said.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.65,
      equityFloor: 60,
      titleZh: "把买盘找回来",
      titleEn: "Find the bid",
      howZh: "这一关没有基本面问题，所以利率这张牌几乎没用——跌的不是资产价格，是「还有没有人接」。你真正的牌有三张：给做市商和券商注入流动性、一次公开的流动性承诺、以及要不要停市。停市能立刻掐断回路，但它会把信心一起掐掉，明天要还。",
      howEn: "Nothing fundamental is wrong here, which is why the rate card barely works — what has fallen is not the value of the assets but the belief that somebody will take the other side. Your real cards are three: funding the dealers, one public commitment of liquidity, and whether to halt. A halt cuts the loop instantly and cuts confidence with it, and tomorrow you pay for both.",
      winZh: "撑满全部时段、做市体系不断，收盘时股指在 60 以上，并且抛压回落到 0.65 以下。",
      winEn: "Last every session with the market-making system intact, the index above 60 at the close, and sell pressure back under 0.65.",
      trapZh: "承诺只有一次，而且必须在你还有额度的时候说。额度见底之后再说同样的话，市场会当成求救，压力反而更大。",
      trapEn: "You get one commitment, and it has to be made while the facility behind it is still real. Say the same words with an empty facility and the market hears a distress call, and the pressure goes up instead.",
    },
  },
};

/**
 * 1873: the domino panic. Where 1907 teaches speed, this one teaches triage.
 *
 * There was no pool and no person to run one: the banks were jealous of each
 * other, the biggest private house in the country was allowed to fail on a
 * Thursday, and the exchange closed its doors for the first time in its
 * history — ten days — because the honest thing had been done in order. The
 * player's problem is not liquidity; it is which domino to stand in front of,
 * and the answer has to be the one nobody wants to save.
 */
const PANIC73_LEXICON: Scenario["lexicon"] = {
  lineZh: "清算链条",
  lineEn: "the settlement chain",
  gaugeZh: "传导压力",
  gaugeEn: "Contagion",
  breakZh: "链条断了。交易所落闩，银行互相锁门，票据变成仅限收件人阅读的信。",
  breakEn: "The chain snaps. The exchange bolts its doors, banks lock each other out, and a bill becomes a letter only its holder can read.",
  rateZh: "拆借利率",
  rateEn: "Money rate",
  potZh: "银行联合资金",
  potEn: "Bankers' pool",
  spendZh: "注入联合资金",
  spendEn: "Commit pool money",
  buyZh: "接下问题机构的账簿",
  buyEn: "Take the failing book",
  marketZh: "铁路债与股指",
  marketEn: "Rail bonds and shares",
  shortLineZh: "做空银行股与铁路债",
  shortLineEn: "Short the banks and the rail bonds",
  shortEqZh: "把账簿换成金币",
  shortEqEn: "Turn the book into coin",
};

export const PANIC73: Scenario = {
  id: "panic73",
  kind: "run",
  nameZh: "北线恐慌",
  nameEn: "The Northern Line Panic",
  year: "1873",
  grade: 4,
  order: 5,
  major: false,
  briefZh:
    "战争结束了八年，狮子国的纸面上全是铁路。城中最有名字的商行靠卖战争债券起家，如今把整座金库押在北境铁路的债券上——一条修到一半、只进不出的线。春天，大陆那边先塌了一块：维也纳式的股灾，资金连夜回家。九月，北线的债券卖不动了。商行把最后一枚金币垫了进去，然后拿着账本来找你——清算所的秘书长。你手里没有中央银行，只有一群互相提防的银行家和一笔凑出来的联合资金。而账本上那家商行，是城里三十张清算链条的第一张。",
  briefEn:
    "Eight years after the war, Leo's balance sheets are all railway. The best-known private house in the city made its name selling war bonds and has now staked its entire vault on Northern Line paper — a line half built, paying out and taking nothing in. In the spring the Continent cracks first: a Vienna-style crash, and the money goes home overnight. By September Northern Line bonds cannot be sold at all. The house has put its last coin into them and comes to you — secretary of the clearing house — with its book. You have no central bank. You have a room of bankers who distrust each other and a pool scraped together that morning. And the house in that book stands first in thirty links of the city's settlement chain.",
  historyZh:
    "史实：1873 年 5 月维也纳证券交易所崩盘，中欧投机热潮终结，资金开始回流。美国方面，内战后货币长期宽松，铁路建设过度扩张；杰伊·库克商行（Jay Cooke & Co.）曾以承销内战国债闻名，此时深陷北太平洋铁路债券。1873 年 9 月 18 日（周四），杰伊·库克商行停止兑付；9 月 20 日（「黑色星期四」），纽约证券交易所历史上第一次关闭，停市十天。库克商行倒闭前曾寻求援助而未果。此后数年间数以百计的银行与商行倒闭，铁路建设长期收缩；美国经济陷入长达数年的萧条（史称 Long Depression），失业、通货紧缩与社会动荡延续至 1870 年代末。这一切发生时，美国尚无中央银行。",
  historyEn:
    "History: the Vienna stock exchange crashed in May 1873, ending the Central European boom and pulling money home. In the United States, years of easy post-Civil War money had fed overbuilt railways; Jay Cooke & Co., the house that had made its name placing Union war bonds, was by then deeply committed to Northern Pacific railway paper. On Thursday 18 September 1873 Jay Cooke & Co. suspended payment; on 20 September — Black Thursday — the New York Stock Exchange closed for the first time in its history, for ten days. Attempts to find support for Cooke before the suspension came to nothing. Hundreds of banks and brokerages failed over the following years and railway construction contracted for a decade; the American economy slid into what became known as the Long Depression, with unemployment, deflation and unrest deep into the late 1870s. All of it happened without a central bank.",
  historyDeepZh: [
    "维也纳 1873 年 5 月 9 日「黑色星期五」股灾后，欧洲资本持续撤出美国市场。秋天的大西洋两岸，同一个泡沫在两边漏气。",
    "北太平洋铁路从 1870 年起持续发债，债券滞销后由承销商自己吃下。库克商行实际上用自己的资产负债表垫了一条铁路。",
    "9 月 18 日前，商行曾试图向纽约的银行集团求援；有人愿意有条件出手，但在嫉妒与侥幸之间，会议室最终散了。",
    "交易所关闭的十天里，票据无法交割，账面上的数字冻结成各自的窟窿。重开之后的第一个小时，卖单比前十天加起来还多。",
    "这场恐慌之后，美国国会围绕货币本位争吵了二十年。1890 年代的每一场危机，都是在没有最后贷款人的房间里处理的。",
  ],
  historyDeepEn: [
    "After Vienna's Black Friday of 9 May 1873, European capital kept leaving the American market. By autumn the same bubble was leaking on both shores of the Atlantic at once.",
    "The Northern Pacific had issued bonds continuously from 1870; when they stopped selling, the underwriters took them onto their own books. Cooke's house was, in effect, financing a railway off its own balance sheet.",
    "In the days before 18 September the house sought support from the New York banks; some were willing on terms, but between jealousy and hope the room never agreed.",
    "Through the exchange's ten closed days bills could not clear, and balances froze into whatever hole each man's book already held. In the first hour after reopening, more stock changed hands than in the ten days before.",
    "The panic opened twenty years of argument over the money standard. Every American crisis of the 1890s would be handled in a room with no lender of last resort in it.",
  ],
  lessonZh:
    "这一战教的是：「连锁违约里，你救谁，就是选择链条断在哪」。1907 教的是快和公开；1873 教的是更冷的那一课——池子不够救所有人时，该救的是「最不该救」的那家：最大的、最惯犯的、名声最响的。因为它的对手方名单就是别人的生死簿。当年没人救杰伊·库克，理由完全正当——于是交易所关了十天，萧条续了六年。道德风险是真实的，但它的账单会在第二年才寄到；而多米诺的账单，当天下午就到。",
  lessonEn:
    "The lesson: in a chain of defaults, whoever you save is you choosing where the chain breaks. 1907 taught speed and daylight; 1873 teaches the colder half — when the pool cannot cover everyone, the house to save is the least deserving one: the biggest, the most overreaching, the most famous, because its counterparty list is everybody else's death register. Nobody saved Jay Cooke, for reasons that were entirely sound — and the exchange shut for ten days and the depression ran six years. Moral hazard is real, and its bill arrives next year; the dominoes bill the same afternoon.",
  lexicon: PANIC73_LEXICON,
  seatLabel: {
    governor: { zh: "清算所秘书长", en: "Clearing house secretary" },
    fund: { zh: "做空辛迪加", en: "The bear syndicate" },
    trader: { zh: "铁路债经纪", en: "Rail-bond broker" },
    retail: { zh: "票据持有人", en: "Bill holder" },
  },
  pegRate: 1,
  band: 0.05,
  reserves: 18_000,
  committedForward: 0,
  startRate: 0.07,
  maxRate: 0.22,
  allowEquityDefence: false,
  // The bolt is real here: the exchange did close, and it was the first time.
  allowHalt: true,
  // 1873 has no Morgan: the pool is real money, but there is no one to make
  // it work like one.
  reserveEfficiency: 0.85,
  rateDefenceCap: 0.5,
  rateDragK: 0.14,
  days: 8,
  escalation: 1.6,
  historicalOutcome: "broke",
  outcomeNoteZh:
    "史实结局：防线断了。交易所史上第一次落闩，清算停摆十天，其后是六年的紧缩。这一关守住的玩家，做的事当年没有人做成。",
  outcomeNoteEn:
    "The record: the line broke. The exchange bolted its doors for the first time, settlement stopped for ten days, and six years of contraction followed. A player who holds this one is doing what nobody managed at the time.",
  autoDefence: { spend: 0.12, nudgeOnDay: 4, nudgeTo: 0.15, hikeOnDay: 6 },
  phases: [
    {
      day: 1,
      titleZh: "大陆那边先塌了",
      titleEn: "The Continent cracks first",
      bodyZh: "春天以来的消息到秋天成了事实：维也纳式的股灾之后，大陆的资金在回家。本地市场开了一个低百分之四的盘，没有反弹。",
      bodyEn: "What was rumour in spring is fact by autumn: after the crash over there, Continental money is going home. The local market opens four per cent lower and does not come back.",
      pressure: 0.12,
      equityShock: 0.04,
    },
    {
      day: 2,
      titleZh: "北线卖不动了",
      titleEn: "The Northern Line stops selling",
      bodyZh: "城中最有名字的商行，金库里一捆一捆全是北境铁路的债券。它还在按面值对外报价——按买进的面值。市场上已经没有这个价了。",
      bodyEn: "The best-known house in the city has its vault stacked with Northern Line bonds. It is still marking them at par — the par it paid. No such price exists in the market any more.",
      pressure: 0.16,
      equityShock: 0.04,
    },
    {
      day: 3,
      titleZh: "商行停业",
      titleEn: "The house suspends",
      bodyZh: "周四上午，它挂出停业告示。头一小时没人说话；第二小时，城里每一张对手方名单都被翻了出来。",
      bodyEn: "Thursday morning it posts the suspension notice. For the first hour nobody speaks; in the second hour every counterparty list in the city is out of its drawer.",
      pressure: 0.26,
      equityShock: 0.08,
    },
    {
      day: 4,
      titleZh: "黑色星期四",
      titleEn: "Black Thursday",
      bodyZh: "交易所决定关门——它历史上的第一次。理由很诚实：卖单比钱多，交割做不成。门闩落下的声音全城都听得见。",
      bodyEn: "The exchange votes to close — the first time in its history. The reason is honest: there are more sell orders than money, and delivery cannot be made. The whole city hears the bolt go home.",
      pressure: 0.28,
      equityShock: 0.1,
    },
    {
      day: 5,
      titleZh: "关闭的十天",
      titleEn: "The ten closed days",
      bodyZh: "门闩落着。票据无法交割，账面上的数字冻结成各自的窟窿。安静，但不是健康的安静。",
      bodyEn: "The bolt stays down. Bills cannot clear, and balances freeze into whatever hole each man's book already held. Quiet — not the healthy kind.",
      pressure: 0.12,
      minDetail: 1,
    },
    {
      day: 6,
      titleZh: "重开",
      titleEn: "The reopening",
      bodyZh: "重新开市——第一小时的成交量超过关闭前十天的总和。被冻结的十天没有消化任何卖压，只是把它腌了起来。",
      bodyEn: "It reopens — the first hour trades more than the whole ten days before. The closed days digested nothing; they only salted it.",
      pressure: 0.3,
      equityShock: 0.09,
    },
    {
      day: 7,
      titleZh: "银行互相锁门",
      titleEn: "The banks lock each other out",
      bodyZh: "没有一家银行肯把钱放在另一家过夜。拆借市场名存实亡：报出的利率是真的，借不到钱也是真的。",
      bodyEn: "No bank will leave money in another overnight. The call market exists in name only: the quoted rate is real, and so is the fact that no money moves at it.",
      pressure: 0.34,
      minDetail: 1,
    },
    {
      day: 8,
      titleZh: "长冬",
      titleEn: "The long winter",
      bodyZh: "解雇通知从码头贴到车厂。铁路工地一个接一个安静下来——不是因为决定停工，是因为发不出工资。",
      bodyEn: "The dismissal notices run from the docks to the rail yards. The works fall quiet one by one — not by decision to stop, but by failure to pay.",
      pressure: 0.24,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "p73-c1",
      day: 2,
      direction: "in",
      fromZh: "南桥商行",
      fromEn: "The South Bridge house",
      roleZh: "高级合伙人",
      roleEn: "Senior partner",
      lines: [
        { zh: "秘书长，我把话说透：北线的债券我们吃下了九百万，市面上它们的报价已经不存在了。", en: "Secretary, plainly: we hold nine million of Northern Line paper at a price the market no longer quotes." },
        { zh: "我需要的不是同情，是让清算所把这笔债券按面值收进联合资金，给我们时间。我们的名字在三十家对手方的账上。", en: "I am not asking for sympathy. I am asking the clearing house to take the paper into the pool at par and give us time. Our name sits on the books of thirty counterparties." },
      ],
      options: [
        {
          id: "takeit",
          zh: "收。按面值收进联合资金，条件是账簿今晚公开给全体成员过目。",
          en: "We take it. Into the pool at par, on condition the books are open to every member tonight.",
          effect: { reserves: -2_500, pressure: -0.14, credibility: 0.12 },
          replyZh: "……可以。先生们，账簿在桌上。这比体面更难，但比停业容易。",
          replyEn: "…Agreed. Gentlemen, the books are on the table. It is harder than dignity and easier than suspension.",
          tone: "good",
        },
        {
          id: "rules",
          zh: "规矩就是规矩。债券按市价，市价就是零——明天清算所照常结算，你们自己想办法。",
          en: "The rules are the rules. The bonds are worth the market, and the market is zero — the clearing house settles tomorrow as usual, and your house will find its own way.",
          effect: { pressure: 0.12, credibility: -0.08 },
          replyZh: "明白了。那么明天早上，您会先收到我们的停业通知，然后是其他二十九家的电话。",
          replyEn: "Understood. Then tomorrow morning you will have our suspension first, and twenty-nine phone calls after it.",
          tone: "bad",
        },
      ],
    },
    {
      id: "p73-c2",
      day: 3,
      direction: "out",
      fromZh: "大陆的代理行",
      fromEn: "The Continental agents",
      roleZh: "汇兑",
      roleEn: "Exchange",
      minDetail: 1,
      lines: [
        { zh: "秘书长，维也纳那边问：狮子国的商行体系还完整吗？", en: "Secretary, Vienna is asking: is the Leo house system still intact?" },
        { zh: "怎么回答，决定了明早轮到港的黄金是进来还是出去。", en: "Whatever we answer decides whether tomorrow's gold comes in at the port or goes out." },
      ],
      options: [
        {
          id: "truthful",
          zh: "如实答：一家商行在清算，其余三十家今天照常结算，数字明早见报。把结算数据一起发过去。",
          en: "Answer it straight: one house is settling, the other thirty settled today as usual, figures in the morning papers. Send the settlement data with it.",
          effect: { credibility: 0.14, pressure: 0.04 },
          replyZh: "数据比形容词有用。他们会核对，然后发现这是这个月欧洲收到过的最好的一份报表。",
          replyEn: "Data is more use than adjectives. They will check it and find it the best statement Europe has received this month.",
          tone: "good",
        },
        {
          id: "bluff",
          zh: "告诉他们一切安好，无需多问。",
          en: "Tell them all is well and there is nothing to ask.",
          effect: { credibility: -0.12 },
          replyZh: "……他们最擅长发现的，就是别人不想让他们问的事。",
          replyEn: "…What they are best at discovering is whatever nobody wants them to ask about.",
          tone: "bad",
        },
      ],
    },
    {
      id: "p73-c3",
      day: 4,
      direction: "in",
      fromZh: "交易所主席",
      fromEn: "The exchange president",
      roleZh: "理事会",
      roleEn: "The governors",
      lines: [
        { zh: "秘书长，理事会在里面等答案：明早开门，还是落闩？", en: "Secretary, the governors are inside waiting on one answer: do we open in the morning, or do we bolt the door?" },
        { zh: "门外是三天攒下来的卖单。门闩挡得住今天，挡不住它们。", en: "Outside are three days of sell orders. The bolt holds back today; it does not hold them back." },
      ],
      options: [
        {
          id: "open",
          zh: "开门。联合资金全部顶在开盘前的拆借市场上，利率上不封顶。让想卖的人今天卖完。",
          en: "We open. The whole pool goes under the call market before the bell, no cap on the rate. Whoever needs to sell sells today.",
          effect: { pressure: -0.12, reserves: -1_800 },
          replyZh: "这会很贵。——比十天便宜。开门。",
          replyEn: "This will be expensive. — Cheaper than ten days. We open.",
          tone: "good",
        },
        {
          id: "close",
          zh: "落闩。市场需要喘口气。",
          en: "Bolt it. The market needs air.",
          effect: { pressure: -0.18, credibility: -0.15 },
          replyZh: "那就闩上。记住今天这句「需要喘口气」——重开那天，它会被行情表引用。",
          replyEn: "Then bolt it. And remember today's phrase 'needs air' — the reopening tape will quote it back.",
          tone: "bad",
        },
      ],
    },
    {
      id: "p73-c4",
      day: 6,
      direction: "in",
      fromZh: "城里储蓄银行",
      fromEn: "The savings banks",
      roleZh: "储户柜台",
      roleEn: "The deposit counters",
      minDetail: 2,
      lines: [
        { zh: "秘书长，柜台开始排队了。储户问的问题只有一个：我们的钱和南桥商行有关系吗？", en: "Secretary, the counters are queueing. The depositors ask one question: is our money anywhere near the South Bridge house?" },
        { zh: "第二个问题没人问出口：清算所保的是支票，不是我们的存款。", en: "The second question nobody says out loud: the clearing house guarantees cheques, not our deposits." },
      ],
      options: [
        {
          id: "publish",
          zh: "今晚公布每一家成员行对商行的敞口数字，包括零。让他们自己看见大多数是零。",
          en: "Publish every member's exposure to the house tonight, zeros included. Let them see for themselves how many are zeros.",
          effect: { credibility: 0.15, pressure: 0.05 },
          replyZh: "零也是数字。印出来。……明天柜台会短一半。",
          replyEn: "Zero is a figure too. Print it. — The counters will be half as long tomorrow.",
          tone: "good",
        },
        {
          id: "soothe",
          zh: "发一份安民公告：体系稳健，无需担心，细节不便披露。",
          en: "Put out a notice: the system is sound, no cause for concern, details not convenient to disclose.",
          effect: { credibility: -0.14, pressure: -0.05 },
          replyZh: "「不便披露」。这四个字明天会出现在每一条队伍的交谈里。",
          replyEn: "'Not convenient to disclose.' Four words that will be in every conversation in every queue tomorrow.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.7,
      howZh: "你持有商行承兑的票据。在 1873 年，判断一家机构倒不倒的唯一办法是看它对手方的脸色——那是公开的，比报表诚实。",
      howEn: "You hold bills the house has accepted. In 1873 the only way to tell whether an institution falls is the look on its counterparties' faces — that is public, and more honest than a balance sheet.",
      trapZh: "票据贴现率每跳一格，都是市场在重新定价那家商行。等到贴现被拒，你的票据就不是资产了，是纪念品。",
      trapEn: "Every tick of the discount on those bills is the market repricing the house. When the discount is refused outright, your bill stops being an asset and becomes a souvenir.",
    }),
    trader: traderObjective({
      target: 0.2,
      howZh: "你做铁路债经纪。行情好的年代，这门生意赚点差价；这一年，赚的是别人不敢接的货——前提是你算得出哪家清算所成员下周还在。",
      howEn: "You deal rail bonds. In good years the trade pays a spread; this year it pays for taking what nobody dares touch — provided you can work out which clearing members still exist next week.",
      trapZh: "别接南桥商行背书的任何票据——它倒下那天，票据还在，背书没了。",
      trapEn: "Do not take paper the South Bridge house has endorsed — on the day it falls, the paper survives and the endorsement does not.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "让链条自己断",
      titleEn: "Let the chain break itself",
      howZh: "你的仓位几乎不用动。做空两家互相持有对方票据的银行，然后在它们的对手方面前谈论第三家的报表——剩下的，嫉妒和恐惧会替你完成。",
      howEn: "You barely need to trade. Short two banks that hold each other's paper, then discuss a third bank's statements in front of its counterparties — envy and fear will finish the rest for you.",
      winZh: "在最后一天结束前让清算链条断掉——交易所落闩，或成员大面积停业。",
      winEn: "Break the settlement chain before the last day ends: the exchange bolted, or the members down in numbers.",
      trapZh: "1873 年的清算所有一张牌是 1907 没有的：关门。它关上门的那天，你的空头什么也兑现不了——十天后重开，行情会把账连本带利还你。",
      trapEn: "The clearing house of 1873 holds one card 1907 never had: the bolt. The day it shuts the doors your shorts settle against nothing — and ten days later the reopening tape repays you in full with interest.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.6,
      equityFloor: 55,
      titleZh: "站在第一张多米诺前面",
      titleEn: "Stand in front of the first domino",
      howZh: "你的池子救不了所有人，所以第一个决定比之后所有决定加起来都重：商行来求救的那天，救它——不是因为它值得，是因为它的对手方名单最厚。然后是纪律：开门别关门、公开别安抚。停市在这一关是真实的诱惑，也是真实的陷阱——被推迟的卖压带着利息回来。",
      howEn: "The pool cannot cover everyone, so the first decision outweighs every later one together: the day the house comes asking, save it — not because it deserves saving, but because its counterparty list is the thickest in the city. Then discipline: doors open, facts public. The halt is a real temptation here and a real trap — the selling it defers comes back with interest.",
      winZh: "撑满全部交易日、清算链条不断，收盘时股指在 55 以上，传导压力回落到 0.6 以下。",
      winEn: "Last every session with the chain intact, the index above 55 at the close, and contagion back under 0.6.",
      trapZh: "「让最贪婪的先死」在别的关是对的，在这一关是通关的反义词：1873 年死掉的那家最贪婪的，身后压着三十家。它停业的周四下午，你的池子救谁都不够了。",
      trapEn: "'Let the most reckless die first' is right in other scenarios and the opposite of the answer here: the most reckless house that died in 1873 had thirty others under it. By the Thursday afternoon it suspended, the pool could not cover anybody.",
    },
  },
};

/**
 * 1890: the list. The third of the nineteenth-century runs, and the first
 * that was won — not with more money than 1873, but with a night of
 * organisation and a sentence that happened to be true.
 *
 * Where 1907 has no central bank and 1873 has no organiser, here there is a
 * central bank whose real power is the telephone: a governor who spends the
 * weekend locking bankers in a room until a guarantee fund exists with every
 * name on it, then says out loud that it exists. The pool is real; that is
 * why the sentence works. The lesson is that the pool and the sentence are
 * two halves of one instrument.
 */
const BARING_LEXICON: Scenario["lexicon"] = {
  lineZh: "商行兑付",
  lineEn: "the house's acceptance book",
  gaugeZh: "兑付压力",
  gaugeEn: "Payment pressure",
  breakZh: "商行停业。它的票据停转，而全城每一份进出口押汇都经过它。",
  breakEn: "The house suspends. Its bills stop circulating, and half the city's trade paper runs through it.",
  rateZh: "贴现率",
  rateEn: "Discount rate",
  potZh: "担保基金",
  potEn: "The guarantee fund",
  spendZh: "动用担保基金",
  spendEn: "Draw the fund",
  buyZh: "收购南原债券",
  buyEn: "Buy the Plate bonds",
  marketZh: "银行股与票据",
  marketEn: "Bank shares and bills",
  shortLineZh: "做空商行票据",
  shortLineEn: "Short the house's bills",
  shortEqZh: "把账簿换成黄金",
  shortEqEn: "Turn the book into gold",
};

export const BARING: Scenario = {
  id: "baring",
  kind: "run",
  nameZh: "十一月的名单",
  nameEn: "The November List",
  year: "1890",
  grade: 5,
  order: 9,
  major: false,
  briefZh:
    "狮子国最老牌的商行在南原共和国押错了年代：一个国家的公债、一座城市的供排水工程、一片草原的抵押贷款，全都经它的手。夏天，南原革命了，债不还了。十一月的一个周六，商行的资深合伙人敲开中央银行的后门：下周五，我们有一笔票据要兑付，账上没有这笔钱。资能抵债——资产是有的，只是都在五年后才到期。你——中央银行的行长——翻遍了法律：你无权直接借钱给它，也没有那么多黄金。你有的东西比钱更管用：一个周末，一间会议室，和一部电话。",
  briefEn:
    "Leo's oldest house has misread a decade: a republic's sovereign bonds, one city's waterworks, a mortgage on half a grassland — all of it through their books. In the summer the republic revolts and the debt stops paying. On a Saturday in November the house's senior partner knocks at the central bank's back door: on Friday a tranche of our acceptances falls due, and the money is not there. Solvent — the assets exist — only they all mature in five years. You, the central bank governor, go through the law line by line: you may not lend to them directly, and the gold is not there anyway. What you have is better than money: one weekend, one meeting room, and a telephone.",
  historyZh:
    "史实：巴林兄弟银行（Barings）深度参与阿根廷融资。1890 年阿根廷爆发革命并事实上违约，巴林持有的阿根廷债券与相关资产随之冻结。1890 年 11 月 8 日（周六），巴林向英格兰银行披露其无力兑付即将到期的票据。行长威廉·利德代尔拒绝了「让巴林倒闭」的选项，转而在周末逐家登门组织私人银团担保：由罗斯柴尔德等行牵头，最终约 1,700 万英镑的担保基金成立，认缴名单由各家银行签署；英格兰银行同时从俄国借入约 660 万英镑黄金以稳住储备，并上调贴现率。11 月 15 日消息公布后，挤兑未起，市场企稳。巴林进入清算重组，商号存续经营。与 1873 年的无人组织相对照，1890 年被视为「最后贷款人」机制的教科书一课；「太大而不能倒」的争论由此埋下伏笔。",
  historyEn:
    "History: Barings was deeply committed to Argentine finance. In 1890 revolution swept Argentina into de facto default, freezing the bonds and assets Barings held. On Saturday 8 November 1890 the house disclosed to the Bank of England that it could not meet its forthcoming acceptances. Governor William Lidderdale declined the option of letting the house fail and spent the weekend organising a private guarantee fund instead: led by Rothschild's, some £17m of guarantees was ultimately subscribed with the banks' names on the list. The Bank borrowed roughly £6.6m in gold from Russia to steady its reserve and raised its discount rate. When the arrangement was announced on 15 November no run materialised and the market settled. Barings went into liquidation and reconstruction, and the name carried on trading. Set against the disorganisation of 1873, 1890 became the textbook lesson in the lender of last resort — and quietly founded the debate about who is too big to fail.",
  historyDeepZh: [
    "巴林的坏账大部分不在证券上，在「流动的承诺」上：承兑票据。这些票据背书的是全城的进出口贸易——这就是「一家商行的账」变成「全城的问题」的原因。",
    "利德代尔的周末是这样过的：周六听资产负债表，周日下午逐家登门，周一凌晨两点拿到最后一家拒签行的一个电话。名单凑齐时离开盘还有六个小时。",
    "担保基金的结构是 1890 年的巧思：不是央行出资，而是私人银团认缴、央行背书。钱和信用各出一半。",
    "从俄国借入的黄金用专列运抵伦敦。在没有最后贷款人法条的时代，黄金的物理位置本身就是货币政策。",
    "巴林重组后继续经营了一百多年，直到 1995 年被一名交易员在新加坡的衍生品账簿再次终结——上一次被名单救回的商行，这一次没有等到名单。",
  ],
  historyDeepEn: [
    "Most of Barings' trouble sat not in securities but in circulating promises: acceptances. Those bills endorsed the city's import and export trade — which is how one house's book becomes the whole city's problem.",
    "Lidderdale's weekend ran: the balance sheet on Saturday, door to door on Sunday afternoon, and the last reluctant signature telephoned in at two on Monday morning. The list closed six hours before the opening bell.",
    "The fund's structure was the century's neat trick: not central-bank money but a private syndicate's subscriptions with the Bank behind them. Half cash, half credibility.",
    "The Russian gold came by special train. In an age with no statute for lenders of last resort, the physical location of gold was itself monetary policy.",
    "Reconstructed, Barings traded on for more than a century — until 1995, when one trader's derivatives book in Singapore ended it a second time. The house the list had saved was, that time, too far gone to wait for one.",
  ],
  lessonZh:
    "这一战教的是：「最后贷款人的一半是钱，另一半是把名单排好的那一夜」。1890 年的英格兰银行没有印钱救巴林，它做的事是：一个周末把全城的银行锁进一间会议室，直到一笔担保基金的名单凑齐；然后用一句话把名单变成信用——「商行的负债有银团全额担保」。这句话之所以有用，是因为它碰巧是真的。对照 1873：同样的坏账规模，无人组织的一年萧条，有人组织的一个周末。危机处理里最贵的资产不是黄金，是提前一晚排好的名单。",
  lessonEn:
    "The lesson: half of the lender of last resort is money; the other half is the night spent getting the list right. The Bank of England in 1890 did not print its way to Barings' rescue. What it did was lock the city's bankers in one room for a weekend until a guarantee fund existed with every name signed, and then turned the list into credit with one sentence: the house's liabilities are guaranteed in full. The sentence worked because it happened to be true. Set it against 1873: the same weight of bad paper, six years of depression when nobody organised, one weekend when somebody did. In a crisis the most expensive asset is not gold — it is a list finished the night before.",
  lexicon: BARING_LEXICON,
  seatLabel: {
    governor: { zh: "中央银行行长", en: "Central bank governor" },
    fund: { zh: "北风基金", en: "Northwind Capital" },
    trader: { zh: "银团成员行交易台", en: "Syndicate bank desk" },
    retail: { zh: "票据商人", en: "Bill merchant" },
  },
  pegRate: 1,
  band: 0.05,
  reserves: 17_000,
  committedForward: 0,
  startRate: 0.06,
  maxRate: 0.28,
  allowEquityDefence: false,
  allowPledge: true,
  allowHalt: false,
  // Real subscriptions, a central bank behind them, and gold on a train: this
  // pool works better than 1907's scrap-together, and nowhere near as well as
  // a cheque from the future.
  reserveEfficiency: 1.35,
  rateDefenceCap: 0.5,
  rateDragK: 0.1,
  // The November 15th announcement, with a real fund standing behind it.
  pledgeRelief: 0.12,
  days: 7,
  escalation: 1.4,
  historicalOutcome: "held",
  outcomeNoteZh:
    "史实结局：防线守住了。没有银行倒闭，票据照常兑付。代价由认缴的银团和随后几年的缓慢增长分摊——以及一桩从此改名为「太大而不能倒」的问题。",
  outcomeNoteEn:
    "The record: the line held. No bank failed and the bills were met. The cost was shared out among the subscribers and the slow years that followed — along with a question that has traded under the name 'too big to fail' ever since.",
  autoDefence: { spend: 0.2, nudgeOnDay: 2, nudgeTo: 0.12, hikeOnDay: 4, pledgeOn: 5 },
  phases: [
    {
      day: 1,
      titleZh: "南原不还了",
      titleEn: "The Plate stops paying",
      bodyZh: "夏天的革命到秋天成了定局：南原共和国的公债不再付息。它在这座城里的敞口，八成经过一家商行的账。",
      bodyEn: "Summer's revolution is autumn's fact: the republic's bonds have stopped paying. Eight parts in ten of that exposure, in this city, run through one house's book.",
      pressure: 0.14,
      equityShock: 0.05,
    },
    {
      day: 2,
      titleZh: "周六的后门",
      titleEn: "The Saturday knock",
      bodyZh: "资深合伙人来了，帽子拿在手里。数字摆上桌：周五到期的票据，账上没有钱。资产有——都在五年后。他问的不是救不救，是找谁。",
      bodyEn: "The senior partner arrives with his hat in his hand. The figures go on the table: Friday's acceptances, no money to meet them. The assets exist — in five years. His question is not whether, but whom to see.",
      pressure: 0.3,
      equityShock: 0.06,
    },
    {
      day: 3,
      titleZh: "名单",
      titleEn: "The list",
      bodyZh: "一整天，你在城里挨家敲门。大多数签了；有一家把笔放下了两次。名单每长一个名字，周五的可能性就大一分。",
      bodyEn: "A whole day of doors across the city. Most sign; one puts the pen down twice. Every name the list gains, Friday becomes a little more possible.",
      pressure: 0.22,
      minDetail: 1,
    },
    {
      day: 4,
      titleZh: "柜台的队伍",
      titleEn: "The counter queues",
      bodyZh: "和商行同名的那半座城开始紧张。票据贴现被问了三遍。这是蔓延的第一小时——名单还没公布。",
      bodyEn: "The half of the city that shares the house's name begins to worry. The discount on its paper is asked after three times. This is contagion's first hour — and the list is still unpublished.",
      pressure: 0.3,
      equityShock: 0.08,
    },
    {
      day: 5,
      titleZh: "公告前夜",
      titleEn: "The night before",
      bodyZh: "名单凑齐了，字都签了。可市场不知道。这是最黑的一夜：明早的报纸印出来之前，你手里唯一的东西是一叠有签名的纸。",
      bodyEn: "The list is complete and every signature is on it. The market does not know. This is the blackest night: until the morning papers print, all you hold is a stack of signed paper.",
      pressure: 0.26,
      equityShock: 0.05,
    },
    {
      day: 6,
      titleZh: "黄金在海上",
      titleEn: "Gold on the water",
      bodyZh: "邻国的借款装船了，专列在码头等。储备薄得发亮——现在全城的空头都知道这件事。公告有了，黄金还要两天。",
      bodyEn: "The neighbour's loan is on the water and a special train waits at the dock. The reserve is polished thin — and every bear in the city knows it. The announcement is out; the gold is two days away.",
      pressure: 0.28,
      minDetail: 1,
    },
    {
      day: 7,
      titleZh: "周五之后",
      titleEn: "After Friday",
      bodyZh: "票据如期兑付。队伍散了，贴现回来了。报纸开始争论下一件事：下一次，名单还应该排吗？",
      bodyEn: "The bills were met in full. The queues drain away and the discount comes back. The papers move on to the next argument: next time, should the list be drawn at all?",
      pressure: 0.2,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "ba-c1",
      day: 2,
      direction: "in",
      fromZh: "橡树商行",
      fromEn: "The Oak House",
      roleZh: "资深合伙人",
      roleEn: "Senior partner",
      lines: [
        { zh: "行长，账目您都看过了。我们资能抵债——差的只是五年的时间，和这个周五。", en: "Governor, you have seen the books. We are solvent — what is short is five years, and this Friday." },
        { zh: "「让它倒」三个字您说得出口，我们听得进去。但请先看一眼对面那页：全城的押汇票据，多少家签着我们的名字。", en: "You could say 'let it fall' and we would hear it. But look at the facing page first: the city's trade acceptances, and how many carry our name." },
      ],
      options: [
        {
          id: "list",
          zh: "周五之前，我组织私人银团担保你们的全部兑付。作为条件：账簿今晚起对我完全开放，清算重组照办，合伙人资本金先赔。",
          en: "Before Friday I organise a private syndicate to guarantee your acceptances in full. The terms: your books open to me from tonight, liquidation and reconstruction proceed, and the partners' capital is lost first.",
          effect: { pressure: -0.16, credibility: 0.12, reserves: -1_200 },
          replyZh: "同意。全部条件。请让名单上有几行是体面的名字——星期五见，行长。",
          replyEn: "Agreed. All of it. See that the list carries some respectable names — until Friday, Governor.",
          tone: "good",
        },
        {
          id: "market",
          zh: "商行的事由市场解决。清算所在，贴现窗开着，仅此而已。",
          en: "The market settles the market's houses. The clearing house stands and the window is open. That is all.",
          effect: { pressure: 0.14, credibility: -0.06 },
          replyZh: "明白。那么请留意周一的报价——不是我们的，是全城的。",
          replyEn: "Understood. Then watch Monday's quotations — not ours, the city's.",
          tone: "bad",
        },
      ],
    },
    {
      id: "ba-c2",
      day: 3,
      direction: "in",
      fromZh: "拒签的那家银行",
      fromEn: "The bank that will not sign",
      roleZh: "董事长",
      roleEn: "Chairman",
      minDetail: 1,
      lines: [
        { zh: "行长，说清楚：凭什么我们出钱，保住他们三十年的红利记录？", en: "Governor, plainly: why does my bank pay to preserve thirty years of somebody else's dividend record?" },
        { zh: "他们赚钱的时候，可没分给我们。", en: "When they were making it, none of it came our way." },
      ],
      options: [
        {
          id: "explain",
          zh: "你不保他们的红利，你保你自己的贴现簿。他们倒下那天，你账上每一张经他们的票据都要单独审。名单不是慈善，是分摊清算成本最便宜的方式。",
          en: "You are not preserving their dividends, you are preserving your own discount book. The day they fall, every bill of theirs on your ledger gets individually examined. The list is not charity — it is the cheapest way anybody has found to share the cost of a liquidation.",
          effect: { credibility: 0.14, reserves: -400 },
          replyZh: "……把笔给我。但记录在案：我是为了自己的贴现簿签的。",
          replyEn: "…Give me the pen. Minuted, though: I sign for my own discount book.",
          tone: "good",
        },
        {
          id: "threaten",
          zh: "记住了：明年牌照换发的时候，行长的记性很好。",
          en: "Remember: licences come up for renewal, and the governor's memory is long.",
          effect: { credibility: -0.1 },
          replyZh: "那我把名字划掉。您可以用记性去找别人补上这个数。",
          replyEn: "Then strike my name. Your memory can find the balance somewhere else.",
          tone: "bad",
        },
      ],
    },
    {
      id: "ba-c3",
      day: 4,
      direction: "out",
      fromZh: "邻国中央银行",
      fromEn: "The neighbour's central bank",
      roleZh: "储备库",
      roleEn: "The reserve vaults",
      minDetail: 1,
      lines: [
        { zh: "行长阁下，黄金可以出借，专列周四发车。两个条件：固定利息，和政治上的一个人情。", en: "Governor, the gold can be lent; the train leaves Thursday. Two conditions: a fixed rate of interest, and a political favour owed." },
        { zh: "您确定要让这个国家欠下第二笔债吗？一笔在账上，一笔在账外。", en: "Are you certain you want this country to owe two debts — one on the books and one beside them?" },
      ],
      options: [
        {
          id: "borrow",
          zh: "借。账外的那笔我来背——让黄金周五前到码头。",
          en: "We borrow. The off-books debt is mine to carry — have the gold at the dock before Friday.",
          effect: { reserves: 2_500, credibility: -0.05 },
          replyZh: "周四发车。愿您的名单配得上这列车黄金。",
          replyEn: "The train goes Thursday. May your list prove worthy of the gold in it.",
          tone: "info",
        },
        {
          id: "decline",
          zh: "不借。储备撑得住这个周末——应该撑得住。",
          en: "No. The reserve will carry the weekend — it should carry the weekend.",
          effect: { credibility: 0.05 },
          replyZh: "「应该」是一个很贵的词，行长阁下。专列原地待命。",
          replyEn: "'Should' is an expensive word, Governor. The train will stand by.",
          tone: "info",
        },
      ],
    },
    {
      id: "ba-c4",
      day: 6,
      direction: "in",
      fromZh: "晨报主编",
      fromEn: "Editor, the morning paper",
      roleZh: "头版",
      roleEn: "The front page",
      minDetail: 2,
      lines: [
        { zh: "行长，头版明晚开印。两个标题都排好了：「危机平息」和「救助开始」。", en: "Governor, the front page goes to press tomorrow night. Both headlines are set: 'The crisis is over' and 'The rescues begin'." },
        { zh: "您要哪一个？——或者，您要哪一个先出现？", en: "Which one do you want? — Or perhaps: which one do you want first?" },
      ],
      options: [
        {
          id: "truth",
          zh: "用第一个，正文全文刊出担保名单和金额。读者自己会算出第二个标题是不是更准确——让它出现在社论版，不是头版。",
          en: "The first, with the guarantee list and the sums printed in full below it. The readers can work out for themselves whether the second headline is the truer one — let it run on the leader page, not the front.",
          effect: { credibility: 0.15, pressure: -0.05 },
          replyZh: "数字上头版，形容词进社论。这是今天我听到的最像行长的话。",
          replyEn: "Figures on the front page, adjectives in the leader. That is the most governor-like sentence I have heard today.",
          tone: "good",
        },
        {
          id: "gloss",
          zh: "「危机平息」，名单就不必刊了——细节会吓着人。",
          en: "'The crisis is over', and let the list stay unprinted — details frighten people.",
          effect: { credibility: -0.12, pressure: -0.08 },
          replyZh: "那明天的报纸就是您担保的。行长的信用可撑不起头版，行长要想清楚。",
          replyEn: "Then tomorrow's paper carries your guarantee instead of mine. A governor's credit does not stretch to a front page — think carefully.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.75,
      titleZh: "别在公告前夜折价卖出",
      titleEn: "Do not sell at the worst discount",
      howZh: "你持有商行承兑的票据。它倒，你的票据要等清算；它活，票据如数兑付。判断的依据只有一个：担保名单上的名字够不够重——名单不公开的时候，看谁在深夜被登门拜访。",
      howEn: "You hold the house's acceptances. If it falls, your bills wait in the liquidation; if it stands, they pay in full. There is one basis for the judgement: whether the names on the guarantee list are heavy enough — and while the list is still private, you watch whose door is knocked on after midnight.",
      winZh: "最后一天净值还剩 75% 以上。",
      winEn: "End the last day with 75% of your net worth or more.",
      trapZh: "周五之前把票据折价三成脱手的人，周一醒来会同时看到两个数字：自己的卖价，和公告上的兑付价。",
      trapEn: "Whoever sells the paper at thirty off before Friday wakes Monday to two numbers side by side: the price they took, and the price the announcement paid.",
    }),
    trader: traderObjective({
      target: 0.18,
      howZh: "你在银团成员行的交易台。恐慌的票据在折价卖——如果你的行在名单上，那批纸最终会如数兑付；这个差价就是付给你「读名单」的能力的。",
      howEn: "You sit on a syndicate bank's desk. Frightened paper is selling at a discount — and if your bank is on the list, that paper pays in full in the end. The spread is what the market pays for being able to read a list.",
      trapZh: "接单之前先确认一件事：你的行在名单上。不在的话，你买的不是折价，是清算顺位。",
      trapEn: "Confirm one thing before you bid: that your bank is on the list. If it is not, you are not buying a discount, you are buying a place in the queue.",
    }),
    fund: {
      side: "attack",
      kind: "profit",
      target: 0.35,
      titleZh: "赌名单凑不齐",
      titleEn: "Bet the list falls short",
      howZh: "你做空商行票据和银行股。你的对手不是商行的资产负债表——它资能抵债——是行长能不能在一个周末之内，让一群互相看不顺眼的银行签下同一张纸。历史说这一次他做到了。你的工作是让「这一次」不一样。",
      howEn: "You are short the house's paper and the banks' shares. Your opponent is not the house's balance sheet — it is solvent — but whether one governor can get a room of bankers who despise each other to sign the same sheet inside a weekend. History says this once, he managed it. Your job is to make 'this once' different.",
      winZh: "最后一天自己的账面收益 ≥ +35%。",
      winEn: "Finish the last day up 35% or more on your own book.",
      trapZh: "你的真正对手是那句话公布的那天。有真池子背书的公告会一夜之间抹掉你两周的浮盈——出仓要在公告前。",
      trapEn: "Your real opponent is the day the sentence is published. An announcement with a real fund behind it erases a fortnight of profit overnight — you are out before the papers print.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.5,
      equityFloor: 60,
      titleZh: "在开盘前把名单排完",
      titleEn: "Finish the list before the bell",
      howZh: "你的牌面比 1873 好，但打法更细。池子要早动——商行开口的那天就启动担保，晚一天，贴现簿上就多一批折价成交。公告只有一次，必须在池子还厚的时候说：一句有真金背书的话值三分之一个市场。贴现率别舍不得——它挡的是黄金外流，不是兑付。最贵的时间是公告前夜：那几个小时里，名单是你唯一的储备。",
      howEn: "Your cards are better than 1873's, but the play is finer. Move the pool early — start the guarantee the day the house speaks, because every day of delay is another tranche sold at a discount. The announcement comes once, and it must be said while the fund is still thick: one sentence with real gold behind it is worth a third of a market. Do not begrudge the discount rate — it holds back the gold, not the payments. The dearest hours are the night before publication: for those hours, the list is the only reserve you have.",
      winZh: "撑满全部交易日、商行照常兑付，收盘时股指在 60 以上，兑付压力回落到 0.5 以下。",
      winEn: "Last every session with the house paying as due, the index above 60 at the close, and payment pressure back under 0.5.",
      trapZh: "最像自杀的选项有两个：等市场自己解决（1873 的剧本），和把池子在头两天一次花光再空口公告。前者输在周五，后者输在那句话上——空着口袋说的话，市场听见的是求救。",
      trapEn: "The two ways to lose look nothing alike: waiting for the market to settle it (the 1873 script), and emptying the pool in the first two days then announcing with nothing behind the words. The first loses on Friday; the second loses on the sentence — said with an empty pocket, the market hears a distress call.",
    },
  },
};
