import type { Scenario } from "../types.ts";
import { PEG_LEXICON, retailObjective, traderObjective } from "./seats.ts";

/**
 * The three currency defences.
 *
 * Two the defender loses, one they win — and the difference between them is
 * most of the curriculum. The `history` field on each is fact: real dates,
 * real figures, stated conservatively. The playable side is the Leo world's
 * retelling, with a fictional fund holding the short.
 *
 * Their numbers are TUNED and pinned by `story.test.ts`. The Hong Kong
 * scenario in particular took several passes to stop being mathematically
 * unwinnable. Read §3.3 of HANDOFF.md before touching a coefficient here.
 */

export const BAHT: Scenario = {
  id: "baht",
  kind: "peg",
  nameZh: "拉莫娜币保卫战",
  nameEn: "The Ramona Defence",
  year: "1997",
  grade: 3,
  order: 4,
  major: true,
  briefZh:
    "拉莫娜国把本币钉在一篮子外币上，钉了十几年，钉出了信心，也钉出了习惯——企业借外债不做对冲，因为「汇率不会动」。房地产盖到了郊外，财务公司的坏账没人细看。春天开始，北风基金在远期市场上一点一点建空头。央行行长说：我们有三百亿储备。他没有说的是，其中大部分已经在远期合约里许出去了。",
  briefEn:
    "Ramona had pegged its currency to a basket for over a decade — long enough to create confidence, and habits: companies borrowed in foreign currency without hedging, because the rate 'does not move'. Property reached the outer suburbs; nobody looked too closely at the finance companies' books. From spring, Northwind built its short in the forwards market. The governor said: we hold thirty billion in reserves. What he did not say was how much of it was already promised away.",
  historyZh:
    "史实：泰铢自 1984 年起钉住以美元为主的一篮子货币，约 25 铢兑 1 美元。1997 年上半年，泰国央行动用即期储备与远期合约防守，到 7 月 2 日宣布浮动时，其远期承诺规模约 230 亿美元，而账面储备约 300 亿美元——可动用的部分已所剩无几。浮动当日泰铢贬值约 20%，到 1998 年初累计贬值超过一半。8 月泰国向 IMF 求援，获得约 170 亿美元一揽子方案。这场危机随后蔓延为亚洲金融危机。",
  historyEn:
    "History: the baht was pegged to a USD-dominated basket from 1984, near 25 baht to the dollar. Through the first half of 1997 the Bank of Thailand defended it with both spot reserves and forward contracts. By the float on 2 July 1997 its forward commitments stood at roughly US$23bn against headline reserves of about US$30bn — almost nothing was actually usable. The baht fell about 20% that day and more than half its value by early 1998. Thailand went to the IMF in August for a package of roughly US$17bn. The crisis spread into the Asian Financial Crisis.",
  historyDeepZh: [
    "1997 年 5 月中旬，泰国央行联合新加坡金管局入市干预，一度把投机者逼到亏损，并对本地银行实行离岸拆借管制，境外隔夜利率一度飙到三位数——攻势被打退了一次，但代价是本地信贷同时冻住。",
    "6 月 19 日财政部长辞职。市场把人事变动读成「防线要松」，远期贴水当周再度扩大。",
    "7 月 2 日宣布「有管理的浮动」后，泰铢当日贬约 20%；央行同时宣布将贴现率由 10.5% 上调至 12.5%。",
    "同年 6 月与 8 月，泰国先后暂停 16 家与 42 家财务公司营业，合计 58 家中的绝大多数最终被永久关闭。",
    "1998 年 1 月泰铢一度触及约 56 铢兑 1 美元，较钉住时贬值逾一半。",
  ],
  historyDeepEn: [
    "In mid-May 1997 the Bank of Thailand intervened jointly with the Monetary Authority of Singapore and briefly put the speculators underwater, aided by curbs on offshore baht lending that drove offshore overnight rates to three figures. The attack was pushed back once — at the price of freezing domestic credit at the same time.",
    "The finance minister resigned on 19 June. The market read the reshuffle as the line loosening, and forward discounts widened again that week.",
    "After the 'managed float' was announced on 2 July the baht fell about 20% that day, and the central bank raised its discount rate from 10.5% to 12.5%.",
    "Thailand suspended 16 finance companies in June and a further 42 in August; most of the 58 were ultimately closed for good.",
    "By January 1998 the baht touched roughly 56 to the dollar — less than half its pegged value.",
  ],
  lessonZh:
    "这一战教的是：「账面储备不等于可用储备」。远期合约是已经花掉但还没结算的钱。当你看到一个央行「储备充足」却还在加息求援，先问一句：远期簿上有多少？",
  lessonEn:
    "The lesson: headline reserves are not usable reserves. A forward book is money already spent but not yet settled. When a central bank says it has ample reserves and is still hiking and asking for help, ask what is on the forward book.",
  lexicon: PEG_LEXICON,
  pegRate: 25,
  band: 0.02,
  reserves: 30_000,
  committedForward: 23_000,
  startRate: 0.105,
  maxRate: 0.25,
  allowEquityDefence: false,
  days: 10,
  historicalOutcome: "broke",
  // The historical defence: burn reserves hard, reach for the rate far too
  // late. The pot is mostly forwards, so it is gone before the hikes matter.
  autoDefence: { spend: 0.3, nudgeOnDay: 7, nudgeTo: 0.155 },
  phases: [
    {
      day: 1,
      titleZh: "远期市场先动",
      titleEn: "The forwards move first",
      bodyZh: "现货还钉得住，远期已经贴水。有人在赌三个月后的汇率，而且赌得不小。",
      bodyEn: "Spot is still pinned; the forwards are already at a discount. Somebody is betting on the rate three months out, and betting big.",
      pressure: 0.18,
    },
    {
      day: 2,
      titleZh: "联合干预",
      titleEn: "A joint intervention",
      bodyZh: "邻国央行和你一起入市，境外拆借被卡住，投机盘一度被打到亏损。代价是本地银行也借不到钱了。",
      bodyEn: "A neighbouring central bank intervenes alongside you and offshore funding is choked off. The speculators are briefly underwater — and so is every local bank trying to borrow.",
      pressure: -0.06,
      equityShock: 0.03,
      minDetail: 2,
    },
    {
      day: 3,
      titleZh: "财务公司挤兑",
      titleEn: "A run on the finance houses",
      bodyZh: "两家财务公司被暂停营业。储户排队。外资开始抽短期信贷。",
      bodyEn: "Two finance companies are suspended. Depositors queue. Foreign lenders start pulling short-term credit lines.",
      pressure: 0.22,
      equityShock: 0.08,
    },
    {
      day: 5,
      titleZh: "财长辞职",
      titleEn: "The minister resigns",
      bodyZh: "财政部长递了辞呈。没有人解释原因，市场自己解释了：防线要松。",
      bodyEn: "The finance minister hands in his resignation. Nobody explains why, so the market explains it for itself: the line is about to loosen.",
      pressure: 0.16,
      minDetail: 1,
    },
    {
      day: 6,
      titleZh: "远期簿曝光",
      titleEn: "The forward book leaks",
      bodyZh: "一份内部数字流出：可用储备远低于公告数字。市场知道了你只剩多少子弹。",
      bodyEn: "An internal figure gets out: usable reserves are far below the published number. The market now knows how many bullets are left.",
      pressure: 0.4,
      equityShock: 0.06,
    },
    {
      day: 8,
      titleZh: "总攻",
      titleEn: "The push",
      bodyZh: "北风基金把仓位加满。这一波不是试探，是要把钉子拔出来。",
      bodyEn: "Northwind sizes up. This wave is not a probe — it is meant to pull the peg out of the floor.",
      pressure: 0.5,
      equityShock: 0.1,
    },
  ],
  calls: [
    {
      id: "baht-c1",
      day: 1,
      direction: "in",
      fromZh: "素拉·Sura",
      fromEn: "Sura",
      roleZh: "央行外汇交易室主管",
      roleEn: "Head of the FX desk",
      lines: [
        { zh: "行长，远期一年期贴水今早扩到 12%。", en: "Governor — one-year forwards widened to a 12% discount this morning." },
        { zh: "对手盘很集中。同一个中介，同一个方向，连着三天。", en: "The flow is concentrated. Same broker, same direction, three days running." },
      ],
      options: [
        {
          id: "look",
          zh: "把远期簿的真实数字给我，今天之内。",
          en: "Get me the real forward book. Today.",
          effect: { credibility: 0.05 },
          replyZh: "……我需要两个小时。行长，数字不好看。",
          replyEn: "…Give me two hours. Governor, the number is not good.",
          tone: "good",
        },
        {
          id: "shrug",
          zh: "远期一直有贴水。按老规矩做市，别声张。",
          en: "Forwards always trade at a discount. Make markets as usual and keep it quiet.",
          effect: { pressure: 0.05 },
          replyZh: "明白。那我继续按老规矩卖美元。",
          replyEn: "Understood. I will keep selling dollars the usual way, then.",
          tone: "bad",
        },
      ],
    },
    {
      id: "baht-c2",
      day: 3,
      direction: "in",
      fromZh: "《海峡商报》记者",
      fromEn: "Strait Commercial Daily",
      roleZh: "财经记者",
      roleEn: "Financial reporter",
      minDetail: 1,
      lines: [
        { zh: "行长，能确认一下储备数字吗？市场上有说法说可动用的部分不到公告的三成。", en: "Governor, can you confirm the reserve figure? There is talk that the usable share is under a third of what you published." },
      ],
      options: [
        {
          id: "truth",
          zh: "公告数字是账面。可动用的部分我们会在下周披露。",
          en: "The published figure is the headline. We will disclose the usable share next week.",
          effect: { pressure: 0.09, credibility: 0.12 },
          replyZh: "……您是第一个这么说的央行官员。我会原文照登。",
          replyEn: "…You are the first central banker to say that out loud. I will print it verbatim.",
          tone: "info",
        },
        {
          id: "deny",
          zh: "储备充足。这个说法没有根据。",
          en: "Reserves are ample. There is no basis for that claim.",
          effect: { pressure: -0.04, credibility: -0.18 },
          replyZh: "好的。不过明天如果数字出来对不上，我还是会打这个电话。",
          replyEn: "Fine. Though if the number comes out and does not match, I will be calling again tomorrow.",
          tone: "bad",
        },
        {
          id: "nocomment",
          zh: "无可奉告。",
          en: "No comment.",
          replyZh: "那我就写「央行拒绝置评」。您知道市场怎么读这五个字。",
          replyEn: "Then I write 'the central bank declined to comment'. You know how the market reads that.",
          tone: "info",
        },
      ],
    },
    {
      id: "baht-c3",
      day: 4,
      direction: "out",
      fromZh: "邻国金管局",
      fromEn: "The neighbouring monetary authority",
      roleZh: "联合干预对口人",
      roleEn: "Counterpart on joint intervention",
      minDetail: 1,
      lines: [
        { zh: "我们可以陪你入一次市，但只有一次，而且不谈第二次。", en: "We will go into the market with you once. Once. We are not discussing a second time." },
        { zh: "你要想清楚用在哪一天——用早了，对手会知道你的极限在哪。", en: "Think hard about which day you use it. Too early, and they learn where your limit is." },
      ],
      options: [
        {
          id: "now",
          zh: "现在就用。先把气焰压下去。",
          en: "Use it now. Break the momentum.",
          effect: { pressure: -0.14, reserves: -1200 },
          replyZh: "成交。今晚就动手。记住，这是最后一次。",
          replyEn: "Done. Tonight. Remember: that was the one.",
          tone: "good",
        },
        {
          id: "save",
          zh: "留着。等他们总攻那天再用。",
          en: "Hold it. Spend it on the day they come in force.",
          effect: { credibility: 0.05 },
          replyZh: "也好。电话随时打得通。",
          replyEn: "Reasonable. The line stays open.",
          tone: "info",
        },
      ],
    },
    {
      id: "baht-c4",
      day: 6,
      direction: "in",
      fromZh: "北风基金 · 交易台",
      fromEn: "Northwind Capital — dealing desk",
      roleZh: "对手方",
      roleEn: "The other side",
      minDetail: 2,
      lines: [
        { zh: "行长，礼貌性通知一声：我们下周三要结算一笔远期。", en: "Governor, a courtesy call: we have a forward settling on Wednesday." },
        { zh: "如果您愿意谈一个价，我们可以私下平掉。当然，价格由市场定。", en: "If you would like to talk about a price, we can unwind it privately. At the market, naturally." },
      ],
      options: [
        {
          id: "refuse",
          zh: "不谈。到期按合约执行。",
          en: "No. It settles on the contract.",
          effect: { pressure: 0.04, credibility: 0.08 },
          replyZh: "那就周三见。",
          replyEn: "Wednesday, then.",
          tone: "info",
        },
        {
          id: "deal",
          zh: "谈。多少钱能让这笔今天消失？",
          en: "Talk. What makes this go away today?",
          effect: { pressure: -0.1, reserves: -2600 },
          replyZh: "价格不便宜。不过您省下的是一个标题，不是一笔钱。",
          replyEn: "It is not cheap. But what you are buying is a headline, not a position.",
          tone: "info",
        },
      ],
    },
    {
      id: "baht-c5",
      day: 8,
      direction: "in",
      fromZh: "国际清算协会",
      fromEn: "The international settlements body",
      roleZh: "紧急贷款窗口",
      roleEn: "Emergency facility",
      minDetail: 2,
      lines: [
        { zh: "我们可以开一个一揽子额度。条件是：公布真实的远期承诺，并且接受监督。", en: "We can open a package. The conditions are: publish the true forward commitments, and accept supervision." },
      ],
      options: [
        {
          id: "accept",
          zh: "接受。把数字公布出去。",
          en: "Accept. Publish the number.",
          effect: { pressure: 0.12, reserves: 4200, credibility: 0.2 },
          replyZh: "钱周一到。市场今天会砸你，下个月会信你。",
          replyEn: "Funds land Monday. The market will hit you today and believe you next month.",
          tone: "info",
        },
        {
          id: "refuse",
          zh: "不接受。我们自己撑得住。",
          en: "Decline. We can hold this ourselves.",
          effect: { credibility: -0.05 },
          replyZh: "记录在案。需要的时候再打过来——如果那时还来得及。",
          replyEn: "Noted. Call when you need it, if there is still time.",
          tone: "info",
        },
      ],
    },
    {
      id: "baht-c6",
      day: 9,
      direction: "out",
      fromZh: "拉莫娜商业银行",
      fromEn: "A large commercial bank",
      roleZh: "行长",
      roleEn: "Chief executive",
      seats: ["governor", "trader"],
      minDetail: 3,
      lines: [
        { zh: "隔夜我们借不到钱。不是贵，是根本没人报价。", en: "We cannot fund overnight. Not expensive — there is simply no bid." },
        { zh: "如果明早开不了门，排队的是储户，不是交易员。", en: "If we cannot open tomorrow, the queue outside is depositors, not traders." },
      ],
      options: [
        {
          id: "window",
          zh: "开贴现窗口。今晚就给你们流动性。",
          en: "The discount window opens. You get liquidity tonight.",
          effect: { pressure: 0.05, reserves: -900, equityMul: 1.04 },
          replyZh: "谢谢。我们明早照常开门。",
          replyEn: "Thank you. We open on time tomorrow.",
          tone: "good",
        },
        {
          id: "no",
          zh: "不行。储备要留给汇率。",
          en: "No. The reserves are for the currency.",
          effect: { equityMul: 0.94, pressure: 0.03 },
          replyZh: "我明白。那明早的照片会很难看。",
          replyEn: "Understood. Tomorrow's photographs will not be kind.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective(),
    trader: traderObjective(),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "把钉子拔出来",
      titleEn: "Pull the peg",
      howZh: "在远期市场上持续建空头，逼央行出手。每一天央行花掉的储备，都是你下一天的胜算。盯住「可用储备」这个数字——不是公告上那个。",
      howEn: "Build the short in the forwards and keep the pressure on. Every unit of reserve the bank burns today is your edge tomorrow. Watch usable reserves, not the published figure.",
      winZh: "在最后一天结束前让汇率跌破区间。储备见底或者利率顶到天花板，钉子就守不住了。",
      winEn: "Force the rate outside its band before the last day ends. When reserves run out or the rate hits its ceiling, the peg goes.",
      trapZh: "央行加息会掐住你的融资成本。攻得太早、太慢，你会先被利息耗死。",
      trapEn: "Rate hikes squeeze your funding. Attack too early or too slowly and the carry bleeds you out before the peg does.",
    },
    governor: {
      side: "defend",
      kind: "holdPeg",
      target: 0,
      titleZh: "守住这根钉子",
      titleEn: "Hold the peg",
      howZh: "你有两张牌：烧储备、加息。烧储备直接压回压力，但会见底；加息压住投机，但会把股市和房地产一起按死。每天决定各出多少。",
      howEn: "You hold two cards: spend reserves and raise rates. Reserves push back on the pressure directly but they run out. Rates deter speculation but they flatten the stock market and property with it.",
      winZh: "撑满全部交易日，汇率不破区间。",
      winEn: "Last every session without the rate leaving its band.",
      trapZh: "你的可用储备远低于账面。先去「储备」面板看清楚自己到底有多少钱，再决定怎么花——这一步没做的行长，历史上没守住。",
      trapEn: "Your usable reserves are far below the headline. Look at the reserves panel before you spend a single unit. The governors who skipped that step are the ones history records as losing.",
    },
  },
};

export const POUND: Scenario = {
  id: "pound",
  kind: "peg",
  nameZh: "大卫币黑色星期三",
  nameEn: "David's Black Wednesday",
  year: "1992",
  grade: 5,
  order: 8,
  major: true,
  briefZh:
    "大卫国两年前把本币加入了一个区域汇率机制，进场价定得偏高。隔壁的大国刚刚完成统一，为了压通胀把利率拉得很高，整个机制都得跟着它走。问题是大卫国正在衰退：失业在升，房贷是浮动利率，选民付不起更高的利息。北风基金看到的不是汇率错了，是「这个国家付不起守住汇率的代价」。",
  briefEn:
    "David joined a regional exchange-rate mechanism two years ago, at a rate many thought too strong. The large neighbour has just reunified and is holding rates high to fight inflation — and the whole mechanism has to follow it. The trouble is that David is in recession: unemployment is rising, mortgages float, and voters cannot pay a higher rate. What Northwind saw was not that the rate was wrong. It was that this country could not afford the price of defending it.",
  historyZh:
    "史实：英国于 1990 年 10 月以 1 英镑兑 2.95 马克的中心汇率加入欧洲汇率机制（ERM），波动区间 ±6%，下限约 2.778 马克。1992 年 9 月 16 日（「黑色星期三」），英格兰银行上午将基准利率由 10% 上调至 12%，下午宣布将再升至 15%（该次加息从未真正实施），同时大量抛售外汇储备干预。当日晚间英国宣布暂停 ERM 成员资格。英国财政部其后估算这次防守的净成本约为 33 亿英镑。乔治·索罗斯旗下的量子基金在这笔交易上的获利，公开报道约为 10 亿美元；此役之后，「打垮英格兰银行的人」成了他最广为人知的标签。",
  historyEn:
    "History: the UK entered the European Exchange Rate Mechanism in October 1990 at a central rate of DM 2.95 to the pound with a ±6% band, a floor near DM 2.778. On 16 September 1992 — Black Wednesday — the Bank of England raised its base rate from 10% to 12% in the morning and announced a further rise to 15% in the afternoon, which was never implemented, while selling reserves heavily to intervene. That evening the UK suspended its ERM membership. The Treasury later estimated the net cost of the defence at around £3.3bn. The profit made on the trade by George Soros's Quantum Fund was widely reported at roughly US$1bn.",
  historyDeepZh: [
    "1992 年 9 月初，芬兰马克已与德国马克脱钩，意大利里拉承压，整个机制的边缘先松动。",
    "9 月 14 日意大利里拉贬值约 7%，德国央行同时小幅降息。市场读出的信息是：降息幅度不足以救英镑。",
    "9 月 15 日晚，一家德国报纸刊出德国央行行长的访谈，暗示还会有货币需要重新调整。这篇访谈被普遍视为触发第二天总攻的那一下。",
    "9 月 16 日上午 11 时，英格兰银行宣布基准利率由 10% 升至 12%；下午 2 时 15 分宣布将于次日再升至 15%。汇率没有回到区间内。",
    "当晚约 19 时，财政大臣宣布暂停 ERM 成员资格，15% 的加息随即撤回。",
    "1997 年解密的财政部文件显示，防守的净成本约 33 亿英镑，其中约 8 亿来自当日干预的直接损失。",
  ],
  historyDeepEn: [
    "By early September 1992 the Finnish markka had already broken its link to the D-mark and the Italian lira was under pressure. The edges of the mechanism loosened first.",
    "On 14 September the lira was devalued by about 7% and the Bundesbank cut rates slightly. What the market heard was that the cut was nowhere near enough to save sterling.",
    "On the evening of 15 September a German newspaper published an interview with the Bundesbank president hinting that further currencies might need realignment. It is widely regarded as the spark for the next morning's assault.",
    "At 11:00 on 16 September the Bank of England raised the base rate from 10% to 12%; at 14:15 it announced a further rise to 15% for the following day. The rate did not come back into the band.",
    "At around 19:00 that evening the Chancellor suspended ERM membership, and the 15% rise was withdrawn.",
    "Treasury papers released in 1997 put the net cost of the defence at about £3.3bn, of which roughly £800m was the direct loss on that day's intervention.",
  ],
  lessonZh:
    "这一战教的是：「利率这张牌，是有政治成本的」。一个央行能加多少息，不取决于模型，取决于这个国家的家庭能不能付得起月供。当市场算出你的利率天花板比守住汇率所需要的低，钉子就已经掉了，只是还没落地。",
  lessonEn:
    "The lesson: the rate card has a political price. How far a central bank can hike is not set by a model, it is set by whether households can pay the mortgage. Once the market works out that your ceiling is below what the peg needs, the peg is already gone — it just has not landed yet.",
  lexicon: PEG_LEXICON,
  pegRate: 2.95,
  band: 0.06,
  reserves: 45_000,
  committedForward: 0,
  startRate: 0.1,
  // Politics, not economics, sets this ceiling: past here the government falls.
  maxRate: 0.15,
  allowEquityDefence: false,
  allowPledge: true,
  days: 6,
  historicalOutcome: "broke",
  // Hold the line on the rate until the last possible day, then hike twice in
  // one morning. Famously too late.
  autoDefence: { spend: 0.14, nudgeOnDay: 5, nudgeTo: 0.12, hikeOnDay: 6 },
  phases: [
    {
      day: 1,
      titleZh: "邻国不肯降息",
      titleEn: "The neighbour will not cut",
      bodyZh: "大国央行重申反通胀立场。市场立刻明白：这台机器不会为你减速。",
      bodyEn: "The large neighbour's central bank restates its anti-inflation line. The market understands at once that the machine will not slow down for you.",
      pressure: 0.2,
    },
    {
      day: 2,
      titleZh: "试探性抛售",
      titleEn: "A probing sale",
      bodyZh: "汇率贴着区间下限跑。储备开始流出，但还不算快。",
      bodyEn: "The rate runs along the floor of the band. Reserves start to leak, though not yet quickly.",
      pressure: 0.25,
    },
    {
      day: 3,
      titleZh: "边缘先松",
      titleEn: "The edges loosen first",
      bodyZh: "机制里最小的那个成员先贬了值。所有人开始数：下一个是谁。",
      bodyEn: "The smallest member of the mechanism devalues first. Everybody starts counting down the list of who is next.",
      pressure: 0.18,
      minDetail: 1,
    },
    {
      day: 4,
      titleZh: "一句话",
      titleEn: "One sentence",
      bodyZh: "一位官员在采访里暗示汇率「可以重新审视」。这一句话值几十亿。",
      bodyEn: "An official hints in an interview that the rate 'could be looked at again'. That sentence is worth billions.",
      pressure: 0.38,
      equityShock: 0.04,
    },
    {
      day: 5,
      titleZh: "黑色星期三",
      titleEn: "Black Wednesday",
      bodyZh: "开盘即遭总攻。上午加息两个点没有止住，下午你面前摆着再加三个点的文件——和一份失业率预测。",
      bodyEn: "The attack lands at the open. Two points on the rate in the morning does not stop it. By the afternoon there is a paper on your desk for three more — and an unemployment forecast beside it.",
      pressure: 1.4,
      equityShock: 0.09,
    },
  ],
  calls: [
    {
      id: "pound-c1",
      day: 1,
      direction: "in",
      fromZh: "财政大臣办公室",
      fromEn: "The Chancellor's office",
      roleZh: "首席私人秘书",
      roleEn: "Principal private secretary",
      lines: [
        { zh: "大臣想知道：我们今天要不要说点什么？", en: "The Chancellor wants to know whether we say anything today." },
        { zh: "他准备了一句「我们将不惜一切代价守住中心汇率」。", en: "He has a line ready: 'we will defend the central rate at any cost'." },
      ],
      options: [
        {
          id: "say",
          zh: "让他说。现在需要的是一个明确的姿态。",
          en: "Let him say it. What this needs today is a clear posture.",
          effect: { pressure: -0.06, credibility: -0.06 },
          replyZh: "好。十一点的镜头前说。",
          replyEn: "Right. In front of the cameras at eleven.",
          tone: "info",
        },
        {
          id: "quiet",
          zh: "别说。说了就是给市场一个可以打的目标。",
          en: "Say nothing. A line like that just hands the market something to aim at.",
          effect: { credibility: 0.08 },
          replyZh: "他不会高兴，但我会转达。",
          replyEn: "He will not be pleased, but I will pass it on.",
          tone: "info",
        },
      ],
    },
    {
      id: "pound-c2",
      day: 3,
      direction: "out",
      fromZh: "大陆央行",
      fromEn: "The continental central bank",
      roleZh: "行长办公室",
      roleEn: "President's office",
      minDetail: 1,
      lines: [
        { zh: "我理解你的处境。但我的法定职责是本国的通胀，不是你的失业率。", en: "I understand your position. My statutory mandate is inflation here, not unemployment there." },
        { zh: "如果你要我降息，那请给我一个能写进纪要的理由。", en: "If you want a cut, give me a reason I can put in the minutes." },
      ],
      options: [
        {
          id: "press",
          zh: "整个机制会因为你的 0.25 个点而崩掉。这是理由。",
          en: "The whole mechanism breaks over a quarter point of yours. That is the reason.",
          effect: { pressure: -0.08, credibility: -0.05 },
          replyZh: "我会把这句话带到理事会。不保证结果。",
          replyEn: "I will take that to the council. I promise nothing.",
          tone: "info",
        },
        {
          id: "realign",
          zh: "那就谈重新调整中心汇率。现在谈，比周三谈体面。",
          en: "Then let us talk about realigning the central rate. It is more dignified now than on Wednesday.",
          effect: { pressure: -0.22, credibility: -0.2 },
          replyZh: "这是成年人的话。但你们的大臣不会同意——你先去说服他。",
          replyEn: "That is the grown-up answer. Your Chancellor will refuse it, though. Convince him first.",
          tone: "info",
        },
        {
          id: "none",
          zh: "不求人。我们自己守。",
          en: "We are not asking. We will hold it ourselves.",
          effect: { credibility: 0.1 },
          replyZh: "祝你好运。我是认真的。",
          replyEn: "Good luck. I mean that.",
          tone: "info",
        },
      ],
    },
    {
      id: "pound-c3",
      day: 4,
      direction: "in",
      fromZh: "《大陆晨报》",
      fromEn: "The continental morning paper",
      roleZh: "首席经济记者",
      roleEn: "Chief economics correspondent",
      minDetail: 1,
      lines: [
        { zh: "我们明早要发一篇访谈，里面有一句「还会有货币需要重新调整」。", en: "We run an interview tomorrow. There is a sentence in it about 'further currencies needing realignment'." },
        { zh: "按惯例，给您一个回应的机会。", en: "As a courtesy, you get a chance to respond." },
      ],
      options: [
        {
          id: "deny",
          zh: "强烈否认。这句话会被市场当成信号。",
          en: "Deny it flatly. The market will read that sentence as a signal.",
          effect: { pressure: 0.06, credibility: -0.05 },
          replyZh: "我们会把您的否认放在第十一段。",
          replyEn: "Your denial will appear in paragraph eleven.",
          tone: "bad",
        },
        {
          id: "prepare",
          zh: "不回应。但我今晚就把利率决议准备好。",
          en: "No response. But I will have the rate decision ready tonight.",
          effect: { pressure: -0.05, credibility: 0.08 },
          replyZh: "那我们明早见。",
          replyEn: "We will see you in the morning, then.",
          tone: "info",
        },
      ],
    },
    {
      id: "pound-c4",
      day: 5,
      direction: "in",
      fromZh: "首相办公室",
      fromEn: "The Prime Minister's office",
      roleZh: "政治秘书",
      roleEn: "Political secretary",
      minDetail: 2,
      lines: [
        { zh: "行长，首相刚看到 15% 的文件。他想知道一件事。", en: "Governor, the Prime Minister has seen the paper on 15%. He wants to know one thing." },
        { zh: "这个数字如果真的实施，下个月有多少家庭还不上月供？", en: "If that number is actually implemented, how many households miss their mortgage next month?" },
      ],
      options: [
        {
          id: "honest",
          zh: "很多。但如果今天不加，明天就不是月供的问题了。",
          en: "A great many. And if we do not go today, by tomorrow the mortgage is not the problem any more.",
          effect: { credibility: 0.12 },
          replyZh: "他会签。但他要你在纪要里写清楚是你建议的。",
          replyEn: "He will sign. He wants the minute to record that it was your recommendation.",
          tone: "info",
        },
        {
          id: "soften",
          zh: "太多了。建议撤回这份文件。",
          en: "Too many. I recommend withdrawing the paper.",
          effect: { pressure: 0.18, equityMul: 1.04 },
          replyZh: "他松了一口气。市场十分钟后就会知道。",
          replyEn: "He is relieved. The market will know within ten minutes.",
          tone: "bad",
        },
      ],
    },
    {
      id: "pound-c5",
      day: 5,
      direction: "out",
      fromZh: "北风基金 · 首席交易员",
      fromEn: "Northwind Capital — head trader",
      roleZh: "对手方",
      roleEn: "The other side",
      seats: ["governor", "fund", "trader"],
      minDetail: 3,
      lines: [
        { zh: "行长？没想到您会亲自打过来。", en: "Governor? I did not expect you to call yourself." },
        { zh: "我不能告诉您我们的仓位。但我可以告诉您：我们不急。", en: "I cannot tell you our position. I can tell you we are not in a hurry." },
      ],
      options: [
        {
          id: "warn",
          zh: "我今天下午会做一件你没算进去的事。",
          en: "This afternoon I am going to do something you have not priced.",
          effect: { pressure: -0.07, credibility: -0.08 },
          replyZh: "那我等着。顺便说一句，您打这通电话本身就是信息。",
          replyEn: "I will wait, then. And — placing this call is itself information.",
          tone: "info",
        },
        {
          id: "listen",
          zh: "我只想知道一件事：你们认为我的天花板在哪？",
          en: "One question only: where do you think my ceiling is?",
          effect: { credibility: -0.03 },
          replyZh: "在您的选民付不起月供的那个点。跟您的模型没关系。",
          replyEn: "At the point your voters cannot pay the mortgage. It has nothing to do with your model.",
          tone: "info",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.75,
      trapZh: "你的房贷是浮动的。行长每加一个点，你的月供就涨一次——加息日之前把杠杆降下来。",
      trapEn: "Your mortgage floats. Every point the governor adds lands on your monthly payment — cut leverage before the hike, not after.",
    }),
    trader: traderObjective({
      target: 0.18,
      howZh: "这一关的信号不在汇率，在政治。盯住利率天花板和失业率：当市场认定行长加不动了，方向就定了。",
      howEn: "The signal here is political, not monetary. Watch the rate ceiling and unemployment: once the market decides the governor cannot hike again, the direction is settled.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "算出他的天花板",
      titleEn: "Find his ceiling",
      howZh: "不要急着满仓。让央行先加息、先烧储备——你要做的是把压力顶到他政治上加不动息的那个点。看着利率逼近天花板，再压最后一把。",
      howEn: "Do not size up early. Let the bank hike and burn reserves first — your job is to push the pressure past the point where another hike is politically impossible. When the rate nears the ceiling, lean in.",
      winZh: "在最后一天结束前让汇率跌破区间下限。",
      winEn: "Force the rate below the floor of the band before the last day ends.",
      trapZh: "他还有很多储备。单靠消耗储备你赢不了——你赢的是他的政治余地，不是他的钱。",
      trapEn: "He has plenty of reserves. You will not win by draining them — you win by exhausting his political room, not his money.",
    },
    governor: {
      side: "defend",
      kind: "holdPeg",
      target: 0,
      titleZh: "撑到周末",
      titleEn: "Hold to the weekend",
      howZh: "储备够用，问题是利率。每次加息都能压回压力，但会推高失业和月供——利率有一个你越不过去的天花板（15%）。在天花板之前，你必须让对手先没钱。你还有一次公开承诺的机会，但空口承诺是要还的。",
      howEn: "Reserves are not your problem; the rate is. Every hike pushes the pressure back and pushes unemployment and mortgage payments up with it — and there is a ceiling (15%) you cannot cross. Before you reach it, the other side has to run out first. You also get one public commitment — but an unbacked promise has to be paid for later.",
      winZh: "撑满全部交易日，汇率不破下限。",
      winEn: "Last every session without the rate leaving the band.",
      trapZh: "历史上这一关是输的。要赢，你得比历史上的行长更早动手——等到「黑色星期三」当天再加息，就来不及了。",
      trapEn: "History lost this one. To win it you have to move earlier than the governor did — waiting until Black Wednesday itself to hike is already too late.",
    },
  },
};

export const HKD: Scenario = {
  id: "hkd",
  kind: "peg",
  nameZh: "狮子币保卫战",
  nameEn: "The Leo Dollar Defence",
  year: "1998",
  grade: 8,
  order: 12,
  major: true,
  briefZh:
    "狮子国用的是货币发行局制度：本币和外币按固定比例硬挂钩，谁卖本币，银行体系的钱就自动减少，隔夜利率就自动飙升。这套机制十五年没破过。北风基金也知道它破不了——所以他们不打算只打汇率。他们同时在股指期货上建了巨额空单。你越守汇率，利率越高；利率越高，股市越垮；股市越垮，他们赚得越多。这叫「双边操作」，你的防守本身就是他们的利润来源。",
  briefEn:
    "Leo runs a currency board: the local unit is hard-linked at a fixed rate, and anyone selling it automatically drains the banking system and sends overnight rates through the roof. In fifteen years it has never broken. Northwind knows that too — which is why they are not only attacking the currency. They have built an enormous short in index futures at the same time. The harder you defend, the higher rates go; the higher rates go, the harder stocks fall; the harder stocks fall, the more they make. This is the double play, and your own defence is what pays for it.",
  historyZh:
    "史实：香港自 1983 年实行联系汇率制度，7.8 港元兑 1 美元。1998 年 8 月，投机者同时沽空港元与恒生指数期货——攻击港元会迫使利率飙升，从而打压股市，在期货上获利。8 月 14 日至 28 日，香港特区政府通过外汇基金直接入市买入港股，规模约 1,180 亿港元，令 8 月期指结算价不利于空方。9 月香港金管局公布七项技术性措施巩固货币发行局制度。政府持有的股票其后注入盈富基金（TraHK），于 1999 年 11 月上市，最终录得盈利。",
  historyEn:
    "History: Hong Kong has operated a Linked Exchange Rate System since 1983, at 7.8 HKD to the US dollar. In August 1998 speculators shorted the Hong Kong dollar and Hang Seng index futures together — attacking the currency forces rates up, which drives stocks down, paying off on the futures leg. Between 14 and 28 August 1998 the Hong Kong government, through the Exchange Fund, bought Hong Kong shares directly, to the order of HK$118bn, turning the August futures settlement against the short side. In September the HKMA announced seven technical measures to strengthen the currency board. The shares were later placed into the Tracker Fund of Hong Kong, listed in November 1999, and were ultimately sold at a profit.",
  historyDeepZh: [
    "1997 年 10 月 23 日，隔夜港元拆息一度触及约 280%，恒生指数当日跌逾 10%——这一天让所有人看清了「守汇率」和「守股市」是同一根杠杆的两端。",
    "1998 年 8 月 14 日（周五）是政府首次入市的日子，恒生指数当日由约 6,660 点升至约 7,224 点。",
    "8 月 28 日为 8 月期指结算日，当日成交约 790 亿港元，创当时单日纪录；恒指收报约 7,829 点。",
    "外汇基金此役买入的港股约占当时市值的 7%，政府一度成为多家蓝筹公司的最大股东之一。",
    "1998 年 9 月 5 日，金管局公布七项技术性措施，其中包括承诺按 7.75 的兑换保证为持牌银行的结算户口提供兑换，并逐步移向 7.80。",
    "2002 年起政府通过盈富基金持续减持，整体录得可观盈利；但这一招在当时被国际舆论广泛批评为干预自由市场。",
  ],
  historyDeepEn: [
    "On 23 October 1997 overnight Hong Kong dollar rates touched roughly 280% and the Hang Seng fell more than 10% in a day — the session that showed everybody that defending the currency and defending the market are two ends of one lever.",
    "Friday 14 August 1998 was the first day of government buying; the Hang Seng rose from about 6,660 to about 7,224.",
    "28 August was the August futures settlement. Turnover reached roughly HK$79bn, a single-day record at the time, and the index closed near 7,829.",
    "The Exchange Fund ended up holding around 7% of the market's capitalisation, making the government one of the largest shareholders in several blue chips.",
    "On 5 September 1998 the HKMA announced seven technical measures, including a convertibility undertaking for licensed banks' clearing balances at 7.75, to be moved gradually towards 7.80.",
    "From 2002 the stake was sold down through the Tracker Fund at an overall profit — though at the time the operation was widely criticised internationally as interference in a free market.",
  ],
  lessonZh:
    "这一战教的是：「面对双边操作，只守一条腿等于送钱」。守汇率会自动推高利率，而利率正是对手打股市的武器。要赢就得同时守住两条腿——而这在当时是一个极具争议的决定：一个自由市场政府，直接下场买自己的股票。它赢了，但赢得并不轻松，也不是可以随便复制的招。",
  lessonEn:
    "The lesson: against a double play, defending one leg is a donation. Defending the currency automatically raises rates, and rates are the weapon aimed at the stock market. Winning means holding both legs at once — which at the time was a deeply controversial call: a free-market government buying its own equities outright. It worked. It was not comfortable, and it is not a move that copies cleanly anywhere else.",
  lexicon: PEG_LEXICON,
  pegRate: 7.8,
  band: 0.01,
  reserves: 96_000,
  committedForward: 0,
  startRate: 0.08,
  maxRate: 0.22,
  allowEquityDefence: true,
  allowPledge: true,
  days: 12,
  historicalOutcome: "held",
  // The currency board hikes on its own, and from settlement week the Exchange
  // Fund goes into the equity market. Both legs.
  autoDefence: { hikeOnDay: 2, buyFrom: 7, buy: 0.17 },
  phases: [
    {
      day: 2,
      titleZh: "两条腿同时建仓",
      titleEn: "Both legs go on",
      bodyZh: "狮子币被卖，隔夜利率跳升。同一时间，期指未平仓合约异常放大——有人在赌股市要跌。",
      bodyEn: "The currency is sold and overnight rates jump. At the same moment, futures open interest balloons — somebody is betting stocks fall.",
      pressure: 0.15,
      equityShock: 0.05,
    },
    {
      day: 4,
      titleZh: "谣言市",
      titleEn: "A market of rumours",
      bodyZh: "「联系汇率将放弃」「银行体系有问题」——传闻一条接一条，每一条都不署名，每一条都有人信。",
      bodyEn: "'The link will be abandoned.' 'There is a problem in the banking system.' The rumours come one after another, all unattributed, all believed by somebody.",
      pressure: 0.12,
      equityShock: 0.04,
      minDetail: 1,
    },
    {
      day: 5,
      titleZh: "利率飙升",
      titleEn: "Rates spike",
      bodyZh: "隔夜拆息一度冲到两位数。银行惜贷，股市连跌五天。对手的期指空单开始赚钱——赚的是你防守的钱。",
      bodyEn: "Overnight money touches double digits. Banks stop lending and the index falls five sessions running. The short futures position starts printing — on your defence.",
      pressure: 0.22,
      equityShock: 0.12,
    },
    {
      day: 8,
      titleZh: "结算周",
      titleEn: "Settlement week",
      bodyZh: "月底期指结算临近。对手需要指数在结算日低于某个位置——他们会把所有筹码压在这几天。",
      bodyEn: "Month-end futures settlement approaches. The other side needs the index below a level on settlement day, and they will put everything into these sessions.",
      pressure: 0.3,
      equityShock: 0.15,
    },
    {
      day: 9,
      titleZh: "国际舆论",
      titleEn: "The international press",
      bodyZh: "几家大报同时评论：一个自由市场政府直接买自己的股票，是在开一个危险的先例。你今天的每一笔成交都会上头版。",
      bodyEn: "Several major papers run the same line at once: a free-market government buying its own equities is setting a dangerous precedent. Every fill you print today makes a front page.",
      pressure: 0.1,
      minDetail: 2,
    },
    {
      day: 10,
      titleZh: "最后三天",
      titleEn: "The last three sessions",
      bodyZh: "成交量是平日的数倍。这三天决定结算价，也决定这一仗谁赢。",
      bodyEn: "Volume runs at several times normal. These three sessions set the settlement price, and with it the winner.",
      pressure: 0.34,
      equityShock: 0.18,
    },
  ],
  calls: [
    {
      id: "hkd-c1",
      day: 2,
      direction: "in",
      fromZh: "金管局 · 市场部",
      fromEn: "Monetary Authority — markets",
      roleZh: "助理总裁",
      roleEn: "Executive director",
      lines: [
        { zh: "总裁，今早的沽盘有个特点：他们卖狮子币，同时在期指上加空单。", en: "Chief — this morning's selling has a signature: they sell the currency and add index shorts at the same time." },
        { zh: "这不是赌汇率会破。这是赌我们守。", en: "They are not betting the peg breaks. They are betting that we defend it." },
      ],
      options: [
        {
          id: "track",
          zh: "去查期指的未平仓合约，按结算月分开看。",
          en: "Pull the futures open interest, broken out by settlement month.",
          effect: { credibility: 0.06 },
          replyZh: "已经在查。八月那一档，大得不正常。",
          replyEn: "Already on it. The August bucket is abnormally large.",
          tone: "good",
        },
        {
          id: "ignore",
          zh: "机制会自己处理。我们守汇率就行。",
          en: "The system handles itself. We defend the currency, that is all.",
          effect: { pressure: 0.04, equityMul: 0.98 },
          replyZh: "是。……那股市那边，就先不管了。",
          replyEn: "Understood. …We leave the equity side alone, then.",
          tone: "bad",
        },
      ],
    },
    {
      id: "hkd-c2",
      day: 5,
      direction: "in",
      fromZh: "财政司办公室",
      fromEn: "The Financial Secretary's office",
      roleZh: "政策顾问",
      roleEn: "Policy adviser",
      minDetail: 1,
      lines: [
        { zh: "有人提了一个方案：用外汇基金直接进股市买。", en: "Somebody has put forward a proposal: take the Exchange Fund into the stock market and buy." },
        { zh: "法律上做得到。政治上，我们会被全世界骂一个月。", en: "Legally we can. Politically, we get shouted at by the entire world for a month." },
      ],
      options: [
        {
          id: "prepare",
          zh: "先把方案做实：买什么、买多少、什么时候停。",
          en: "Work it up properly: what we buy, how much, and when we stop.",
          effect: { credibility: 0.1 },
          replyZh: "明白。我要一份退出机制，不然这笔钱出不去。",
          replyEn: "Understood. I want an exit plan in it, or that money never comes back out.",
          tone: "good",
        },
        {
          id: "reject",
          zh: "不做。自由市场政府不买自己的股票。",
          en: "No. A free-market government does not buy its own equities.",
          effect: { pressure: 0.05, equityMul: 0.97 },
          replyZh: "记录在案。希望我们不会后悔。",
          replyEn: "Noted for the record. I hope we do not regret it.",
          tone: "bad",
        },
      ],
    },
    {
      id: "hkd-c3",
      day: 8,
      direction: "in",
      fromZh: "期货结算所",
      fromEn: "The futures clearing house",
      roleZh: "结算主管",
      roleEn: "Head of clearing",
      minDetail: 1,
      lines: [
        { zh: "八月合约的未平仓量还在涨。空方的保证金我们收得上来，但如果指数反向跳，他们就要追缴。", en: "Open interest in the August contract is still climbing. We can collect the shorts' margin — but if the index gaps against them, they get called." },
        { zh: "您要不要知道他们的持仓集中度？", en: "Do you want to know how concentrated that position is?" },
      ],
      options: [
        {
          id: "yes",
          zh: "要。我要知道他们能被轧到什么程度。",
          en: "Yes. I want to know how far they can be squeezed.",
          effect: { credibility: 0.08, pressure: -0.04 },
          replyZh: "集中在三个账户。结算日之前他们必须平，不然就交割。",
          replyEn: "Three accounts. They have to close before settlement or take delivery.",
          tone: "good",
        },
        {
          id: "no",
          zh: "不必。按规矩办你的事。",
          en: "No need. Just run your book by the rules.",
          replyZh: "明白。",
          replyEn: "Understood.",
          tone: "info",
        },
      ],
    },
    {
      id: "hkd-c4",
      day: 9,
      direction: "in",
      fromZh: "国际财经电视台",
      fromEn: "International business television",
      roleZh: "主持人",
      roleEn: "Anchor",
      minDetail: 2,
      lines: [
        { zh: "总裁，全世界都在问同一个问题：你们是不是在操纵市场？", en: "Chief Executive — the whole world is asking the same question. Are you manipulating your own market?" },
      ],
      options: [
        {
          id: "explain",
          zh: "我们在打退一场有组织的双边操作。买股票是手段，不是目的。",
          en: "We are pushing back a coordinated double play. Buying equities is the method, not the objective.",
          effect: { credibility: 0.12, pressure: -0.05 },
          replyZh: "那您什么时候卖回去？——这个问题您总要回答的。",
          replyEn: "And when do you sell it back? You will have to answer that one eventually.",
          tone: "good",
        },
        {
          id: "defiant",
          zh: "我们的市场，我们的规则。",
          en: "Our market. Our rules.",
          effect: { credibility: -0.15, pressure: 0.06 },
          replyZh: "这句话明天会被引用一百次，而且不是好的那种引用。",
          replyEn: "That will be quoted a hundred times tomorrow, and not kindly.",
          tone: "bad",
        },
        {
          id: "commit",
          zh: "我今天宣布：结算日之前，我们不会停手。",
          en: "I will say this today: we do not stop before settlement.",
          effect: { pressure: -0.12, credibility: -0.05 },
          replyZh: "那是一个承诺。市场会拿它来考你。",
          replyEn: "That is a commitment. The market will test it.",
          tone: "info",
        },
      ],
    },
    {
      id: "hkd-c5",
      day: 11,
      direction: "out",
      fromZh: "本地券商公会",
      fromEn: "The local brokers' association",
      roleZh: "主席",
      roleEn: "Chairman",
      minDetail: 3,
      seats: ["governor", "trader", "retail"],
      lines: [
        { zh: "我们的会员怕的不是跌，是明天开不了盘。", en: "Our members are not afraid of a fall. They are afraid there is no market tomorrow." },
        { zh: "您能不能给一句话：结算会正常进行。", en: "Can you give us one sentence: settlement goes ahead as normal." },
      ],
      options: [
        {
          id: "assure",
          zh: "结算会正常进行。这一句可以引用。",
          en: "Settlement goes ahead as normal. You may quote that.",
          effect: { equityMul: 1.03, pressure: -0.03, credibility: 0.05 },
          replyZh: "谢谢。我现在就发给会员。",
          replyEn: "Thank you. I am sending it to members now.",
          tone: "good",
        },
        {
          id: "hedge",
          zh: "我不做承诺。我们按市场情况决定。",
          en: "I make no promises. We decide as the market decides.",
          effect: { equityMul: 0.97, pressure: 0.04 },
          replyZh: "……那我只能如实转达。",
          replyEn: "…Then I will pass that on exactly as you said it.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.8,
      howZh: "这一关汇率大概率守得住，真正危险的是利率和股市。隔夜拆息冲上两位数的那几天，别持有任何靠借钱撑着的仓位。",
      howEn: "The peg will most likely hold here; rates and equities are what will hurt you. On the days overnight money hits double digits, hold nothing that depends on borrowing.",
    }),
    trader: traderObjective({
      target: 0.2,
      howZh: "这一关有两条腿。看懂政府会不会下场买股票，比猜汇率重要得多——他们一旦入市，空头的期指仓位会被瞬间轧平。",
      howEn: "There are two legs here. Reading whether the government will step into the equity market matters far more than guessing the currency — once they do, the short futures book gets run over.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "双边操作",
      titleEn: "The double play",
      howZh: "同时压汇率和股指。你不需要真的把钉子拔掉——只要指数在结算日之前跌够，期指那条腿就够你赚。持续施压，让利率替你砸盘。",
      howEn: "Press the currency and the index together. You do not actually need the peg to break — if the index falls far enough before settlement, the futures leg pays on its own. Keep the pressure on and let rates do the selling for you.",
      winZh: "在最后一天结束前让汇率破位。注意：如果政府直接下场买股票，你股指那条腿会被反噬。",
      winEn: "Break the peg before the last day ends. Be warned: if the government buys equities outright, the futures leg turns on you.",
      trapZh: "这是三场里最难攻的一场。货币发行局不会因为储备见底而崩——它的压力会自动转移到利率上。历史上这一战空方是输的。",
      trapEn: "This is the hardest of the three to attack. A currency board does not fall because reserves run out — the pressure transfers automatically into rates. History records the short side losing this one.",
    },
    governor: {
      side: "defend",
      kind: "holdPeg",
      target: 0,
      // Holding the peg alone is not a win here; the index has to survive too.
      equityFloor: 55,
      titleZh: "两条腿一起守",
      titleEn: "Hold both legs",
      howZh: "汇率这条腿制度会自动帮你守——卖狮子币就抽走流动性，利率自动飙升。你真正要做的决定是另一条腿：「要不要用外汇基金直接买股票」。买了，对手的期指空单会被轧；不买，你守住了汇率，输掉了股市和这一仗。",
      howEn: "The system defends the currency leg for you — selling drains liquidity and rates spike automatically. Your real decision is the other leg: whether to buy equities with the Exchange Fund. Do it and the short futures book gets squeezed. Refuse and you hold the peg, lose the market, and lose the fight.",
      winZh: "撑满全部交易日、汇率不破位，并且收盘时股指仍在 55 以上（开局 100）。两条腿缺一条都算输。",
      winEn: "Last every session with the peg intact and the index still above 55 at the close (it opens at 100). Either leg alone is a loss.",
      trapZh: "别只盯着汇率。汇率你多半守得住——你会输在股市上，而且输的钱正是你自己加息加出来的。",
      trapEn: "Do not watch only the rate. You will probably hold it — and lose on the equity leg instead, to a fall your own hikes created.",
    },
  },
};
