import type { Scenario } from "../types.ts";
import { SOVEREIGN_LEXICON, retailObjective, traderObjective } from "./seats.ts";

/**
 * A currency union with no treasury behind it.
 *
 * Every other defence in this game has a central bank that can, in the last
 * resort, produce the thing being demanded of it. Here the countries under
 * attack do not issue the currency they owe, and the institution that does
 * issue it has spent two years explaining that rescuing them is not its job.
 *
 * Which is why the winning move in this scenario is a sentence.
 */
export const EURO: Scenario = {
  id: "euro",
  kind: "sovereign",
  nameZh: "联盟债务危机 · 不惜一切代价",
  nameEn: "The Union Debt Crisis",
  year: "2010–2012",
  grade: 7,
  order: 11,
  major: true,
  briefZh:
    "十七个国家共用一种货币，却各自管自己的预算。这意味着一件在平时没人在意、在危机里决定一切的事：这些国家借的钱，是用一种它们自己印不出来的货币计价的。秋天，一个成员国承认自己的赤字比上报的高出一倍多。市场重新算了一遍所有人的账，然后问了一个从来没问过的问题：这些债，到底是谁的债？更麻烦的是，这些国债大部分躺在本国银行的账上——国家一弱，银行就弱；银行一弱，国家要救它，于是国家更弱。这个圈自己会转。",
  briefEn:
    "Seventeen countries share a currency and each runs its own budget. That means something nobody minds in calm weather and which decides everything in a crisis: these countries borrow in a currency they cannot print. In the autumn one member admits its deficit is more than twice what it had reported. The market reprices everybody and asks a question it had never asked before: whose debt is this, exactly? And it is worse than that, because most of those bonds sit on the books of the country's own banks. A weak state weakens its banks; weak banks have to be rescued by the state, which weakens the state. The loop turns by itself.",
  historyZh:
    "史实：2009 年 10 月，希腊新政府将当年赤字估计上修至约 GDP 的 12.7%（其后进一步修正至约 15.4%）。2010 年 4 月希腊十年期国债收益率突破 10%，5 月获得欧盟与 IMF 约 1,100 亿欧元的第一轮援助；同月设立欧洲金融稳定基金（EFSF，规模 4,400 亿欧元）。爱尔兰于 2010 年 11 月、葡萄牙于 2011 年 5 月先后接受援助。2012 年 3 月完成的希腊私人部门参与（PSI）债务重组涉及约 2,000 亿欧元债券，名义削减约 53.5%。2012 年 7 月，西班牙十年期收益率一度升至约 7.6%。7 月 26 日，欧洲央行行长在伦敦表示「在我们的职责范围内，欧洲央行准备好不惜一切代价捍卫欧元。相信我，这就够了」。9 月 6 日欧洲央行公布直接货币交易（OMT）机制；该机制此后从未被实际启用，而相关国家的收益率显著回落。",
  historyEn:
    "History: in October 2009 the incoming Greek government revised its deficit estimate to about 12.7% of GDP, later raised further to roughly 15.4%. Greek ten-year yields passed 10% in April 2010 and a first EU/IMF programme of about €110bn followed in May, alongside the creation of the European Financial Stability Facility at €440bn. Ireland took a programme in November 2010 and Portugal in May 2011. The Greek private sector involvement completed in March 2012 covered roughly €200bn of bonds at a nominal haircut near 53.5%. In July 2012 Spanish ten-year yields reached about 7.6%. On 26 July the President of the ECB said in London that 'within our mandate, the ECB is ready to do whatever it takes to preserve the euro. And believe me, it will be enough.' Outright Monetary Transactions were announced on 6 September; the facility was never actually used, and the yields of the countries concerned fell substantially.",
  historyDeepZh: [
    "「毁灭循环」（doom loop）的具体形态是：本国银行持有大量本国国债，主权利差上升直接打穿银行资本，而救助银行的责任又回到同一个主权头上。爱尔兰是最极端的例子——2008 年对银行体系的全面担保，两年后变成了主权本身的危机。",
    "2011 至 2012 年间，希腊、西班牙、爱尔兰等国出现持续的存款外流，资金流向被认为更安全的成员国银行。",
    "PSI 重组在技术上被认定为「信用事件」，触发了信用违约互换的赔付——这件事本身又让市场重新评估其他主权的 CDS 是否可靠。",
    "2012 年 6 月，欧盟峰会同意推动银行业联盟与单一监管机制，把银行监管从成员国上收，正是为了切断这个循环。",
    "OMT 附带严格条件：申请国必须先接受一个调整方案。也就是说，这句承诺的效力来自它背后可以无限量，而它的边界来自政治条件——两者缺一不可。",
  ],
  historyDeepEn: [
    "The doom loop in concrete terms: domestic banks hold large amounts of their own sovereign's bonds, a widening spread cuts straight through bank capital, and rescuing the banks falls back on the same sovereign. Ireland is the extreme case — a blanket guarantee of the banking system in 2008 became a sovereign crisis two years later.",
    "Through 2011 and 2012 Greece, Spain and Ireland saw sustained deposit outflows towards banks in members perceived as safer.",
    "The Greek restructuring was formally determined to be a credit event and triggered payouts on credit default swaps — which in turn made the market reassess whether any sovereign CDS could be relied on.",
    "In June 2012 the European Council agreed to move towards a banking union and a single supervisor, lifting bank supervision away from member states precisely to cut the loop.",
    "OMT came with strict conditions: a country had to accept an adjustment programme first. The promise drew its force from being potentially unlimited, and its limits from the political conditions. It needed both.",
  ],
  lessonZh:
    "这一战教的是：「承诺本身可以是一种工具，但它的效力来自它背后的东西」。同样一句「不惜一切代价」，由一个能无限量印出这种货币的机构说出来，是决定性的；由一个已经把弹药打光的财政部说出来，是求救信号。这一战里最便宜、也最有效的那一招，一分钱都没有真的花出去——但它之所以有效，恰恰是因为所有人都相信真要花的时候花得出来。另外记住那个循环：当银行的资产是本国国债，你就没法只救其中一个。",
  lessonEn:
    "The lesson: a commitment can be a tool, and its force comes entirely from what stands behind it. The same sentence — whatever it takes — is decisive from an institution that can create the currency without limit, and a distress signal from a treasury that has already spent its ammunition. The cheapest and most effective move in this crisis never actually spent anything, and it worked precisely because everybody believed the money was there if it came to that. And remember the loop: when the banks' assets are their own government's bonds, you cannot rescue one of them alone.",
  lexicon: SOVEREIGN_LEXICON,
  seatLabel: {
    governor: { zh: "央行行长", en: "Central bank president" },
    fund: { zh: "做空主权的基金", en: "The fund short the sovereign" },
    trader: { zh: "主权债交易台", en: "Sovereign bond desk" },
    retail: { zh: "本国储户", en: "Domestic saver" },
  },
  // Displayed as a yield in per cent: sustainable near 4%, unfinanceable past 7%.
  pegRate: 4,
  band: 1,
  reserves: 88_000,
  committedForward: 0,
  startRate: 0,
  // "Rate" here is austerity. The ceiling is where the government falls.
  maxRate: 0.09,
  allowEquityDefence: true,
  allowPledge: true,
  reserveEfficiency: 0.8,
  rateDefenceCap: 0.5,
  // Austerity narrows the deficit and shrinks the economy it is measured against.
  rateDragK: 0.34,
  days: 10,
  historicalOutcome: "held",
  autoDefence: { spend: 0.12, nudgeOnDay: 2, nudgeTo: 0.05, hikeOnDay: 4, buyFrom: 5, buy: 0.14, pledgeOn: 6 },
  phases: [
    {
      day: 1,
      titleZh: "数字是错的",
      titleEn: "The number was wrong",
      bodyZh: "一个成员国的新政府宣布：上一任报的赤字，实际是它的两倍多。市场开始重算所有人的账。",
      bodyEn: "A new government announces that the deficit its predecessor reported was less than half the real one. The market starts repricing everybody.",
      pressure: 0.2,
      equityShock: 0.04,
    },
    {
      day: 2,
      titleZh: "银行持有自己国家的债",
      titleEn: "The banks hold their own sovereign",
      bodyZh: "利差每涨一个点，本国银行的资本就掉一块。而要救这些银行的，正是同一个财政部。",
      bodyEn: "Every point on the spread takes a slice out of the domestic banks' capital. And the treasury that would have to rescue those banks is the same one.",
      pressure: 0.22,
      equityShock: 0.07,
    },
    {
      day: 3,
      titleZh: "第一轮援助",
      titleEn: "The first programme",
      bodyZh: "一揽子援助谈成了，条件是大幅削减赤字。街上有游行，债券市场安静了两周。",
      bodyEn: "A package is agreed, conditional on deep deficit cuts. There are demonstrations in the street, and the bond market is quiet for a fortnight.",
      pressure: -0.08,
      equityShock: 0.05,
      minDetail: 1,
    },
    {
      day: 4,
      titleZh: "传染",
      titleEn: "Contagion",
      bodyZh: "第二个、第三个成员国的利差跟着走宽。它们的财政状况没有变化，变化的是市场的问题——现在这个问题是「谁是下一个」。",
      bodyEn: "A second and a third member widen too. Nothing changed in their public finances; what changed is the market's question, which is now 'who is next'.",
      pressure: 0.3,
      equityShock: 0.06,
    },
    {
      day: 5,
      titleZh: "存款开始搬家",
      titleEn: "The deposits start moving",
      bodyZh: "钱从边缘国的银行流向被认为安全的成员国。同一种货币，同一个联盟，但这个成员国的一块钱已经不等于那个成员国的一块钱了。",
      bodyEn: "Money moves from the periphery's banks to the members thought to be safe. Same currency, same union — and a unit in one member is no longer worth a unit in another.",
      pressure: 0.28,
      equityShock: 0.08,
      minDetail: 1,
    },
    {
      day: 6,
      titleZh: "债务重组",
      titleEn: "The restructuring",
      bodyZh: "私人债权人被要求削减一半以上的本金。这解决了一个国家的问题，也让市场第一次相信：主权债是会被削的。",
      bodyEn: "Private creditors are asked to write off more than half the principal. It solves one country's problem, and it teaches the market for the first time that a sovereign bond can be cut.",
      pressure: 0.34,
      equityShock: 0.07,
    },
    {
      day: 8,
      titleZh: "第四个国家，而且这个太大了",
      titleEn: "A fourth, and this one is too big",
      bodyZh: "一个大成员国的十年期收益率冲到 7% 以上。按这个利率，它借不起下一笔；而按它的体量，没有任何救助基金接得住。",
      bodyEn: "A large member's ten-year yield goes through 7%. At that rate it cannot finance the next issue, and at its size no rescue fund is big enough to catch it.",
      pressure: 0.46,
      equityShock: 0.1,
    },
    {
      day: 9,
      titleZh: "有人开始算「退出」",
      titleEn: "People start pricing an exit",
      bodyZh: "券商研究报告里出现了一个以前不存在的名词：成员国退出联盟之后，你的合同用哪种货币结算。",
      bodyEn: "Research notes start using a term that did not exist before: redenomination — which currency your contract settles in after a member leaves.",
      pressure: 0.38,
      equityShock: 0.09,
      minDetail: 2,
    },
  ],
  calls: [
    {
      id: "eu-c1",
      day: 2,
      direction: "in",
      fromZh: "边缘国央行",
      fromEn: "A periphery central bank",
      roleZh: "行长",
      roleEn: "Governor",
      lines: [
        { zh: "我们的银行手上全是我们自己的国债。利差再宽两百个点，三家银行的资本就归零。", en: "Our banks are full of our own government's bonds. Another two hundred basis points and three of them have no capital left." },
        { zh: "而要救它们的，还是我们自己。", en: "And the only people who can rescue them are us." },
      ],
      options: [
        {
          id: "separate",
          zh: "先把银行和主权分开。银行监管上收，救助不走你们的账。",
          en: "Separate the banks from the sovereign. Supervision comes up to the centre and the rescue does not go through your budget.",
          effect: { pressure: -0.16, credibility: 0.12 },
          replyZh: "那要改条约。可是……对，这是唯一能断掉这个圈的办法。",
          replyEn: "That needs a treaty change. And… yes. It is the only thing that cuts the loop.",
          tone: "good",
        },
        {
          id: "domestic",
          zh: "让你们的银行继续买本国国债，把利差压住。",
          en: "Have your banks keep buying your own bonds and hold the spread down.",
          effect: { pressure: -0.12, equityMul: 0.94 },
          replyZh: "短期有效。长期……我们是在把炸药往同一个箱子里装。",
          replyEn: "It works for now. In the long run we are putting more of the explosive into the same box.",
          tone: "bad",
        },
      ],
    },
    {
      id: "eu-c2",
      day: 4,
      direction: "in",
      fromZh: "财政部长会议",
      fromEn: "The finance ministers",
      roleZh: "轮值主席",
      roleEn: "In the chair",
      lines: [
        { zh: "行长，我们想知道央行能做到哪一步。", en: "President — we want to know how far the central bank can go." },
        { zh: "有人说你们买成员国国债就是财政货币化。", en: "There are those who say buying member states' bonds is monetary financing." },
      ],
      options: [
        {
          id: "mandate",
          zh: "在职责范围内我们什么都能做。范围之外，一步都不行。这两句必须一起说。",
          en: "Within our mandate we can do anything. Outside it, nothing at all. Those two sentences go together.",
          effect: { credibility: 0.16, pressure: -0.06 },
          replyZh: "那请你把「范围」写清楚。市场要的是边界，不是热情。",
          replyEn: "Then define the mandate precisely. What the market wants is a boundary, not enthusiasm.",
          tone: "good",
        },
        {
          id: "hedge",
          zh: "这个问题需要法律意见。我们会研究。",
          en: "That requires a legal opinion. We will study it.",
          effect: { pressure: 0.12, credibility: -0.1 },
          replyZh: "「我们会研究」在债券市场上的意思是「他们不会做」。",
          replyEn: "'We will study it' means, in a bond market, that you will not do it.",
          tone: "bad",
        },
      ],
    },
    {
      id: "eu-c3",
      day: 6,
      direction: "in",
      fromZh: "一家大型保险公司",
      fromEn: "A large insurer",
      roleZh: "首席投资官",
      roleEn: "Chief investment officer",
      minDetail: 1,
      lines: [
        { zh: "重组方案要我们削减一半本金。我们是长期持有人，不是投机者。", en: "The restructuring asks us to write off half the principal. We are long-term holders, not speculators." },
        { zh: "如果这次能削，下次为什么不能？", en: "If it can be cut this time, why not next time?" },
      ],
      options: [
        {
          id: "oneoff",
          zh: "这是唯一一次，而且我会公开这么说。",
          en: "This is the only time, and I will say so publicly.",
          effect: { pressure: -0.14, credibility: -0.12 },
          replyZh: "我希望你说到做到。因为这句话我们会拿去定价。",
          replyEn: "I hope you mean it, because we are going to price that sentence.",
          tone: "info",
        },
        {
          id: "honest",
          zh: "我不能保证。我能保证的是：我们会让这种情况不再有必要发生。",
          en: "I cannot promise that. What I can promise is that we will make it unnecessary.",
          effect: { pressure: 0.06, credibility: 0.14 },
          replyZh: "……这个回答诚实得让人不舒服。但我会照它调整仓位。",
          replyEn: "…That is an uncomfortably honest answer. I will position for it.",
          tone: "good",
        },
      ],
    },
    {
      id: "eu-c4",
      day: 8,
      direction: "out",
      fromZh: "北岸 · 投资会议",
      fromEn: "Northbank — an investment conference",
      roleZh: "讲台",
      roleEn: "The podium",
      minDetail: 1,
      lines: [
        { zh: "行长，台下坐着三百个做空你们的人。演讲稿在您手上。", en: "President — there are three hundred people out there short of you. The speech is in your hand." },
        { zh: "原稿是四页技术说明。您还有九十秒决定要不要照念。", en: "The draft is four pages of technical explanation. You have ninety seconds to decide whether to read it." },
      ],
      options: [
        {
          id: "whatever",
          zh: "不念了。我说一句：在职责范围内，不惜一切代价——相信我，这就够了。",
          en: "I am not reading it. One sentence: within our mandate, whatever it takes — and believe me, it will be enough.",
          effect: { pressure: -0.34, equityMul: 1.08, credibility: 0.18 },
          replyZh: "……大厅安静了三秒。然后所有人开始打电话。",
          replyEn: "…The room is silent for three seconds. Then everybody reaches for a phone.",
          tone: "good",
        },
        {
          id: "technical",
          zh: "照念。技术细节才是可信的东西。",
          en: "Read it. The technical detail is what is credible.",
          effect: { pressure: 0.06, credibility: 0.06 },
          replyZh: "掌声很礼貌。收益率没有动。",
          replyEn: "The applause is polite. The yield does not move.",
          tone: "info",
        },
        {
          id: "warn",
          zh: "警告他们：做空这个联盟，是在和一张无限大的资产负债表打赌。",
          en: "Warn them: shorting this union is a bet against an unlimited balance sheet.",
          effect: { pressure: -0.16, credibility: -0.06 },
          replyZh: "有几个人笑了。不过下午的报价确实变谨慎了。",
          replyEn: "A few of them laugh. The afternoon quotes do get more careful, though.",
          tone: "info",
        },
      ],
    },
    {
      id: "eu-c5",
      day: 9,
      direction: "in",
      fromZh: "宪法法院 · 书记官",
      fromEn: "The constitutional court",
      roleZh: "书记官",
      roleEn: "Registrar",
      minDetail: 2,
      lines: [
        { zh: "有人提起诉讼，主张您的购债计划越权。", en: "A case has been filed arguing that your purchase programme exceeds your powers." },
        { zh: "法院想知道：这个计划有没有上限？", en: "The court wishes to know whether the programme has a limit." },
      ],
      options: [
        {
          id: "conditional",
          zh: "有条件，没有金额上限。申请的国家必须先接受一个调整方案。",
          en: "It has conditions and no numerical limit. A country has to accept an adjustment programme first.",
          effect: { pressure: -0.2, credibility: 0.15 },
          replyZh: "这个回答法院能接受。市场也能——因为它同时说明了力量和边界。",
          replyEn: "The court can work with that. So can the market: it states the power and the boundary in the same breath.",
          tone: "good",
        },
        {
          id: "capped",
          zh: "有上限。我现在就给一个数字。",
          en: "There is a limit. I will give you a number now.",
          effect: { pressure: 0.24, credibility: 0.05 },
          replyZh: "法院满意了。市场拿到了一个可以去测试的数字。",
          replyEn: "The court is satisfied. The market now has a number it can test.",
          tone: "bad",
        },
      ],
    },
    {
      id: "eu-c6",
      day: 10,
      direction: "out",
      fromZh: "边缘国储户热线",
      fromEn: "The periphery's public line",
      roleZh: "一位退休教师",
      roleEn: "A retired teacher",
      minDetail: 3,
      seats: ["governor", "retail"],
      lines: [
        { zh: "我在银行的钱，如果我们国家退出，会变成什么？", en: "The money in my bank — if my country leaves, what does it become?" },
      ],
      options: [
        {
          id: "plain",
          zh: "还是联盟的钱。只要联盟在，它就是联盟的钱。我们正在做的事，就是让这个问题永远不用回答。",
          en: "The union's money, the same as today. As long as the union holds, that is what it is — and what we are doing is making sure the question never has to be answered.",
          effect: { pressure: -0.1, credibility: 0.12 },
          replyZh: "那我就不去排队了。谢谢您接我的电话。",
          replyEn: "Then I will not queue tomorrow. Thank you for taking the call.",
          tone: "good",
        },
        {
          id: "nocomment",
          zh: "我不能对假设性问题作答。",
          en: "I cannot answer a hypothetical.",
          effect: { pressure: 0.14, equityMul: 0.96 },
          replyZh: "……我明白了。我明天早上去取钱。",
          replyEn: "…I understand. I will go and take it out in the morning.",
          tone: "bad",
        },
      ],
    },
  ],
  objectives: {
    retail: retailObjective({
      target: 0.74,
      titleZh: "你的钱在哪个国家的银行里",
      titleEn: "Which country is your bank in",
      howZh: "你用的是一种跨国货币，但你的存款在一家本国银行里。这一关要判断的是：如果这个联盟散了，你账上的数字会用哪种货币结算。",
      howEn: "You hold a cross-border currency, and your deposit is in a domestic bank. What you have to judge is which currency the number in your account settles in if the union comes apart.",
      trapZh: "这一关的风险不是价格，是「重新计价」。而一旦所有人同时想通这件事，你就已经搬不走了。",
      trapEn: "The risk here is not the price, it is redenomination. And by the time everybody works that out at once, you can no longer move.",
    }),
    trader: traderObjective({
      target: 0.18,
      titleZh: "主权债交易台",
      titleEn: "The sovereign desk",
      howZh: "你做的是国债利差。这一关的信号不在财政数字里，在政治日历上：哪一天开会、谁说了什么、法院怎么判。数字每季度更新一次，句子每天都在动。",
      howEn: "You trade sovereign spreads. The signal here is not in the fiscal numbers, it is in the political calendar: who meets on which day, who said what, how the court rules. The numbers update quarterly; the sentences move every day.",
      trapZh: "别在没有读完条件的情况下做多承诺。「不惜一切代价」后面永远跟着一句「在我们的职责范围内」。",
      trapEn: "Do not buy the promise without reading the conditions. 'Whatever it takes' is always preceded by 'within our mandate'.",
    }),
    fund: {
      side: "attack",
      kind: "breakPeg",
      target: 0,
      titleZh: "做空这个联盟",
      titleEn: "Short the union",
      howZh: "你的论点很硬：这些国家借的是它们印不出来的钱，救助基金的规模接不住最大的那个成员。你要做的是把利差推到一级市场关门的位置。",
      howEn: "Your thesis is a hard one: these countries borrow money they cannot print, and no rescue fund is large enough to catch the biggest of them. Push the spread to where the primary market shuts.",
      winZh: "在最后一天结束前让主权利差失控。",
      winEn: "Force the sovereign spread out of control before the last day ends.",
      trapZh: "你在和一个可以无限量创造这种货币的机构对赌。只要它愿意说出那句话，而且所有人相信它说得出口，你的论点当天作废——历史上正是这样结束的。",
      trapEn: "You are betting against an institution that can create this currency without limit. The day it is willing to say so — and be believed — your thesis is void. That is exactly how it ended.",
    },
    governor: {
      side: "defend",
      kind: "contain",
      target: 0.68,
      equityFloor: 50,
      titleZh: "不惜一切代价",
      titleEn: "Whatever it takes",
      howZh: "你有三张牌，而最贵的那张其实不花钱。紧缩能压住赤字、压住利差，但它同时在缩小你用来衡量赤字的那个经济体——加得太狠，比例反而更难看。救助基金能直接买回压力，但它的规模所有人都算得出来，接不住大成员国。二级市场购债能托住银行和经济。最后一张是一句公开承诺：它一分钱不花，却需要所有人相信钱在后面——所以必须在你还有弹药、也还有法律依据的时候说。",
      howEn: "Three cards, and the expensive one costs nothing. Austerity narrows the deficit and the spread, and shrinks the economy the deficit is measured against — push it too far and the ratio gets worse, not better. The rescue fund buys pressure back directly, and everybody can do the arithmetic on its size: it cannot catch the large members. Buying in the secondary market holds up the banks and the economy. The last card is one public commitment. It spends nothing and it requires everybody to believe the money is behind it — so it has to be made while you still have ammunition and still have a legal basis.",
      winZh: "撑满全部时段、利差不失控，收盘时经济与银行指数在 50 以上，并且利差压力回落到 0.68 以下。",
      winEn: "Last every session with the spread under control, the economy and banking index above 50 at the close, and spread pressure back under 0.68.",
      trapZh: "紧缩是这一关最常见的死法。它在账面上永远是对的，在政治上有天花板，而在算术上——分母也在跟着缩。",
      trapEn: "Austerity is how this scenario is usually lost. It is always right on paper, it has a political ceiling, and arithmetically the denominator is shrinking with it.",
    },
  },
};
